// GENERATED by ./generate-concert-ecosystem from the Pure models -- do not edit: regenerated on every run.
package io.concert.eco.order_events;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.fasterxml.jackson.databind.JsonNode;
import io.concert.common.EventEnvelope;
import io.concert.common.Json;
import io.concert.common.TaskQueues;
import io.concert.common.api.SmStateRow;
import io.concert.model.runtime.ModelJson;
import io.concert.model.runtime.ModelObject;
import io.concert.orchestration.DispatchActivitiesImpl;
import io.concert.orchestration.IngestDispatcher;
import io.concert.orchestration.KeyLockWorkflowImpl;
import io.concert.sdk.EntitySnapshotPublisher;
import io.concert.sdk.events.EventCatalog;
import io.concert.sdk.events.EventWorkerBootstrap;
import io.concert.store.InMemoryStateStore;
import io.concert.store.TraceWriter;
import io.temporal.testing.TestEnvironmentOptions;
import io.temporal.testing.TestWorkflowEnvironment;
import io.temporal.worker.Worker;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Deque;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.stream.Stream;
import org.junit.jupiter.api.Test;

/**
 * Checks the generated event samples and runs every event flow ({@code samples/event-flows/*.json}) through the real
 * pipeline on Temporal's in-memory server: ingest dispatcher, lock chain, processors and your handlers. Each event
 * of a flow is sent once the previous one's causation tree settled (no event NEW any more). A flow may list the
 * expected status per event type ({@code "expect": {"OrderCreateEvent": "DONE"}}); without it, no event may
 * end without a handler.
 */
class OrderEventsEventFlowsTest {

    private static final Path SAMPLES = Path.of(System.getProperty("ecosystem.samples", "samples"));

    @Test
    void eventSamplesBindAndEveryTypeHasAHandler() throws IOException {
        int checked = 0;
        for (EventCatalog.EventType type : OrderEventsEventTypes.types()) {
            assertNotNull(OrderEventsEventTypes.handlers(type.domain()).get(type.name()), "no handler for " + type.name());
            Path sample = SAMPLES.resolve("events").resolve(type.name() + ".json");
            if (!Files.exists(sample)) {
                continue;
            }
            Object bound = ModelJson.read(Files.readString(sample), type.payloadType());
            if (bound instanceof ModelObject mo) {
                assertEquals(List.of(), mo.validationErrors(), sample.toString());
            }
            checked++;
        }
        assertTrue(checked > 0, "no event samples under " + SAMPLES.toAbsolutePath());
    }

    @Test
    void eventFlowsSettleThroughYourHandlers() throws IOException {
        System.setProperty("TEMPORAL_SEARCH_ATTRIBUTES", "false");
        InMemoryStateStore store = new InMemoryStateStore();
        List<Path> flows;
        try (Stream<Path> s = Files.list(SAMPLES.resolve("event-flows"))) {
            flows = s.filter(p -> p.toString().endsWith(".json")).sorted().toList();
        }
        assertTrue(!flows.isEmpty(), "no event flows");
        try (TestWorkflowEnvironment env = TestWorkflowEnvironment.newInstance(
                TestEnvironmentOptions.newBuilder().setUseTimeskipping(false).build());
                TraceWriter traces = new TraceWriter(store, 100_000, 500, 10)) {
            DispatchActivitiesImpl dispatch = new DispatchActivitiesImpl(env.getWorkflowClient(), traces);
            Worker orch = env.newWorker(TaskQueues.ORCHESTRATION);
            orch.registerWorkflowImplementationTypes(KeyLockWorkflowImpl.class);
            orch.registerActivitiesImplementations(dispatch);
            for (String domain : OrderEventsEventTypes.DOMAINS) {
                EventWorkerBootstrap.registerOn(env.newWorker(TaskQueues.events(domain)), env.getWorkflowClient(), store,
                        OrderEventsEventTypes.handlers(domain), EventWorkerBootstrap.Options.defaults().withPublisher(EntitySnapshotPublisher.logging()));
            }
            env.start();
            try (IngestDispatcher dispatcher = new IngestDispatcher(store, traces, dispatch, Set.of(), 64)) {
                int n = 0;
                for (Path flow : flows) {
                    JsonNode f = Json.MAPPER.readTree(Files.readString(flow));
                    List<SmStateRow> rows = new ArrayList<>();
                    for (JsonNode e : f.path("events")) {
                        JsonNode p = e.get("payload");
                        EventEnvelope event = OrderEventsEvents.eventEnvelope(e.path("eventType").asText(),
                                p == null || p.isNull() ? null : Json.write(p), 0, flow.getFileName() + "-" + n++);
                        dispatcher.dispatchBatch(List.of(event));
                        rows.addAll(settle(store, event.eventId(), flow.getFileName().toString()));
                    }
                    JsonNode expect = f.get("expect");
                    for (SmStateRow r : rows) {
                        JsonNode d = Json.MAPPER.readTree(r.data());
                        String type = d.path("eventType").asText();
                        if (expect != null && expect.has(type)) {
                            assertEquals(expect.get(type).asText(), r.state(), flow.getFileName() + ": " + r.workflowId() + " " + d);
                        } else {
                            assertTrue(!d.path("error").asText("").startsWith("no handler"), flow.getFileName() + ": " + d);
                        }
                    }
                    if (expect != null) {
                        for (Map.Entry<String, JsonNode> x : expect.properties()) {
                            assertTrue(rows.stream().anyMatch(r -> r.smType().equals(smType(x.getKey()))),
                                    flow.getFileName() + ": no " + x.getKey() + " event in the flow's causation trees");
                        }
                    }
                }
            }
        }
    }

    /** {@code OrderCreateEvent} -> {@code evt_order_create_event} (the lifecycle rows' smType). */
    private static String smType(String eventType) {
        return io.concert.sdk.events.EventRows.eventSmType(eventType);
    }

    /** Waits until the event and all of its descendants have left NEW; returns their lifecycle rows. */
    private static List<SmStateRow> settle(InMemoryStateStore store, String rootId, String flow) {
        long deadline = System.currentTimeMillis() + 30_000;
        while (true) {
            List<SmStateRow> rows = new ArrayList<>();
            boolean settled = true;
            Deque<String> todo = new ArrayDeque<>(List.of(rootId));
            while (!todo.isEmpty() && settled) {
                SmStateRow r = store.loadState("event:" + todo.pop()).orElse(null);
                if (r == null || r.state().equals("NEW")) {
                    settled = false;
                    break;
                }
                rows.add(r);
                Json.read(r.data(), JsonNode.class).path("children").forEach(c -> todo.add(c.asText()));
            }
            if (settled) {
                return rows;
            }
            assertTrue(System.currentTimeMillis() < deadline, flow + ": " + rootId + " did not settle; rows so far: " + rows);
            try {
                Thread.sleep(25);
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
                throw new AssertionError("interrupted");
            }
        }
    }
}
