// GENERATED by ./generate-concert-ecosystem from the Pure models -- do not edit: regenerated on every run.
package io.concert.eco.trading_gen;

import com.fasterxml.jackson.databind.JsonNode;
import io.concert.sdk.LockTemplates;
import io.concert.sdk.StateMachineSpec;
import java.util.List;
import java.util.Map;

/**
 * State machine {@code gen_trading_execution} declared on {@code trading::order::Execution} (order.pure:117:1).
 *
 * <pre>
 *   initial PENDING_NEW; terminal FILLED, CANCELLED, REJECTED
 *   PENDING_NEW -route-&gt; ROUTED : trading::command::RouteCommand
 *   ROUTED -fill-&gt; PARTIALLY_FILLED : trading::command::FillCommand
 *   ROUTED -complete_fill-&gt; FILLED : trading::command::FillCommand
 *   ROUTED -cancel-&gt; CANCELLED : trading::command::CancelCommand
 *   ROUTED -reject-&gt; REJECTED : trading::command::RejectCommand
 *   PARTIALLY_FILLED -fill-&gt; PARTIALLY_FILLED : trading::command::FillCommand
 *   PARTIALLY_FILLED -complete_fill-&gt; FILLED : trading::command::FillCommand
 *   PARTIALLY_FILLED -cancel-&gt; CANCELLED : trading::command::CancelCommand
 * </pre>
 */
public final class GenTradingExecutionSpec {
    private GenTradingExecutionSpec() {}

    /** smType: task queue {@code sm-gen_trading_execution}, workflow ids {@code gen_trading_execution:<key>}. */
    public static final String TYPE = "gen_trading_execution";

    /** Qualified Pure name of the root (data) class. */
    public static final String ROOT_CLASS = "trading::order::Execution";

    /** Property set to the instance key, or {@code null}. */
    public static final String ID_PROPERTY = "execId";

    /** Enum property kept equal to the state, or {@code null}. */
    public static final String STATUS_PROPERTY = "status";

    public static final StateMachineSpec SPEC = StateMachineSpec.startingAt("PENDING_NEW")
            .on("PENDING_NEW", "route", "ROUTED", io.concert.eco.trading_gen.model.trading.command.RouteCommand.class)
            .on("ROUTED", "fill", "PARTIALLY_FILLED", io.concert.eco.trading_gen.model.trading.command.FillCommand.class)
            .on("ROUTED", "complete_fill", "FILLED", io.concert.eco.trading_gen.model.trading.command.FillCommand.class)
            .on("ROUTED", "cancel", "CANCELLED", io.concert.eco.trading_gen.model.trading.command.CancelCommand.class)
            .on("ROUTED", "reject", "REJECTED", io.concert.eco.trading_gen.model.trading.command.RejectCommand.class)
            .on("PARTIALLY_FILLED", "fill", "PARTIALLY_FILLED", io.concert.eco.trading_gen.model.trading.command.FillCommand.class)
            .on("PARTIALLY_FILLED", "complete_fill", "FILLED", io.concert.eco.trading_gen.model.trading.command.FillCommand.class)
            .on("PARTIALLY_FILLED", "cancel", "CANCELLED", io.concert.eco.trading_gen.model.trading.command.CancelCommand.class)
            .build();

    /**
     * Lock key templates per event type, beyond the target entity key (always implied): {@code {id}} is
     * the instance key, {@code {field}} a payload field.
     */
    public static final Map<String, List<String>> LOCKS = Map.ofEntries(
            Map.entry("route", List.of("gen_trading_order:{orderId}")),
            Map.entry("fill", List.of("gen_trading_order:{orderId}")),
            Map.entry("complete_fill", List.of("gen_trading_order:{orderId}")),
            Map.entry("cancel", List.of("gen_trading_order:{orderId}")),
            Map.entry("reject", List.of("gen_trading_order:{orderId}")));

    /** The lock keys of an event, rendered from its payload. */
    public static List<String> lockKeys(String eventType, String instanceKey, JsonNode payload) {
        List<String> templates = LOCKS.get(eventType);
        if (templates == null) {
            throw new IllegalArgumentException(TYPE + " has no event " + eventType + ", expected one of " + LOCKS.keySet());
        }
        return LockTemplates.render(templates, instanceKey, payload);
    }
}
