// GENERATED by ./generate-concert-ecosystem from the Pure models -- do not edit: regenerated on every run.
package io.concert.eco.trading_gen;

import com.fasterxml.jackson.databind.JsonNode;
import io.concert.sdk.LockTemplates;
import io.concert.sdk.StateMachineSpec;
import java.util.List;
import java.util.Map;

/**
 * State machine {@code gen_trading_order} declared on {@code trading::order::Order} (order.pure:62:1).
 *
 * <pre>
 *   initial PENDING_NEW; terminal REJECTED, CANCELLED, FILLED
 *   PENDING_NEW -submit-&gt; NEW : trading::command::NewOrderCommand
 *   NEW -ack-&gt; ACKED : trading::command::AckCommand
 *   NEW -reject-&gt; REJECTED : trading::command::RejectCommand
 *   ACKED -route-&gt; WORKING : trading::command::RouteCommand
 *   ACKED -cancel-&gt; CANCELLED : trading::command::CancelCommand
 *   WORKING -route-&gt; WORKING : trading::command::RouteCommand
 *   WORKING -fill-&gt; PARTIALLY_FILLED : trading::command::FillCommand
 *   WORKING -complete_fill-&gt; ALLOCATING : trading::command::FillCommand
 *   WORKING -cancel-&gt; CANCELLED : trading::command::CancelCommand
 *   PARTIALLY_FILLED -route-&gt; PARTIALLY_FILLED : trading::command::RouteCommand
 *   PARTIALLY_FILLED -fill-&gt; PARTIALLY_FILLED : trading::command::FillCommand
 *   PARTIALLY_FILLED -complete_fill-&gt; ALLOCATING : trading::command::FillCommand
 *   PARTIALLY_FILLED -cancel-&gt; CANCEL_ALLOCATING : trading::command::CancelCommand
 *   ALLOCATING -allocate-&gt; ALLOCATING : trading::command::AllocateCommand
 *   ALLOCATING -close-&gt; FILLED : trading::command::CloseOrderCommand
 *   CANCEL_ALLOCATING -allocate-&gt; CANCEL_ALLOCATING : trading::command::AllocateCommand
 *   CANCEL_ALLOCATING -close-&gt; CANCELLED : trading::command::CloseOrderCommand
 * </pre>
 */
public final class GenTradingOrderSpec {
    private GenTradingOrderSpec() {}

    /** smType: task queue {@code sm-gen_trading_order}, workflow ids {@code gen_trading_order:<key>}. */
    public static final String TYPE = "gen_trading_order";

    /** Qualified Pure name of the root (data) class. */
    public static final String ROOT_CLASS = "trading::order::Order";

    /** Property set to the instance key, or {@code null}. */
    public static final String ID_PROPERTY = "orderId";

    /** Enum property kept equal to the state, or {@code null}. */
    public static final String STATUS_PROPERTY = "status";

    public static final StateMachineSpec SPEC = StateMachineSpec.startingAt("PENDING_NEW")
            .on("PENDING_NEW", "submit", "NEW", io.concert.eco.trading_gen.model.trading.command.NewOrderCommand.class)
            .on("NEW", "ack", "ACKED", io.concert.eco.trading_gen.model.trading.command.AckCommand.class)
            .on("NEW", "reject", "REJECTED", io.concert.eco.trading_gen.model.trading.command.RejectCommand.class)
            .on("ACKED", "route", "WORKING", io.concert.eco.trading_gen.model.trading.command.RouteCommand.class)
            .on("ACKED", "cancel", "CANCELLED", io.concert.eco.trading_gen.model.trading.command.CancelCommand.class)
            .on("WORKING", "route", "WORKING", io.concert.eco.trading_gen.model.trading.command.RouteCommand.class)
            .on("WORKING", "fill", "PARTIALLY_FILLED", io.concert.eco.trading_gen.model.trading.command.FillCommand.class)
            .on("WORKING", "complete_fill", "ALLOCATING", io.concert.eco.trading_gen.model.trading.command.FillCommand.class)
            .on("WORKING", "cancel", "CANCELLED", io.concert.eco.trading_gen.model.trading.command.CancelCommand.class)
            .on("PARTIALLY_FILLED", "route", "PARTIALLY_FILLED", io.concert.eco.trading_gen.model.trading.command.RouteCommand.class)
            .on("PARTIALLY_FILLED", "fill", "PARTIALLY_FILLED", io.concert.eco.trading_gen.model.trading.command.FillCommand.class)
            .on("PARTIALLY_FILLED", "complete_fill", "ALLOCATING", io.concert.eco.trading_gen.model.trading.command.FillCommand.class)
            .on("PARTIALLY_FILLED", "cancel", "CANCEL_ALLOCATING", io.concert.eco.trading_gen.model.trading.command.CancelCommand.class)
            .on("ALLOCATING", "allocate", "ALLOCATING", io.concert.eco.trading_gen.model.trading.command.AllocateCommand.class)
            .on("ALLOCATING", "close", "FILLED", io.concert.eco.trading_gen.model.trading.command.CloseOrderCommand.class)
            .on("CANCEL_ALLOCATING", "allocate", "CANCEL_ALLOCATING", io.concert.eco.trading_gen.model.trading.command.AllocateCommand.class)
            .on("CANCEL_ALLOCATING", "close", "CANCELLED", io.concert.eco.trading_gen.model.trading.command.CloseOrderCommand.class)
            .build();

    /**
     * Lock key templates per event type, beyond the target entity key (always implied): {@code {id}} is
     * the instance key, {@code {field}} a payload field.
     */
    public static final Map<String, List<String>> LOCKS = Map.ofEntries(
            Map.entry("submit", List.of("account:{accountId}")),
            Map.entry("ack", List.of("account:{accountId}")),
            Map.entry("reject", List.of("account:{accountId}")),
            Map.entry("route", List.of("account:{accountId}")),
            Map.entry("cancel", List.of("account:{accountId}")),
            Map.entry("fill", List.of("account:{accountId}")),
            Map.entry("complete_fill", List.of("account:{accountId}")),
            Map.entry("allocate", List.of("account:{accountId}")),
            Map.entry("close", List.of("account:{accountId}")));

    /** The lock keys of an event, rendered from its payload. */
    public static List<String> lockKeys(String eventType, String instanceKey, JsonNode payload) {
        List<String> templates = LOCKS.get(eventType);
        if (templates == null) {
            throw new IllegalArgumentException(TYPE + " has no event " + eventType + ", expected one of " + LOCKS.keySet());
        }
        return LockTemplates.render(templates, instanceKey, payload);
    }
}
