// GENERATED by ./generate-concert-ecosystem from the Pure models -- do not edit: regenerated on every run.
package io.concert.eco.trading_gen;

import com.fasterxml.jackson.databind.JsonNode;
import io.concert.sdk.LockTemplates;
import io.concert.sdk.StateMachineSpec;
import java.util.List;
import java.util.Map;

/**
 * State machine {@code gen_trading_allocation} declared on {@code trading::order::Allocation} (order.pure:170:1).
 *
 * <pre>
 *   initial PENDING; terminal CONFIRMED
 *   PENDING -allocate-&gt; ALLOCATED : trading::command::AllocateCommand
 *   ALLOCATED -confirm-&gt; CONFIRMED : trading::command::ConfirmAllocationCommand
 * </pre>
 */
public final class GenTradingAllocationSpec {
    private GenTradingAllocationSpec() {}

    /** smType: task queue {@code sm-gen_trading_allocation}, workflow ids {@code gen_trading_allocation:<key>}. */
    public static final String TYPE = "gen_trading_allocation";

    /** Qualified Pure name of the root (data) class. */
    public static final String ROOT_CLASS = "trading::order::Allocation";

    /** Property set to the instance key, or {@code null}. */
    public static final String ID_PROPERTY = "allocId";

    /** Enum property kept equal to the state, or {@code null}. */
    public static final String STATUS_PROPERTY = "status";

    public static final StateMachineSpec SPEC = StateMachineSpec.startingAt("PENDING")
            .on("PENDING", "allocate", "ALLOCATED", io.concert.eco.trading_gen.model.trading.command.AllocateCommand.class)
            .on("ALLOCATED", "confirm", "CONFIRMED", io.concert.eco.trading_gen.model.trading.command.ConfirmAllocationCommand.class)
            .build();

    /**
     * Lock key templates per event type, beyond the target entity key (always implied): {@code {id}} is
     * the instance key, {@code {field}} a payload field.
     */
    public static final Map<String, List<String>> LOCKS = Map.ofEntries(
            Map.entry("allocate", List.of("gen_trading_order:{orderId}", "account:{allocAccountId}")),
            Map.entry("confirm", List.of("gen_trading_order:{orderId}", "account:{allocAccountId}")));

    /** The lock keys of an event, rendered from its payload. */
    public static List<String> lockKeys(String eventType, String instanceKey, JsonNode payload) {
        List<String> templates = LOCKS.get(eventType);
        if (templates == null) {
            throw new IllegalArgumentException(TYPE + " has no event " + eventType + ", expected one of " + LOCKS.keySet());
        }
        return LockTemplates.render(templates, instanceKey, payload);
    }
}
