// GENERATED by ./generate-concert-ecosystem from the Pure models -- do not edit: regenerated on every run.
package io.concert.eco.trading_gen;

import com.fasterxml.jackson.databind.JsonNode;
import io.concert.common.Env;
import io.concert.common.EventEnvelope;
import io.concert.common.Json;
import io.concert.model.runtime.ModelJson;
import io.concert.model.runtime.ModelObject;
import io.concert.orchestration.KinesisClients;
import io.concert.sdk.LockTemplates;
import io.concert.sdk.MachineCatalog;
import io.concert.sdk.StateMachineSpec;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import software.amazon.awssdk.core.SdkBytes;
import software.amazon.awssdk.services.kinesis.KinesisClient;

/**
 * Sends events of ecosystem {@code trading-gen} to Kinesis ({@code INGEST_STREAM}, default
 * {@code concert-events}; {@code KINESIS_ENDPOINT}, e.g. {@code http://localhost:4566}), addressed and locked as
 * the Pure annotations declare: lock keys are rendered from the payload, the partition key is the first sorted
 * lock key. Payloads are checked against their model class before sending.
 *
 * <pre>
 * send &lt;smType&gt; &lt;eventType&gt; &lt;instanceKey&gt; [payload.json | - | '{...json...}']        entity style
 * flow &lt;flow.json&gt; [--delay-ms 500]     {"events": [...]}: {smType, instanceKey, eventType, payload}
 * list
 * </pre>
 */
public final class TradingGenEvents {
    private TradingGenEvents() {}

    public static void main(String[] args) throws Exception {
        try {
            run(args);
        } catch (IllegalArgumentException | java.io.UncheckedIOException e) {
            System.err.println("error: " + e.getMessage());
            System.exit(1);
        }
    }

    private static void run(String[] args) throws Exception {
        if (args.length == 0) {
            usage();
            System.exit(2);
        }
        switch (args[0]) {
            case "list" -> list();
            case "send" -> {
                if (args.length < 4) {
                    usage();
                    System.exit(2);
                }
                String payload = args.length > 4 ? readPayload(args[4]) : null;
                EventEnvelope e = envelope(args[1], args[2], args[3], payload);
                try (KinesisClient kinesis = KinesisClients.fromEnv()) {
                    publish(kinesis, e);
                }
            }
            case "flow" -> {
                if (args.length < 2) {
                    usage();
                    System.exit(2);
                }
                long delay = args.length > 3 && args[2].equals("--delay-ms") ? Long.parseLong(args[3]) : 500;
                flow(Path.of(args[1]), delay);
            }
            default -> {
                usage();
                System.exit(2);
            }
        }
    }

    private static void usage() {
        System.err.println("usage: "
                + "send <smType> <eventType> <instanceKey> [payload.json | - | '{json}']\n       "
                + "flow <flow.json> [--delay-ms N]\n       list"
                + "\nsmTypes: " + TradingGenMachines.ALL.keySet());
    }

    private static void list() {
        TradingGenMachines.ALL.forEach((type, machine) -> {
            System.out.println(type + "  (initial " + machine.spec().initialState() + ", terminal " + machine.spec().terminalStates() + ")");
            for (StateMachineSpec.Edge e : machine.spec().edges()) {
                System.out.printf("  %-14s %s -> %s  payload %s  locks %s%n", e.eventType(), e.from(), e.to(),
                        e.payloadType() == null ? "-" : e.payloadType().getSimpleName(), TradingGenMachines.LOCKS.get(type).get(e.eventType()));
            }
        });
    }

    private static String readPayload(String arg) throws IOException {
        if (arg.equals("-")) {
            return new String(System.in.readAllBytes(), StandardCharsets.UTF_8);
        }
        String t = arg.strip();
        return t.startsWith("{") || t.equals("null") ? t : Files.readString(Path.of(arg), StandardCharsets.UTF_8);
    }

    /** The payload bound to its model class and validated (multiplicities), then serialized back. */
    private static String checked(String payload, Class<?> type) {
        String json = payload == null || payload.isBlank() || payload.strip().equals("null") ? null : payload.strip();
        if (type != null && json != null) {
            Object bound = ModelJson.read(json, type);
            if (bound instanceof ModelObject mo && !mo.validationErrors().isEmpty()) {
                throw new IllegalArgumentException("invalid " + type.getSimpleName() + " payload: "
                        + String.join("; ", mo.validationErrors()));
            }
            json = ModelJson.write(bound);
        }
        return json;
    }

    private static JsonNode tree(String json) {
        try {
            return json == null ? null : Json.MAPPER.readTree(json);
        } catch (com.fasterxml.jackson.core.JsonProcessingException x) {
            throw new IllegalArgumentException("payload is not JSON: " + x.getOriginalMessage(), x);
        }
    }

    /**
     * An entity-style event, validated: the smType and event type exist, the payload binds to the event's payload class
     * and satisfies its multiplicities, and every lock key renders.
     */
    public static EventEnvelope envelope(String smType, String eventType, String instanceKey, String payload) {
        MachineCatalog.Machine machine = TradingGenMachines.get(smType);
        StateMachineSpec.Edge edge = machine.spec().edges().stream().filter(x -> x.eventType().equals(eventType)).findFirst()
                .orElseThrow(() -> new IllegalArgumentException(smType + " has no event " + eventType + "; events: "
                        + machine.spec().edges().stream().map(StateMachineSpec.Edge::eventType).distinct().toList()));
        String json = checked(payload, edge.payloadType());
        List<String> locks = LockTemplates.render(TradingGenMachines.LOCKS.get(smType).get(eventType), instanceKey, tree(json));
        return new EventEnvelope(smType + "-" + eventType + "-" + UUID.randomUUID(), smType, instanceKey, eventType, locks, json,
                System.currentTimeMillis(), 0);
    }

    private static void publish(KinesisClient kinesis, EventEnvelope e) {
        String stream = Env.get("INGEST_STREAM", "concert-events");
        String partitionKey = e.effectiveLockKeys().getFirst();
        kinesis.putRecord(b -> b.streamName(stream).partitionKey(partitionKey).data(SdkBytes.fromUtf8String(Json.write(e))));
        if (e.isEventStyle()) {
            System.out.printf("sent %s event %s (domain %s)  locks %s  (partition key %s)%s%n", e.eventId(), e.eventType(), e.domain(),
                    e.effectiveLockKeys(), partitionKey, e.scheduledAtMillis() > 0 ? "  scheduled at "
                            + java.time.Instant.ofEpochMilli(e.scheduledAtMillis()) : "");
        } else {
            System.out.printf("sent %s %s:%s %s  locks %s  (partition key %s)%n", e.eventId(), e.smType(), e.instanceKey(),
                    e.eventType(), e.effectiveLockKeys(), partitionKey);
        }
    }

    private static void flow(Path file, long delayMs) throws IOException, InterruptedException {
        JsonNode flow = Json.MAPPER.readTree(Files.readString(file, StandardCharsets.UTF_8));
        List<EventEnvelope> events = new ArrayList<>();
        for (JsonNode e : flow.path("events")) {
            JsonNode p = e.get("payload");
            String payload = p == null || p.isNull() ? null : Json.write(p);
            events.add(envelope(e.path("smType").asText(), e.path("eventType").asText(), e.path("instanceKey").asText(), payload));
        }
        System.out.printf("flow %s: %d events%n", flow.path("name").asText(file.getFileName().toString()), events.size());
        try (KinesisClient kinesis = KinesisClients.fromEnv()) {
            for (int i = 0; i < events.size(); i++) {
                if (i > 0 && delayMs > 0) {
                    Thread.sleep(delayMs); // events of one entity in order, even across shards
                }
                publish(kinesis, events.get(i));
            }
        }
    }

    /** smType to machine, for tests and tools. */
    public static Map<String, MachineCatalog.Machine> machines() {
        return TradingGenMachines.ALL;
    }
}
