// GENERATED by ./generate-concert-ecosystem from the Pure models -- do not edit: regenerated on every run.
package io.concert.eco.trading_gen;

import io.concert.sdk.MachineCatalog;
import io.concert.sdk.StateMachineRegistry;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * The machines of ecosystem {@code trading-gen} by smType: their specs and the model's class diagram
 * (for the worker, the event sender and, through the {@link MachineCatalog} SPI, the trace UI).
 */
public final class TradingGenMachines implements MachineCatalog {

    /** Mermaid class diagram of the ecosystem's model (all model files). */
    public static final String MODEL_MERMAID = mermaid(io.concert.eco.trading_gen.model.trading.CommandsModel.MERMAID, io.concert.eco.trading_gen.model.trading.CommonModel.MERMAID, io.concert.eco.trading_gen.model.trading.MarketdataModel.MERMAID, io.concert.eco.trading_gen.model.trading.OrderModel.MERMAID, io.concert.eco.trading_gen.model.trading.RefdataModel.MERMAID);

    /** In declaration order. */
    public static final Map<String, Machine> ALL = index(
            new Machine(GenTradingOrderSpec.TYPE, GenTradingOrderMachine.class, GenTradingOrderSpec.SPEC, MODEL_MERMAID),
            new Machine(GenTradingExecutionSpec.TYPE, GenTradingExecutionMachine.class, GenTradingExecutionSpec.SPEC, MODEL_MERMAID),
            new Machine(GenTradingFillSpec.TYPE, GenTradingFillMachine.class, GenTradingFillSpec.SPEC, MODEL_MERMAID),
            new Machine(GenTradingAllocationSpec.TYPE, GenTradingAllocationMachine.class, GenTradingAllocationSpec.SPEC, MODEL_MERMAID));

    /** Lock key templates per smType and event type. */
    public static final Map<String, Map<String, List<String>>> LOCKS = Map.ofEntries(
            Map.entry(GenTradingOrderSpec.TYPE, GenTradingOrderSpec.LOCKS),
            Map.entry(GenTradingExecutionSpec.TYPE, GenTradingExecutionSpec.LOCKS),
            Map.entry(GenTradingFillSpec.TYPE, GenTradingFillSpec.LOCKS),
            Map.entry(GenTradingAllocationSpec.TYPE, GenTradingAllocationSpec.LOCKS));

    private static Map<String, Machine> index(Machine... machines) {
        Map<String, Machine> m = new LinkedHashMap<>();
        for (Machine x : machines) {
            m.put(x.smType(), x);
        }
        return java.util.Collections.unmodifiableMap(m);
    }

    /** Merges generated {@code classDiagram}s (one per model file) into one diagram. */
    static String mermaid(String... diagrams) {
        StringBuilder sb = new StringBuilder("classDiagram\n");
        for (String d : diagrams) {
            sb.append(d.substring(d.indexOf('\n') + 1));
        }
        return sb.toString();
    }

    /** Registers the specs in {@link StateMachineRegistry}. */
    public static void registerSpecs() {
        ALL.forEach((type, m) -> StateMachineRegistry.register(type, m.spec()));
    }

    public static Machine get(String smType) {
        Machine m = ALL.get(smType);
        if (m == null) {
            throw new IllegalArgumentException("unknown smType " + smType + ", expected one of " + ALL.keySet());
        }
        return m;
    }

    @Override
    public String name() {
        return NAME;
    }

    @Override
    public List<Machine> machines() {
        return List.copyOf(ALL.values());
    }

    /** The ecosystem (module) name. */
    public static final String NAME = "trading-gen";
}
