// GENERATED by ./generate-concert-ecosystem from the Pure models -- do not edit: regenerated on every run.
package io.concert.eco.insurance;

import com.fasterxml.jackson.databind.JsonNode;
import io.concert.sdk.LockTemplates;
import io.concert.sdk.StateMachineSpec;
import java.util.List;
import java.util.Map;

/**
 * State machine {@code claim} declared on {@code insurance::Claim} (claim.pure:31:1).
 *
 * <pre>
 *   initial NEW; terminal WITHDRAWN, REJECTED, PAID
 *   NEW -file-&gt; OPEN : insurance::FileClaim
 *   OPEN -assess-&gt; ASSESSED : insurance::AssessClaim
 *   OPEN -withdraw-&gt; WITHDRAWN : insurance::WithdrawClaim
 *   ASSESSED -approve-&gt; APPROVED : insurance::ApproveClaim
 *   ASSESSED -reject-&gt; REJECTED : insurance::RejectClaim
 *   APPROVED -pay-&gt; PAID : insurance::PayClaim
 * </pre>
 */
public final class ClaimSpec {
    private ClaimSpec() {}

    /** smType: task queue {@code sm-claim}, workflow ids {@code claim:<key>}. */
    public static final String TYPE = "claim";

    /** Qualified Pure name of the root (data) class. */
    public static final String ROOT_CLASS = "insurance::Claim";

    /** Property set to the instance key, or {@code null}. */
    public static final String ID_PROPERTY = "claimId";

    /** Enum property kept equal to the state, or {@code null}. */
    public static final String STATUS_PROPERTY = "status";

    public static final StateMachineSpec SPEC = StateMachineSpec.startingAt("NEW")
            .on("NEW", "file", "OPEN", io.concert.eco.insurance.model.insurance.FileClaim.class)
            .on("OPEN", "assess", "ASSESSED", io.concert.eco.insurance.model.insurance.AssessClaim.class)
            .on("OPEN", "withdraw", "WITHDRAWN", io.concert.eco.insurance.model.insurance.WithdrawClaim.class)
            .on("ASSESSED", "approve", "APPROVED", io.concert.eco.insurance.model.insurance.ApproveClaim.class)
            .on("ASSESSED", "reject", "REJECTED", io.concert.eco.insurance.model.insurance.RejectClaim.class)
            .on("APPROVED", "pay", "PAID", io.concert.eco.insurance.model.insurance.PayClaim.class)
            .build();

    /**
     * Lock key templates per event type, beyond the target entity key (always implied): {@code {id}} is
     * the instance key, {@code {field}} a payload field.
     */
    public static final Map<String, List<String>> LOCKS = Map.ofEntries(
            Map.entry("file", List.of("policy:{policyId}")),
            Map.entry("assess", List.of()),
            Map.entry("withdraw", List.of()),
            Map.entry("approve", List.of("policy:{policyId}")),
            Map.entry("reject", List.of()),
            Map.entry("pay", List.of("policy:{policyId}", "payee:{payeeAccount}")));

    /** The lock keys of an event, rendered from its payload. */
    public static List<String> lockKeys(String eventType, String instanceKey, JsonNode payload) {
        List<String> templates = LOCKS.get(eventType);
        if (templates == null) {
            throw new IllegalArgumentException(TYPE + " has no event " + eventType + ", expected one of " + LOCKS.keySet());
        }
        return LockTemplates.render(templates, instanceKey, payload);
    }
}
