// GENERATED by ./generate-concert-ecosystem from the Pure models -- do not edit: regenerated on every run.
package io.concert.eco.insurance;

import io.concert.model.runtime.LegendModel;

/**
 * Generates the Java classes of the ecosystem's Pure models ({@code src/main/pure}) at compile time:
 * {@code a::b::X} becomes {@code io.concert.eco.insurance.model.a.b.X}.
 */
@LegendModel(files = {"concert/concert.pure", "claim.pure", "common.pure", "payout.pure", "policy.pure"}, root = "insurance::Claim", javaPackage = "io.concert.eco.insurance.model")
public final class InsuranceModels {
    private InsuranceModels() {}

    /** The {@code files} of the annotation. */
    public static final String[] FILES = {"concert/concert.pure", "claim.pure", "common.pure", "payout.pure", "policy.pure"};
}
