// GENERATED by ./generate-concert-ecosystem from the Pure models -- do not edit: regenerated on every run.
package io.concert.eco.insurance;

import io.concert.sdk.MachineCatalog;
import io.concert.sdk.StateMachineRegistry;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * The machines of ecosystem {@code insurance} by smType: their specs and the model's class diagram
 * (for the worker, the event sender and, through the {@link MachineCatalog} SPI, the trace UI).
 */
public final class InsuranceMachines implements MachineCatalog {

    /** Mermaid class diagram of the ecosystem's model (all model files). */
    public static final String MODEL_MERMAID = mermaid(io.concert.eco.insurance.model.insurance.ClaimModel.MERMAID, io.concert.eco.insurance.model.insurance.CommonModel.MERMAID, io.concert.eco.insurance.model.insurance.PayoutModel.MERMAID, io.concert.eco.insurance.model.insurance.PolicyModel.MERMAID);

    /** In declaration order. */
    public static final Map<String, Machine> ALL = index(
            new Machine(ClaimSpec.TYPE, ClaimMachine.class, ClaimSpec.SPEC, MODEL_MERMAID),
            new Machine(PayoutSpec.TYPE, PayoutMachine.class, PayoutSpec.SPEC, MODEL_MERMAID),
            new Machine(PolicySpec.TYPE, PolicyMachine.class, PolicySpec.SPEC, MODEL_MERMAID));

    /** Lock key templates per smType and event type. */
    public static final Map<String, Map<String, List<String>>> LOCKS = Map.ofEntries(
            Map.entry(ClaimSpec.TYPE, ClaimSpec.LOCKS),
            Map.entry(PayoutSpec.TYPE, PayoutSpec.LOCKS),
            Map.entry(PolicySpec.TYPE, PolicySpec.LOCKS));

    private static Map<String, Machine> index(Machine... machines) {
        Map<String, Machine> m = new LinkedHashMap<>();
        for (Machine x : machines) {
            m.put(x.smType(), x);
        }
        return java.util.Collections.unmodifiableMap(m);
    }

    /** Merges generated {@code classDiagram}s (one per model file) into one diagram. */
    static String mermaid(String... diagrams) {
        StringBuilder sb = new StringBuilder("classDiagram\n");
        for (String d : diagrams) {
            sb.append(d.substring(d.indexOf('\n') + 1));
        }
        return sb.toString();
    }

    /** Registers the specs in {@link StateMachineRegistry}. */
    public static void registerSpecs() {
        ALL.forEach((type, m) -> StateMachineRegistry.register(type, m.spec()));
    }

    public static Machine get(String smType) {
        Machine m = ALL.get(smType);
        if (m == null) {
            throw new IllegalArgumentException("unknown smType " + smType + ", expected one of " + ALL.keySet());
        }
        return m;
    }

    @Override
    public String name() {
        return NAME;
    }

    @Override
    public List<Machine> machines() {
        return List.copyOf(ALL.values());
    }

    /** The ecosystem (module) name. */
    public static final String NAME = "insurance";
}
