// GENERATED by ./generate-concert-ecosystem from the Pure models -- do not edit: regenerated on every run.
package io.concert.eco.insurance;

import io.concert.common.Env;
import io.concert.common.TemporalClients;
import io.concert.sdk.EntitySnapshotPublisher;
import io.concert.sdk.MachineCatalog;
import io.concert.sdk.WorkerBootstrap;
import io.concert.sink.SnapshotCodec;
import io.concert.store.StateStore;
import io.concert.store.Stores;
import io.temporal.worker.WorkerFactory;
import java.util.ArrayList;
import java.util.List;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Runs the workers of every machine of ecosystem {@code insurance} in one process (task queues
 * {@code sm-<smType>}). Environment as for every worker ({@code TEMPORAL_*}, {@code STORE_KIND},
 * {@code KAFKA_BOOTSTRAP}, ...); {@code INSURANCE_SM_TYPES} (comma separated) optionally restricts the types.
 */
public final class InsuranceWorkerMain {
    private static final Logger log = LoggerFactory.getLogger(InsuranceWorkerMain.class);

    private InsuranceWorkerMain() {}

    public static void main(String[] args) throws InterruptedException {
        StateStore store = Stores.fromEnv();
        var client = TemporalClients.fromEnv();
        InsuranceMachines.registerSpecs();
        // One Kafka producer for all types (no-op when KAFKA_BOOTSTRAP is empty); the schemaHash header is
        // the hash of the ecosystem's model diagram.
        String schemaHash = SnapshotCodec.schemaHash(InsuranceMachines.MODEL_MERMAID);
        EntitySnapshotPublisher snapshots = EntitySnapshotPublisher.fromEnv(
                type -> InsuranceMachines.ALL.containsKey(type) ? schemaHash : null);
        String types = Env.get("INSURANCE_SM_TYPES", String.join(",", InsuranceMachines.ALL.keySet()));
        List<WorkerFactory> factories = new ArrayList<>();
        for (String type : types.split(",")) {
            MachineCatalog.Machine machine = InsuranceMachines.get(type.trim());
            factories.add(WorkerBootstrap.start(client, store, machine.smType(), machine.impl(), snapshots));
            log.info("worker up for sm-{}", machine.smType());
        }
        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            factories.forEach(WorkerFactory::shutdown);
            store.close();
        }));
        Thread.currentThread().join();
    }
}
