// GENERATED by ./generate-concert-ecosystem from the Pure models -- do not edit: regenerated on every run.
package io.concert.eco.insurance;

import com.fasterxml.jackson.databind.JsonNode;
import io.concert.sdk.LockTemplates;
import io.concert.sdk.StateMachineSpec;
import java.util.List;
import java.util.Map;

/**
 * State machine {@code payout} declared on {@code insurance::Payout} (payout.pure:25:1).
 *
 * <pre>
 *   initial PENDING; terminal DISBURSED
 *   PENDING -schedule-&gt; SCHEDULED : insurance::SchedulePayout
 *   SCHEDULED -disburse-&gt; DISBURSED : insurance::DisbursePayout
 *   SCHEDULED -fail-&gt; FAILED : insurance::FailPayout
 *   FAILED -retry-&gt; SCHEDULED : insurance::SchedulePayout
 * </pre>
 */
public final class PayoutSpec {
    private PayoutSpec() {}

    /** smType: task queue {@code sm-payout}, workflow ids {@code payout:<key>}. */
    public static final String TYPE = "payout";

    /** Qualified Pure name of the root (data) class. */
    public static final String ROOT_CLASS = "insurance::Payout";

    /** Property set to the instance key, or {@code null}. */
    public static final String ID_PROPERTY = "payoutId";

    /** Enum property kept equal to the state, or {@code null}. */
    public static final String STATUS_PROPERTY = "status";

    public static final StateMachineSpec SPEC = StateMachineSpec.startingAt("PENDING")
            .on("PENDING", "schedule", "SCHEDULED", io.concert.eco.insurance.model.insurance.SchedulePayout.class)
            .on("SCHEDULED", "disburse", "DISBURSED", io.concert.eco.insurance.model.insurance.DisbursePayout.class)
            .on("SCHEDULED", "fail", "FAILED", io.concert.eco.insurance.model.insurance.FailPayout.class)
            .on("FAILED", "retry", "SCHEDULED", io.concert.eco.insurance.model.insurance.SchedulePayout.class)
            .build();

    /**
     * Lock key templates per event type, beyond the target entity key (always implied): {@code {id}} is
     * the instance key, {@code {field}} a payload field.
     */
    public static final Map<String, List<String>> LOCKS = Map.ofEntries(
            Map.entry("schedule", List.of("claim:{claimId}")),
            Map.entry("disburse", List.of("claim:{claimId}")),
            Map.entry("fail", List.of("claim:{claimId}")),
            Map.entry("retry", List.of("claim:{claimId}")));

    /** The lock keys of an event, rendered from its payload. */
    public static List<String> lockKeys(String eventType, String instanceKey, JsonNode payload) {
        List<String> templates = LOCKS.get(eventType);
        if (templates == null) {
            throw new IllegalArgumentException(TYPE + " has no event " + eventType + ", expected one of " + LOCKS.keySet());
        }
        return LockTemplates.render(templates, instanceKey, payload);
    }
}
