// GENERATED by ./generate-concert-ecosystem from the Pure models -- do not edit: regenerated on every run.
package io.concert.eco.insurance;

import com.fasterxml.jackson.databind.JsonNode;
import io.concert.sdk.LockTemplates;
import io.concert.sdk.StateMachineSpec;
import java.util.List;
import java.util.Map;

/**
 * State machine {@code policy} declared on {@code insurance::Policy} (policy.pure:24:1).
 *
 * <pre>
 *   initial QUOTED; terminal DECLINED, EXPIRED, CANCELLED
 *   QUOTED -bind-&gt; ACTIVE : insurance::BindPolicy
 *   QUOTED -decline-&gt; DECLINED : insurance::DeclineQuote
 *   ACTIVE -endorse-&gt; ACTIVE : insurance::EndorsePolicy
 *   ACTIVE -expire-&gt; EXPIRED : insurance::ExpirePolicy
 *   ACTIVE -cancel-&gt; CANCELLED : insurance::CancelPolicy
 * </pre>
 */
public final class PolicySpec {
    private PolicySpec() {}

    /** smType: task queue {@code sm-policy}, workflow ids {@code policy:<key>}. */
    public static final String TYPE = "policy";

    /** Qualified Pure name of the root (data) class. */
    public static final String ROOT_CLASS = "insurance::Policy";

    /** Property set to the instance key, or {@code null}. */
    public static final String ID_PROPERTY = "policyId";

    /** Enum property kept equal to the state, or {@code null}. */
    public static final String STATUS_PROPERTY = "status";

    public static final StateMachineSpec SPEC = StateMachineSpec.startingAt("QUOTED")
            .on("QUOTED", "bind", "ACTIVE", io.concert.eco.insurance.model.insurance.BindPolicy.class)
            .on("QUOTED", "decline", "DECLINED", io.concert.eco.insurance.model.insurance.DeclineQuote.class)
            .on("ACTIVE", "endorse", "ACTIVE", io.concert.eco.insurance.model.insurance.EndorsePolicy.class)
            .on("ACTIVE", "expire", "EXPIRED", io.concert.eco.insurance.model.insurance.ExpirePolicy.class)
            .on("ACTIVE", "cancel", "CANCELLED", io.concert.eco.insurance.model.insurance.CancelPolicy.class)
            .build();

    /**
     * Lock key templates per event type, beyond the target entity key (always implied): {@code {id}} is
     * the instance key, {@code {field}} a payload field.
     */
    public static final Map<String, List<String>> LOCKS = Map.ofEntries(
            Map.entry("bind", List.of()),
            Map.entry("decline", List.of()),
            Map.entry("endorse", List.of()),
            Map.entry("expire", List.of()),
            Map.entry("cancel", List.of()));

    /** The lock keys of an event, rendered from its payload. */
    public static List<String> lockKeys(String eventType, String instanceKey, JsonNode payload) {
        List<String> templates = LOCKS.get(eventType);
        if (templates == null) {
            throw new IllegalArgumentException(TYPE + " has no event " + eventType + ", expected one of " + LOCKS.keySet());
        }
        return LockTemplates.render(templates, instanceKey, payload);
    }
}
