// GENERATED by ./generate-concert-ecosystem from the Pure models -- do not edit: regenerated on every run.
package io.concert.eco.order_events;

import io.concert.sdk.events.EventCatalog;
import io.concert.sdk.events.OnError;
import java.util.List;
import java.util.Map;

/**
 * Event types of domain {@code inventory} (task queue {@code ev-inventory}), declared with {@code concert::event} in the
 * Pure models; discovered through the {@link EventCatalog} SPI (workers, event sender, trace UI).
 *
 * <pre>
 *   ReserveInventoryEvent  locks sku:{sku}  onError NON_BLOCKING  attempts 3
 *   RestockEvent  locks sku:{sku}  onError BLOCKING  attempts 3
 * </pre>
 */
public final class InventoryEventCatalog implements EventCatalog {

    public static final String DOMAIN = "inventory";

    /** {@code inventory::ReserveInventoryEvent} (inventory.pure:24:1). */
    public static final EventType RESERVE_INVENTORY_EVENT = new EventType("ReserveInventoryEvent", DOMAIN,
            io.concert.eco.order_events.model.inventory.ReserveInventoryEvent.class, List.of("sku:{sku}"), OnError.NON_BLOCKING, 3);

    /** {@code inventory::RestockEvent} (inventory.pure:36:1). */
    public static final EventType RESTOCK_EVENT = new EventType("RestockEvent", DOMAIN,
            io.concert.eco.order_events.model.inventory.RestockEvent.class, List.of("sku:{sku}"), OnError.BLOCKING, 3);

    /** Keyed state {@code inventory::Stock}: rows {@code state:<key>}. */
    public static final StateType STOCK_STATE = new StateType("Stock", io.concert.eco.order_events.model.inventory.Stock.class, "sku:{sku}");

    public static final List<EventType> EVENTS = List.of(RESERVE_INVENTORY_EVENT, RESTOCK_EVENT);

    public static final List<StateType> STATES = List.of(STOCK_STATE);

    /** {@code concert::event.emits} per event type. */
    public static final Map<String, List<String>> EMITS = Map.ofEntries(
            Map.entry("ReserveInventoryEvent", List.of()),
            Map.entry("RestockEvent", List.of()));

    @Override
    public String name() {
        return "order-events/inventory";
    }

    @Override
    public List<EventType> events() {
        return EVENTS;
    }

    @Override
    public List<StateType> states() {
        return STATES;
    }

    @Override
    public Map<String, List<String>> emits() {
        return EMITS;
    }

    @Override
    public String flowMermaid() {
        return OrderEventsEventTypes.FLOW_MERMAID;
    }

    @Override
    public String modelMermaid() {
        return OrderEventsEventTypes.MODEL_MERMAID;
    }
}
