// GENERATED by ./generate-concert-ecosystem from the Pure models -- do not edit: regenerated on every run.
package io.concert.eco.order_events;

import io.concert.sdk.events.EventCatalog;
import io.concert.sdk.events.EventCatalogs;
import io.concert.sdk.events.HandlerRegistry;
import java.util.List;

/**
 * The event-style part of ecosystem {@code order-events}: its catalogs (one per domain), the handlers
 * of each domain (your {@code *Handler} classes) and the diagrams.
 *
 * <pre>
 * flowchart LR
 *   subgraph inventory["domain inventory"]
 *     ReserveInventoryEvent["ReserveInventoryEvent&lt;br/&gt;&lt;small&gt;sku:{sku} · non-blocking&lt;/small&gt;"]
 *     RestockEvent["RestockEvent&lt;br/&gt;&lt;small&gt;sku:{sku}&lt;/small&gt;"]
 *   end
 *   subgraph orders["domain orders"]
 *     OrderCreateEvent["OrderCreateEvent&lt;br/&gt;&lt;small&gt;order:{orderId}, customer:{customerId}&lt;/small&gt;"]
 *     OrderAcceptedEvent["OrderAcceptedEvent&lt;br/&gt;&lt;small&gt;order:{orderId}&lt;/small&gt;"]
 *     OrderRejectedEvent["OrderRejectedEvent&lt;br/&gt;&lt;small&gt;order:{orderId}&lt;/small&gt;"]
 *     OrderExpiryCheckEvent["OrderExpiryCheckEvent&lt;br/&gt;&lt;small&gt;order:{orderId}&lt;/small&gt;"]
 *     PaymentCaptureEvent["PaymentCaptureEvent&lt;br/&gt;&lt;small&gt;order:{orderId}&lt;/small&gt;"]
 *   end
 *   OrderCreateEvent --&gt; OrderAcceptedEvent
 *   OrderCreateEvent --&gt; OrderRejectedEvent
 *   OrderAcceptedEvent --&gt; ReserveInventoryEvent
 *   OrderAcceptedEvent --&gt; OrderExpiryCheckEvent
 * </pre>
 */
public final class OrderEventsEventTypes {
    private OrderEventsEventTypes() {}

    /** The ecosystem (module) name. */
    public static final String NAME = "order-events";

    /** Mermaid flowchart of the event flow (concert::event.emits). */
    public static final String FLOW_MERMAID = "flowchart LR\n  subgraph inventory[\"domain inventory\"]\n    ReserveInventoryEvent[\"ReserveInventoryEvent<br/><small>sku:{sku} · non-blocking</small>\"]\n    RestockEvent[\"RestockEvent<br/><small>sku:{sku}</small>\"]\n  end\n  subgraph orders[\"domain orders\"]\n    OrderCreateEvent[\"OrderCreateEvent<br/><small>order:{orderId}, customer:{customerId}</small>\"]\n    OrderAcceptedEvent[\"OrderAcceptedEvent<br/><small>order:{orderId}</small>\"]\n    OrderRejectedEvent[\"OrderRejectedEvent<br/><small>order:{orderId}</small>\"]\n    OrderExpiryCheckEvent[\"OrderExpiryCheckEvent<br/><small>order:{orderId}</small>\"]\n    PaymentCaptureEvent[\"PaymentCaptureEvent<br/><small>order:{orderId}</small>\"]\n  end\n  OrderCreateEvent --> OrderAcceptedEvent\n  OrderCreateEvent --> OrderRejectedEvent\n  OrderAcceptedEvent --> ReserveInventoryEvent\n  OrderAcceptedEvent --> OrderExpiryCheckEvent\n";

    /** Mermaid class diagram of the ecosystem's model (all model files). */
    public static final String MODEL_MERMAID = mermaid(io.concert.eco.order_events.model.inventory.InventoryModel.MERMAID, io.concert.eco.order_events.model.orders.OrdersModel.MERMAID);

    /** The domains, in declaration order. */
    public static final List<String> DOMAINS = List.of("inventory", "orders");

    /** One catalog per domain. */
    public static final List<EventCatalog> CATALOGS = List.of(new InventoryEventCatalog(), new OrdersEventCatalog());

    /** Registers the catalogs (also discovered through ServiceLoader; registering twice is harmless). */
    public static void register() {
        CATALOGS.forEach(EventCatalogs::register);
    }

    /** The handlers of a domain: one instance of each of your handler classes. */
    public static HandlerRegistry handlers(String domain) {
        register();
        return switch (domain) {
            case "inventory" -> new HandlerRegistry("inventory")
                    .add(new ReserveInventoryHandler())
                    .add(new RestockHandler());
            case "orders" -> new HandlerRegistry("orders")
                    .add(new OrderCreateHandler())
                    .add(new OrderAcceptedHandler())
                    .add(new OrderRejectedHandler())
                    .add(new OrderExpiryCheckHandler())
                    .add(new PaymentCaptureHandler());
            default -> throw new IllegalArgumentException("unknown event domain " + domain + ", expected one of " + DOMAINS);
        };
    }

    /** The event type named {@code eventType}. */
    public static EventCatalog.EventType type(String eventType) {
        for (EventCatalog c : CATALOGS) {
            for (EventCatalog.EventType t : c.events()) {
                if (t.name().equals(eventType)) {
                    return t;
                }
            }
        }
        throw new IllegalArgumentException("unknown event type " + eventType + ", expected one of " + typeNames());
    }

    /** Whether {@code name} is one of the event types. */
    public static boolean isEventType(String name) {
        return typeNames().contains(name);
    }

    /** All event type names, in declaration order. */
    public static List<String> typeNames() {
        return CATALOGS.stream().flatMap(c -> c.events().stream()).map(EventCatalog.EventType::name).toList();
    }

    /** Every event type, in declaration order. */
    public static List<EventCatalog.EventType> types() {
        return CATALOGS.stream().flatMap(c -> c.events().stream()).toList();
    }

    /** The {@code concert::event.emits} of an event type. */
    public static List<String> emits(String eventType) {
        for (EventCatalog c : CATALOGS) {
            List<String> e = c.emits().get(eventType);
            if (e != null) {
                return e;
            }
        }
        return List.of();
    }

    /** Merges generated {@code classDiagram}s (one per model file) into one diagram. */
    static String mermaid(String... diagrams) {
        StringBuilder sb = new StringBuilder("classDiagram\n");
        for (String d : diagrams) {
            sb.append(d.substring(d.indexOf('\n') + 1));
        }
        return sb.toString();
    }
}
