// GENERATED by ./generate-concert-ecosystem from the Pure models -- do not edit: regenerated on every run.
package io.concert.eco.order_events;

import io.concert.model.runtime.LegendModel;

/**
 * Generates the Java classes of the ecosystem's Pure models ({@code src/main/pure}) at compile time:
 * {@code a::b::X} becomes {@code io.concert.eco.order_events.model.a.b.X}.
 */
@LegendModel(files = {"concert/concert.pure", "inventory.pure", "orders.pure"}, root = "inventory::ReserveInventoryEvent", javaPackage = "io.concert.eco.order_events.model")
public final class OrderEventsModels {
    private OrderEventsModels() {}

    /** The {@code files} of the annotation. */
    public static final String[] FILES = {"concert/concert.pure", "inventory.pure", "orders.pure"};
}
