// GENERATED by ./generate-concert-ecosystem from the Pure models -- do not edit: regenerated on every run.
package io.concert.eco.order_events;

import io.concert.sdk.events.EventCatalog;
import io.concert.sdk.events.OnError;
import java.util.List;
import java.util.Map;

/**
 * Event types of domain {@code orders} (task queue {@code ev-orders}), declared with {@code concert::event} in the
 * Pure models; discovered through the {@link EventCatalog} SPI (workers, event sender, trace UI).
 *
 * <pre>
 *   OrderCreateEvent  locks order:{orderId}, customer:{customerId}  onError BLOCKING  attempts 3  emits OrderAcceptedEvent, OrderRejectedEvent
 *   OrderAcceptedEvent  locks order:{orderId}  onError BLOCKING  attempts 3  emits ReserveInventoryEvent, OrderExpiryCheckEvent
 *   OrderRejectedEvent  locks order:{orderId}  onError BLOCKING  attempts 3
 *   OrderExpiryCheckEvent  locks order:{orderId}  onError BLOCKING  attempts 2
 *   PaymentCaptureEvent  locks order:{orderId}  onError BLOCKING  attempts 3
 * </pre>
 */
public final class OrdersEventCatalog implements EventCatalog {

    public static final String DOMAIN = "orders";

    /** {@code orders::OrderCreateEvent} (orders.pure:46:1). */
    public static final EventType ORDER_CREATE_EVENT = new EventType("OrderCreateEvent", DOMAIN,
            io.concert.eco.order_events.model.orders.OrderCreateEvent.class, List.of("order:{orderId}", "customer:{customerId}"), OnError.BLOCKING, 3);

    /** {@code orders::OrderAcceptedEvent} (orders.pure:61:1). */
    public static final EventType ORDER_ACCEPTED_EVENT = new EventType("OrderAcceptedEvent", DOMAIN,
            io.concert.eco.order_events.model.orders.OrderAcceptedEvent.class, List.of("order:{orderId}"), OnError.BLOCKING, 3);

    /** {@code orders::OrderRejectedEvent} (orders.pure:74:1). */
    public static final EventType ORDER_REJECTED_EVENT = new EventType("OrderRejectedEvent", DOMAIN,
            io.concert.eco.order_events.model.orders.OrderRejectedEvent.class, List.of("order:{orderId}"), OnError.BLOCKING, 3);

    /** {@code orders::OrderExpiryCheckEvent} (orders.pure:88:1). */
    public static final EventType ORDER_EXPIRY_CHECK_EVENT = new EventType("OrderExpiryCheckEvent", DOMAIN,
            io.concert.eco.order_events.model.orders.OrderExpiryCheckEvent.class, List.of("order:{orderId}"), OnError.BLOCKING, 2);

    /** {@code orders::PaymentCaptureEvent} (orders.pure:101:1). */
    public static final EventType PAYMENT_CAPTURE_EVENT = new EventType("PaymentCaptureEvent", DOMAIN,
            io.concert.eco.order_events.model.orders.PaymentCaptureEvent.class, List.of("order:{orderId}"), OnError.BLOCKING, 3);

    /** Keyed state {@code orders::Order}: rows {@code state:<key>}. */
    public static final StateType ORDER_STATE = new StateType("Order", io.concert.eco.order_events.model.orders.Order.class, "order:{orderId}");

    public static final List<EventType> EVENTS = List.of(ORDER_CREATE_EVENT, ORDER_ACCEPTED_EVENT, ORDER_REJECTED_EVENT, ORDER_EXPIRY_CHECK_EVENT, PAYMENT_CAPTURE_EVENT);

    public static final List<StateType> STATES = List.of(ORDER_STATE);

    /** {@code concert::event.emits} per event type. */
    public static final Map<String, List<String>> EMITS = Map.ofEntries(
            Map.entry("OrderCreateEvent", List.of("OrderAcceptedEvent", "OrderRejectedEvent")),
            Map.entry("OrderAcceptedEvent", List.of("ReserveInventoryEvent", "OrderExpiryCheckEvent")),
            Map.entry("OrderRejectedEvent", List.of()),
            Map.entry("OrderExpiryCheckEvent", List.of()),
            Map.entry("PaymentCaptureEvent", List.of()));

    @Override
    public String name() {
        return "order-events/orders";
    }

    @Override
    public List<EventType> events() {
        return EVENTS;
    }

    @Override
    public List<StateType> states() {
        return STATES;
    }

    @Override
    public Map<String, List<String>> emits() {
        return EMITS;
    }

    @Override
    public String flowMermaid() {
        return OrderEventsEventTypes.FLOW_MERMAID;
    }

    @Override
    public String modelMermaid() {
        return OrderEventsEventTypes.MODEL_MERMAID;
    }
}
