// GENERATED by ./generate-concert-ecosystem from the Pure models -- do not edit: regenerated on every run.
package io.concert.eco.order_events;

import io.concert.common.Env;
import io.concert.common.TemporalClients;
import io.concert.common.WorkerTuning;
import io.concert.sdk.EntitySnapshotPublisher;
import io.concert.sdk.events.EventWorkerBootstrap;
import io.concert.sink.SnapshotCodec;
import io.concert.store.StateStore;
import io.concert.store.Stores;
import io.temporal.worker.WorkerFactory;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Runs the event-style workers of ecosystem {@code order-events} in one process: one worker per domain (task
 * queue {@code ev-<domain>}) with its processor workflow and your handlers. Environment as for every worker
 * ({@code TEMPORAL_*}, {@code STORE_KIND}, {@code KAFKA_BOOTSTRAP}, ...); {@code ORDER_EVENTS_EVENT_DOMAINS} (comma separated)
 * optionally restricts the domains.
 */
public final class OrderEventsEventWorkerMain {
    private static final Logger log = LoggerFactory.getLogger(OrderEventsEventWorkerMain.class);

    private OrderEventsEventWorkerMain() {}

    public static void main(String[] args) throws InterruptedException {
        StateStore store = Stores.fromEnv();
        var client = TemporalClients.fromEnv();
        OrderEventsEventTypes.register();
        // Lifecycle rows (evt_*) and state documents (st_*) go to entity-snapshots like completed entities (no-op
        // when KAFKA_BOOTSTRAP is empty); the schemaHash header is the hash of the ecosystem's model diagram.
        String schemaHash = SnapshotCodec.schemaHash(OrderEventsEventTypes.MODEL_MERMAID);
        EntitySnapshotPublisher snapshots = EntitySnapshotPublisher.fromEnv(
                type -> type.startsWith("evt_") || type.startsWith("st_") ? schemaHash : null);
        String domains = Env.get("ORDER_EVENTS_EVENT_DOMAINS", String.join(",", OrderEventsEventTypes.DOMAINS));
        WorkerFactory factory = WorkerFactory.newInstance(client, WorkerTuning.factoryOptions());
        for (String domain : domains.split(",")) {
            if (domain.isBlank()) {
                continue;
            }
            EventWorkerBootstrap.register(factory, client, store, OrderEventsEventTypes.handlers(domain.trim()),
                    EventWorkerBootstrap.Options.defaults().withPublisher(snapshots));
            log.info("event worker up for ev-{}", domain.trim());
        }
        factory.start();
        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            factory.shutdown();
            store.close();
        }));
        Thread.currentThread().join();
    }
}
