// GENERATED by ./generate-concert-ecosystem from the Pure models -- do not edit: regenerated on every run.
package io.concert.eco.order_events;

import com.fasterxml.jackson.databind.JsonNode;
import io.concert.common.Env;
import io.concert.common.EventEnvelope;
import io.concert.common.Json;
import io.concert.model.runtime.ModelJson;
import io.concert.model.runtime.ModelObject;
import io.concert.orchestration.KinesisClients;
import io.concert.sdk.LockTemplates;
import io.concert.sdk.events.EventCatalog;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Duration;
import java.time.Instant;
import java.time.OffsetDateTime;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import software.amazon.awssdk.core.SdkBytes;
import software.amazon.awssdk.services.kinesis.KinesisClient;

/**
 * Sends events of ecosystem {@code order-events} to Kinesis ({@code INGEST_STREAM}, default
 * {@code concert-events}; {@code KINESIS_ENDPOINT}, e.g. {@code http://localhost:4566}), addressed and locked as
 * the Pure annotations declare: lock keys are rendered from the payload, the partition key is the first sorted
 * lock key. Payloads are checked against their model class before sending.
 *
 * <pre>
 * send &lt;EventType&gt; [payload.json | - | '{...json...}'] [--at ISO|+30s|+5m|+2h] [--id ID]   event style
 *      (no payload: $ECOSYSTEM_SAMPLES/events/&lt;EventType&gt;.json)
 * flow &lt;flow.json&gt; [--delay-ms 500]     {"events": [...]}: {style: event, eventType, payload, at?, id?}
 * list
 * </pre>
 */
public final class OrderEventsEvents {
    private OrderEventsEvents() {}

    public static void main(String[] args) throws Exception {
        try {
            run(args);
        } catch (IllegalArgumentException | java.io.UncheckedIOException e) {
            System.err.println("error: " + e.getMessage());
            System.exit(1);
        }
    }

    private static void run(String[] args) throws Exception {
        if (args.length == 0) {
            usage();
            System.exit(2);
        }
        switch (args[0]) {
            case "list" -> list();
            case "send" -> {
                if (args.length >= 2 && OrderEventsEventTypes.isEventType(args[1])) {
                    sendEvent(args);
                    return;
                }
                usage();
                System.exit(2);
            }
            case "flow" -> {
                if (args.length < 2) {
                    usage();
                    System.exit(2);
                }
                long delay = args.length > 3 && args[2].equals("--delay-ms") ? Long.parseLong(args[3]) : 500;
                flow(Path.of(args[1]), delay);
            }
            default -> {
                usage();
                System.exit(2);
            }
        }
    }

    private static void usage() {
        System.err.println("usage: "
                + "send <EventType> [payload.json | - | '{json}'] [--at ISO|+30s|+5m|+2h] [--id ID]\n       "
                + "flow <flow.json> [--delay-ms N]\n       list"
                + "\nevent types: " + OrderEventsEventTypes.typeNames());
    }

    private static void list() {
        for (String domain : OrderEventsEventTypes.DOMAINS) {
            System.out.println("event domain " + domain + "  (task queue ev-" + domain + ")");
            for (EventCatalog.EventType e : OrderEventsEventTypes.types()) {
                if (e.domain().equals(domain)) {
                    System.out.printf("  %-24s locks %s  onError %s  attempts %d  emits %s%n", e.name(),
                            e.lockTemplates().isEmpty() ? "[" + domain + ":{id}]" : e.lockTemplates(), e.onError(), e.maxAttempts(), OrderEventsEventTypes.emits(e.name()));
                }
            }
        }
    }

    private static String readPayload(String arg) throws IOException {
        if (arg.equals("-")) {
            return new String(System.in.readAllBytes(), StandardCharsets.UTF_8);
        }
        String t = arg.strip();
        return t.startsWith("{") || t.equals("null") ? t : Files.readString(Path.of(arg), StandardCharsets.UTF_8);
    }

    /** The payload bound to its model class and validated (multiplicities), then serialized back. */
    private static String checked(String payload, Class<?> type) {
        String json = payload == null || payload.isBlank() || payload.strip().equals("null") ? null : payload.strip();
        if (type != null && json != null) {
            Object bound = ModelJson.read(json, type);
            if (bound instanceof ModelObject mo && !mo.validationErrors().isEmpty()) {
                throw new IllegalArgumentException("invalid " + type.getSimpleName() + " payload: "
                        + String.join("; ", mo.validationErrors()));
            }
            json = ModelJson.write(bound);
        }
        return json;
    }

    private static JsonNode tree(String json) {
        try {
            return json == null ? null : Json.MAPPER.readTree(json);
        } catch (com.fasterxml.jackson.core.JsonProcessingException x) {
            throw new IllegalArgumentException("payload is not JSON: " + x.getOriginalMessage(), x);
        }
    }

    private static void sendEvent(String[] args) throws IOException {
        String type = args[1];
        String payload = null;
        long at = 0;
        String id = null;
        for (int i = 2; i < args.length; i++) {
            switch (args[i]) {
                case "--at" -> at = parseAt(value(args, ++i, "--at"));
                case "--id" -> id = value(args, ++i, "--id");
                default -> payload = readPayload(args[i]);
            }
        }
        if (payload == null) {
            payload = samplePayload(type);
        }
        EventEnvelope e = eventEnvelope(type, payload, at, id);
        try (KinesisClient kinesis = KinesisClients.fromEnv()) {
            publish(kinesis, e);
        }
    }

    private static String value(String[] args, int i, String option) {
        if (i >= args.length) {
            throw new IllegalArgumentException(option + " needs a value");
        }
        return args[i];
    }

    /** {@code $ECOSYSTEM_SAMPLES/events/<type>.json} (set by the send script), else {@code null}. */
    private static String samplePayload(String type) throws IOException {
        String dir = Env.get("ECOSYSTEM_SAMPLES", "");
        Path p = dir.isBlank() ? null : Path.of(dir, "events", type + ".json");
        return p != null && Files.isRegularFile(p) ? Files.readString(p, StandardCharsets.UTF_8) : null;
    }

    /** {@code +30s}, {@code +5m}, {@code +2h}, {@code +1d} from now, or an ISO-8601 instant / offset date-time. */
    public static long parseAt(String at) {
        String s = at.strip();
        if (s.startsWith("+") && s.length() > 2) {
            long n = Long.parseLong(s.substring(1, s.length() - 1));
            Duration d = switch (s.charAt(s.length() - 1)) {
                case 's' -> Duration.ofSeconds(n);
                case 'm' -> Duration.ofMinutes(n);
                case 'h' -> Duration.ofHours(n);
                case 'd' -> Duration.ofDays(n);
                default -> throw new IllegalArgumentException("bad --at " + at + ": use +30s, +5m, +2h, +1d or an ISO instant");
            };
            return System.currentTimeMillis() + d.toMillis();
        }
        try {
            return Instant.parse(s).toEpochMilli();
        } catch (DateTimeParseException notInstant) {
            try {
                return OffsetDateTime.parse(s).toInstant().toEpochMilli();
            } catch (DateTimeParseException e) {
                throw new IllegalArgumentException("bad --at " + at + ": use +30s, +5m, +2h, +1d or an ISO instant", e);
            }
        }
    }

    /**
     * An event-style event, validated: the type exists, the payload binds to its class and satisfies its
     * multiplicities, and every lock key renders from it.
     *
     * @param atMillis apply no earlier than this (SCHEDULED until then); 0 = now
     * @param eventId {@code null}: {@code <EventType>-<random>}
     */
    public static EventEnvelope eventEnvelope(String eventType, String payload, long atMillis, String eventId) {
            EventCatalog.EventType type = OrderEventsEventTypes.type(eventType);
        String json = checked(payload, type.payloadType());
        String id = eventId != null ? eventId : eventType + "-" + UUID.randomUUID().toString().replace("-", "").substring(0, 12);
        List<String> locks = type.lockTemplates().isEmpty() ? List.of() : LockTemplates.render(type.lockTemplates(), id, tree(json));
        EventEnvelope e = EventEnvelope.event(id, type.domain(), type.name(), locks, json, System.currentTimeMillis());
        return atMillis > 0 ? e.withScheduledAt(atMillis) : e;
    }

    private static void publish(KinesisClient kinesis, EventEnvelope e) {
        String stream = Env.get("INGEST_STREAM", "concert-events");
        String partitionKey = e.effectiveLockKeys().getFirst();
        kinesis.putRecord(b -> b.streamName(stream).partitionKey(partitionKey).data(SdkBytes.fromUtf8String(Json.write(e))));
        if (e.isEventStyle()) {
            System.out.printf("sent %s event %s (domain %s)  locks %s  (partition key %s)%s%n", e.eventId(), e.eventType(), e.domain(),
                    e.effectiveLockKeys(), partitionKey, e.scheduledAtMillis() > 0 ? "  scheduled at "
                            + java.time.Instant.ofEpochMilli(e.scheduledAtMillis()) : "");
        } else {
            System.out.printf("sent %s %s:%s %s  locks %s  (partition key %s)%n", e.eventId(), e.smType(), e.instanceKey(),
                    e.eventType(), e.effectiveLockKeys(), partitionKey);
        }
    }

    private static void flow(Path file, long delayMs) throws IOException, InterruptedException {
        JsonNode flow = Json.MAPPER.readTree(Files.readString(file, StandardCharsets.UTF_8));
        List<EventEnvelope> events = new ArrayList<>();
        for (JsonNode e : flow.path("events")) {
            JsonNode p = e.get("payload");
            String payload = p == null || p.isNull() ? null : Json.write(p);
            if (e.path("style").asText("").equals("event")) {
                long at = e.hasNonNull("at") ? parseAt(e.get("at").asText()) : 0;
                events.add(eventEnvelope(e.path("eventType").asText(), payload, at,
                        e.hasNonNull("id") ? e.get("id").asText() : null));
                continue;
            }
            throw new IllegalArgumentException(file + ": flow event without \"style\": \"event\": " + e);
        }
        System.out.printf("flow %s: %d events%n", flow.path("name").asText(file.getFileName().toString()), events.size());
        try (KinesisClient kinesis = KinesisClients.fromEnv()) {
            for (int i = 0; i < events.size(); i++) {
                if (i > 0 && delayMs > 0) {
                    Thread.sleep(delayMs); // events of one entity in order, even across shards
                }
                publish(kinesis, events.get(i));
            }
        }
    }
}
