package io.concert.ecosystem;

import io.concert.model.codegen.JavaNames;
import io.concert.model.pure.ClassDef;
import io.concert.model.pure.PropertyDef;
import io.concert.model.pure.ResolvedModel;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.TreeSet;

/** The Java sources of a generated ecosystem module. */
final class JavaSources {

    static final String GENERATED_HEADER = "// GENERATED by ./generate-concert-ecosystem from the Pure models -- do not edit: regenerated on every run.\n";

    private final Ecosystem eco;
    private final ResolvedModel model;

    JavaSources(Ecosystem eco) {
        this.eco = eco;
        this.model = eco.model();
    }

    String pkg() {
        return eco.javaPackage();
    }

    static String specClass(MachineDecl m) {
        return Ecosystem.pascal(m.smType()) + "Spec";
    }

    static String machineClass(MachineDecl m) {
        return Ecosystem.pascal(m.smType()) + "Machine";
    }

    String machinesClass() {
        return eco.pascalName() + "Machines";
    }

    String modelsClass() {
        return eco.pascalName() + "Models";
    }

    String workerMainClass() {
        return eco.pascalName() + "WorkerMain";
    }

    String eventsClass() {
        return eco.pascalName() + "Events";
    }

    String testClass() {
        return eco.pascalName() + "GeneratedTest";
    }

    private static String q(String s) {
        StringBuilder sb = new StringBuilder("\"");
        for (char c : s.toCharArray()) {
            switch (c) {
                case '"' -> sb.append("\\\"");
                case '\\' -> sb.append("\\\\");
                case '\n' -> sb.append("\\n");
                default -> sb.append(c);
            }
        }
        return sb.append('"').toString();
    }

    private static String html(String s) {
        return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("*/", "*&#47;").replace("@", "&#64;");
    }

    /** Transition table as Javadoc {@code <pre>} lines. */
    private static String table(MachineDecl m) {
        StringBuilder sb = new StringBuilder();
        for (MachineDecl.Transition t : m.transitions()) {
            sb.append(" *   ").append(html(t.from() + " -" + t.eventType() + "-> " + t.to()));
            if (t.payloadClass() != null) {
                sb.append(" : ").append(html(t.payloadClass()));
            }
            sb.append('\n');
        }
        return sb.toString();
    }

    // ---- <Name>Models ----

    String models() {
        StringBuilder files = new StringBuilder();
        List<String> lf = eco.legendFiles();
        for (int i = 0; i < lf.size(); i++) {
            files.append(i == 0 ? "" : ", ").append(q(lf.get(i)));
        }
        return GENERATED_HEADER + "package " + pkg() + ";\n\n"
                + "import io.concert.model.runtime.LegendModel;\n\n"
                + "/**\n"
                + " * Generates the Java classes of the ecosystem's Pure models ({@code src/main/pure}) at compile time:\n"
                + " * {@code a::b::X} becomes {@code " + eco.modelPackage() + ".a.b.X}.\n"
                + " */\n"
                + "@LegendModel(files = {" + files + "}, root = " + q(eco.machines().getFirst().root().qualifiedName())
                + ", javaPackage = " + q(eco.modelPackage()) + ")\n"
                + "public final class " + modelsClass() + " {\n"
                + "    private " + modelsClass() + "() {}\n\n"
                + "    /** The {@code files} of the annotation. */\n"
                + "    public static final String[] FILES = {" + files + "};\n"
                + "}\n";
    }

    // ---- <Root>Spec ----

    String spec(MachineDecl m) {
        StringBuilder sb = new StringBuilder(GENERATED_HEADER);
        sb.append("package ").append(pkg()).append(";\n\n");
        sb.append("import com.fasterxml.jackson.databind.JsonNode;\n");
        sb.append("import io.concert.sdk.LockTemplates;\n");
        sb.append("import io.concert.sdk.StateMachineSpec;\n");
        sb.append("import java.util.List;\nimport java.util.Map;\n\n");
        sb.append("/**\n * State machine {@code ").append(m.smType()).append("} declared on {@code ").append(html(m.root().qualifiedName()))
                .append("} (").append(html(m.root().location().toString())).append(").\n *\n * <pre>\n");
        sb.append(" *   initial ").append(m.initial()).append("; terminal ").append(html(String.join(", ", m.terminal()))).append('\n');
        sb.append(table(m));
        sb.append(" * </pre>\n */\n");
        String cls = specClass(m);
        sb.append("public final class ").append(cls).append(" {\n    private ").append(cls).append("() {}\n\n");
        sb.append("    /** smType: task queue {@code sm-").append(m.smType()).append("}, workflow ids {@code ").append(m.smType())
                .append(":<key>}. */\n");
        sb.append("    public static final String TYPE = ").append(q(m.smType())).append(";\n\n");
        sb.append("    /** Qualified Pure name of the root (data) class. */\n");
        sb.append("    public static final String ROOT_CLASS = ").append(q(m.root().qualifiedName())).append(";\n\n");
        sb.append("    /** Property set to the instance key, or {@code null}. */\n");
        sb.append("    public static final String ID_PROPERTY = ").append(m.idProperty() == null ? "null" : q(m.idProperty())).append(";\n\n");
        sb.append("    /** Enum property kept equal to the state, or {@code null}. */\n");
        sb.append("    public static final String STATUS_PROPERTY = ").append(m.statusProperty() == null ? "null" : q(m.statusProperty()))
                .append(";\n\n");
        sb.append("    public static final StateMachineSpec SPEC = StateMachineSpec.startingAt(").append(q(m.initial())).append(")\n");
        for (MachineDecl.Transition t : m.transitions()) {
            sb.append("            .on(").append(q(t.from())).append(", ").append(q(t.eventType())).append(", ").append(q(t.to()));
            if (t.payloadClass() != null) {
                sb.append(", ").append(eco.javaType(t.payloadClass())).append(".class");
            }
            sb.append(")\n");
        }
        if (m.terminalDeclared()) {
            sb.append("            .terminal(");
            sb.append(String.join(", ", m.terminal().stream().map(JavaSources::q).toList()));
            sb.append(")\n");
        }
        sb.append("            .build();\n\n");
        sb.append("    /**\n     * Lock key templates per event type, beyond the target entity key (always implied): {@code {id}} is\n"
                + "     * the instance key, {@code {field}} a payload field.\n     */\n");
        sb.append("    public static final Map<String, List<String>> LOCKS = Map.ofEntries(\n");
        List<Map.Entry<String, List<String>>> entries = new ArrayList<>(m.locks().entrySet());
        for (int i = 0; i < entries.size(); i++) {
            Map.Entry<String, List<String>> e = entries.get(i);
            sb.append("            Map.entry(").append(q(e.getKey())).append(", List.of(")
                    .append(String.join(", ", e.getValue().stream().map(JavaSources::q).toList())).append("))")
                    .append(i == entries.size() - 1 ? ");\n\n" : ",\n");
        }
        sb.append("    /** The lock keys of an event, rendered from its payload. */\n");
        sb.append("    public static List<String> lockKeys(String eventType, String instanceKey, JsonNode payload) {\n");
        sb.append("        List<String> templates = LOCKS.get(eventType);\n");
        sb.append("        if (templates == null) {\n");
        sb.append("            throw new IllegalArgumentException(TYPE + \" has no event \" + eventType + \", expected one of \" + LOCKS.keySet());\n");
        sb.append("        }\n");
        sb.append("        return LockTemplates.render(templates, instanceKey, payload);\n    }\n");
        sb.append("}\n");
        return sb.toString();
    }

    // ---- <Root>Machine (user-owned stub) ----

    String stub(MachineDecl m) {
        String root = eco.javaType(m.root().qualifiedName());
        String rootSimple = Ecosystem.simpleName(root);
        String var = Character.toLowerCase(rootSimple.charAt(0)) + rootSimple.substring(1);
        if (var.equals("event") || var.equals("payload") || var.equals("from") || var.equals("to")) {
            var = var + "Data";
        }
        TreeSet<String> imports = new TreeSet<>(List.of("io.concert.common.EventEnvelope", "io.concert.sdk.ModelStateMachine",
                "io.concert.sdk.StateMachineSpec", root));
        Map<String, String> names = new LinkedHashMap<>(); // qualified Java -> name used in code
        names.put(root, rootSimple);
        java.util.function.Function<String, String> use = qualified -> names.computeIfAbsent(qualified, k -> {
            String simple = Ecosystem.simpleName(k);
            if (names.containsValue(simple)) {
                return k;
            }
            imports.add(k);
            return simple;
        });
        String statusEnum = m.statusEnum() == null ? null : use.apply(eco.javaType(m.statusEnum()));
        StringBuilder body = new StringBuilder();
        body.append("    @Override\n    protected StateMachineSpec spec() {\n        return ").append(specClass(m)).append(".SPEC;\n    }\n\n");
        body.append("    @Override\n    protected Class<").append(rootSimple).append("> dataType() {\n        return ").append(rootSimple)
                .append(".class;\n    }\n\n");
        body.append("    @Override\n    protected ").append(rootSimple).append(" initialData(String instanceKey) {\n        return new ")
                .append(rootSimple).append("()");
        if (m.idProperty() != null) {
            body.append('.').append(JavaNames.setter(m.idProperty())).append("(instanceKey)");
        }
        if (statusEnum != null) {
            body.append('.').append(JavaNames.setter(m.statusProperty())).append('(').append(statusEnum).append('.')
                    .append(JavaNames.identifier(m.initial())).append(')');
        }
        body.append(";\n    }\n\n");
        body.append("    @Override\n    protected void onTransition(String from, String to, ").append(rootSimple).append(' ').append(var)
                .append(", Object payload, EventEnvelope event) {\n");
        if (statusEnum != null) {
            body.append("        ").append(var).append('.').append(JavaNames.setter(m.statusProperty())).append('(').append(statusEnum)
                    .append(".valueOf(to));\n");
        }
        body.append("        switch (payload) {\n");
        for (String payload : m.payloadClasses()) {
            String name = use.apply(eco.javaType(payload));
            body.append("            case ").append(name).append(" cmd -> {\n");
            for (MachineDecl.Transition t : m.transitions()) {
                if (payload.equals(t.payloadClass())) {
                    body.append("                // TODO ").append(t.from()).append(" -").append(t.eventType()).append("-> ").append(t.to())
                            .append(": apply the command to the ").append(var).append(", call activities, or reject(\"...\")\n");
                }
            }
            for (String copy : copies(m, payload, var)) {
                body.append("                ").append(copy).append('\n');
            }
            body.append("            }\n");
        }
        List<MachineDecl.Transition> untyped = m.transitions().stream().filter(t -> t.payloadClass() == null).toList();
        if (!untyped.isEmpty()) {
            body.append("            case null -> {\n");
            for (MachineDecl.Transition t : untyped) {
                body.append("                // TODO ").append(t.from()).append(" -").append(t.eventType()).append("-> ").append(t.to())
                        .append(" (untyped event; see event.eventType())\n");
            }
            body.append("            }\n");
            body.append("            default -> reject(\"unexpected payload for \" + event.eventType() + \": \" + payload.getClass().getSimpleName());\n");
        } else {
            body.append("            case null, default -> reject(\"unexpected payload for \" + event.eventType() + \": \" + payload);\n");
        }
        body.append("        }\n    }\n}\n");

        StringBuilder sb = new StringBuilder();
        sb.append("// Yours to edit: generated once by ./generate-concert-ecosystem and never overwritten (--force\n"
                + "// regenerates it after backing it up as ").append(machineClass(m)).append(".java.bak-<timestamp>).\n");
        sb.append("package ").append(pkg()).append(";\n\n");
        imports.forEach(i -> sb.append("import ").append(i).append(";\n"));
        sb.append("\n/**\n * The {@code ").append(m.smType()).append("} state machine: entity data {@code ").append(html(m.root().qualifiedName()))
                .append("}, transitions\n * from {@link ").append(specClass(m)).append("} (regenerated from the Pure annotations):\n *\n * <pre>\n")
                .append(table(m)).append(" * </pre>\n *\n")
                .append(" * <p>{@code onTransition} mutates the data in place; reject an event with {@code reject(\"reason\")}. Take time\n"
                        + " * from {@code Workflow.currentTimeMillis()} (workflow code must be deterministic).\n */\n");
        sb.append("public class ").append(machineClass(m)).append(" extends ModelStateMachine<").append(rootSimple).append("> {\n\n");
        sb.append(body);
        return sb.toString();
    }

    /**
     * Starting-point code copying payload fields that have the same name, type and to-one multiplicity on
     * the root (except the id and status properties).
     */
    private List<String> copies(MachineDecl m, String payloadClass, String var) {
        ClassDef payload = model.findClass(payloadClass).orElseThrow();
        List<String> out = new ArrayList<>();
        for (PropertyDef p : model.allProperties(payload)) {
            if (!p.multiplicity().isToOne() || p.name().equals(m.idProperty()) || p.name().equals(m.statusProperty())) {
                continue;
            }
            Optional<PropertyDef> r = model.allProperties(m.root()).stream().filter(x -> x.name().equals(p.name())).findFirst();
            if (r.isPresent() && r.get().type().equals(p.type()) && r.get().multiplicity().isToOne()) {
                String get = "cmd." + JavaNames.getter(p.name()) + "()";
                out.add("if (" + get + " != null) {\n                    " + var + "." + JavaNames.setter(p.name()) + "(" + get
                        + ");\n                }");
            }
        }
        if (!out.isEmpty()) {
            out.addFirst("// generated starting point: copy the fields the command shares with the " + var);
        }
        return out;
    }

    // ---- <Name>Machines ----

    String machines() {
        StringBuilder sb = new StringBuilder(GENERATED_HEADER);
        sb.append("package ").append(pkg()).append(";\n\n");
        sb.append("import io.concert.sdk.MachineCatalog;\nimport io.concert.sdk.StateMachineRegistry;\nimport java.util.LinkedHashMap;\n"
                + "import java.util.List;\nimport java.util.Map;\n\n");
        sb.append("/**\n * The machines of ecosystem {@code ").append(eco.name()).append("} by smType: their specs and the model's class diagram\n"
                + " * (for the worker, the event sender and, through the {@link MachineCatalog} SPI, the trace UI).\n */\n");
        String cls = machinesClass();
        sb.append("public final class ").append(cls).append(" implements MachineCatalog {\n\n");
        sb.append("    /** Mermaid class diagram of the ecosystem's model (all model files). */\n");
        sb.append("    public static final String MODEL_MERMAID = mermaid(");
        List<String> registries = eco.modelRegistryClasses();
        sb.append(String.join(", ", registries.stream().map(r -> r + ".MERMAID").toList())).append(");\n\n");
        sb.append("    /** In declaration order. */\n");
        sb.append("    public static final Map<String, Machine> ALL = index(\n");
        for (int i = 0; i < eco.machines().size(); i++) {
            MachineDecl m = eco.machines().get(i);
            sb.append("            new Machine(").append(specClass(m)).append(".TYPE, ").append(machineClass(m)).append(".class, ")
                    .append(specClass(m)).append(".SPEC, MODEL_MERMAID)").append(i == eco.machines().size() - 1 ? ");\n\n" : ",\n");
        }
        sb.append("    /** Lock key templates per smType and event type. */\n");
        sb.append("    public static final Map<String, Map<String, List<String>>> LOCKS = Map.ofEntries(\n");
        for (int i = 0; i < eco.machines().size(); i++) {
            MachineDecl m = eco.machines().get(i);
            sb.append("            Map.entry(").append(specClass(m)).append(".TYPE, ").append(specClass(m)).append(".LOCKS)")
                    .append(i == eco.machines().size() - 1 ? ");\n\n" : ",\n");
        }
        sb.append("""
                    private static Map<String, Machine> index(Machine... machines) {
                        Map<String, Machine> m = new LinkedHashMap<>();
                        for (Machine x : machines) {
                            m.put(x.smType(), x);
                        }
                        return java.util.Collections.unmodifiableMap(m);
                    }

                    /** Merges generated {@code classDiagram}s (one per model file) into one diagram. */
                    static String mermaid(String... diagrams) {
                        StringBuilder sb = new StringBuilder("classDiagram\\n");
                        for (String d : diagrams) {
                            sb.append(d.substring(d.indexOf('\\n') + 1));
                        }
                        return sb.toString();
                    }

                    /** Registers the specs in {@link StateMachineRegistry}. */
                    public static void registerSpecs() {
                        ALL.forEach((type, m) -> StateMachineRegistry.register(type, m.spec()));
                    }

                    public static Machine get(String smType) {
                        Machine m = ALL.get(smType);
                        if (m == null) {
                            throw new IllegalArgumentException("unknown smType " + smType + ", expected one of " + ALL.keySet());
                        }
                        return m;
                    }

                    @Override
                    public String name() {
                        return NAME;
                    }

                    @Override
                    public List<Machine> machines() {
                        return List.copyOf(ALL.values());
                    }

                """);
        sb.append("    /** The ecosystem (module) name. */\n    public static final String NAME = ").append(q(eco.name())).append(";\n}\n");
        return sb.toString();
    }

    // ---- <Name>WorkerMain ----

    String workerMain() {
        String cls = workerMainClass();
        String m = machinesClass();
        String env = eco.name().toUpperCase(java.util.Locale.ROOT).replace('-', '_') + "_SM_TYPES";
        return GENERATED_HEADER + "package " + pkg() + ";\n\n"
                + """
                import io.concert.common.Env;
                import io.concert.common.TemporalClients;
                import io.concert.sdk.EntitySnapshotPublisher;
                import io.concert.sdk.MachineCatalog;
                import io.concert.sdk.WorkerBootstrap;
                import io.concert.sink.SnapshotCodec;
                import io.concert.store.StateStore;
                import io.concert.store.Stores;
                import io.temporal.worker.WorkerFactory;
                import java.util.ArrayList;
                import java.util.List;
                import org.slf4j.Logger;
                import org.slf4j.LoggerFactory;

                """
                + "/**\n * Runs the workers of every machine of ecosystem {@code " + eco.name() + "} in one process (task queues\n"
                + " * {@code sm-<smType>}). Environment as for every worker ({@code TEMPORAL_*}, {@code STORE_KIND},\n"
                + " * {@code KAFKA_BOOTSTRAP}, ...); {@code " + env + "} (comma separated) optionally restricts the types.\n */\n"
                + "public final class " + cls + " {\n"
                + "    private static final Logger log = LoggerFactory.getLogger(" + cls + ".class);\n\n"
                + "    private " + cls + "() {}\n\n"
                + "    public static void main(String[] args) throws InterruptedException {\n"
                + "        StateStore store = Stores.fromEnv();\n"
                + "        var client = TemporalClients.fromEnv();\n"
                + "        " + m + ".registerSpecs();\n"
                + "        // One Kafka producer for all types (no-op when KAFKA_BOOTSTRAP is empty); the schemaHash header is\n"
                + "        // the hash of the ecosystem's model diagram.\n"
                + "        String schemaHash = SnapshotCodec.schemaHash(" + m + ".MODEL_MERMAID);\n"
                + "        EntitySnapshotPublisher snapshots = EntitySnapshotPublisher.fromEnv(\n"
                + "                type -> " + m + ".ALL.containsKey(type) ? schemaHash : null);\n"
                + "        String types = Env.get(\"" + env + "\", String.join(\",\", " + m + ".ALL.keySet()));\n"
                + "        List<WorkerFactory> factories = new ArrayList<>();\n"
                + "        for (String type : types.split(\",\")) {\n"
                + "            MachineCatalog.Machine machine = " + m + ".get(type.trim());\n"
                + "            factories.add(WorkerBootstrap.start(client, store, machine.smType(), machine.impl(), snapshots));\n"
                + "            log.info(\"worker up for sm-{}\", machine.smType());\n"
                + "        }\n"
                + "        Runtime.getRuntime().addShutdownHook(new Thread(() -> {\n"
                + "            factories.forEach(WorkerFactory::shutdown);\n"
                + "            store.close();\n"
                + "        }));\n"
                + "        Thread.currentThread().join();\n"
                + "    }\n"
                + "}\n";
    }

    // ---- <Name>Events ----

    String events() {
        String cls = eventsClass();
        String m = machinesClass();
        return GENERATED_HEADER + "package " + pkg() + ";\n\n"
                + """
                import com.fasterxml.jackson.databind.JsonNode;
                import io.concert.common.Env;
                import io.concert.common.EventEnvelope;
                import io.concert.common.Json;
                import io.concert.model.runtime.ModelJson;
                import io.concert.model.runtime.ModelObject;
                import io.concert.orchestration.KinesisClients;
                import io.concert.sdk.LockTemplates;
                import io.concert.sdk.MachineCatalog;
                import io.concert.sdk.StateMachineSpec;
                import java.io.IOException;
                import java.nio.charset.StandardCharsets;
                import java.nio.file.Files;
                import java.nio.file.Path;
                import java.util.ArrayList;
                import java.util.List;
                import java.util.Map;
                import java.util.UUID;
                import software.amazon.awssdk.core.SdkBytes;
                import software.amazon.awssdk.services.kinesis.KinesisClient;

                """
                + "/**\n * Sends events of ecosystem {@code " + eco.name() + "} to Kinesis ({@code INGEST_STREAM}, default\n"
                + " * {@code concert-events}; {@code KINESIS_ENDPOINT}, e.g. {@code http://localhost:4566}), addressed and locked as\n"
                + " * the Pure annotations declare: lock keys are rendered from the payload ({@code <Root>Spec.LOCKS}), the partition\n"
                + " * key is the first sorted lock key. Payloads are checked against their model class before sending.\n *\n"
                + " * <pre>\n"
                + " * send &lt;smType&gt; &lt;eventType&gt; &lt;instanceKey&gt; [payload.json | - | '{...json...}']\n"
                + " * flow &lt;flow.json&gt; [--delay-ms 500]     {\"events\": [{smType, instanceKey, eventType, payload}, ...]}\n"
                + " * list\n"
                + " * </pre>\n */\n"
                + "public final class " + cls + " {\n"
                + "    private " + cls + "() {}\n\n"
                + "    public static void main(String[] args) throws Exception {\n"
                + "        try {\n"
                + "            run(args);\n"
                + "        } catch (IllegalArgumentException | java.io.UncheckedIOException e) {\n"
                + "            System.err.println(\"error: \" + e.getMessage());\n"
                + "            System.exit(1);\n"
                + "        }\n"
                + "    }\n\n"
                + "    private static void run(String[] args) throws Exception {\n"
                + "        if (args.length == 0) {\n"
                + "            usage();\n"
                + "            System.exit(2);\n"
                + "        }\n"
                + "        switch (args[0]) {\n"
                + "            case \"list\" -> list();\n"
                + "            case \"send\" -> {\n"
                + "                if (args.length < 4) {\n"
                + "                    usage();\n"
                + "                    System.exit(2);\n"
                + "                }\n"
                + "                String payload = args.length > 4 ? readPayload(args[4]) : null;\n"
                + "                EventEnvelope e = envelope(args[1], args[2], args[3], payload);\n"
                + "                try (KinesisClient kinesis = KinesisClients.fromEnv()) {\n"
                + "                    publish(kinesis, e);\n"
                + "                }\n"
                + "            }\n"
                + "            case \"flow\" -> {\n"
                + "                if (args.length < 2) {\n"
                + "                    usage();\n"
                + "                    System.exit(2);\n"
                + "                }\n"
                + "                long delay = args.length > 3 && args[2].equals(\"--delay-ms\") ? Long.parseLong(args[3]) : 500;\n"
                + "                flow(Path.of(args[1]), delay);\n"
                + "            }\n"
                + "            default -> {\n"
                + "                usage();\n"
                + "                System.exit(2);\n"
                + "            }\n"
                + "        }\n"
                + "    }\n\n"
                + "    private static void usage() {\n"
                + "        System.err.println(\"usage: send <smType> <eventType> <instanceKey> [payload.json | - | '{json}']\\n\"\n"
                + "                + \"       flow <flow.json> [--delay-ms N]\\n       list\\nsmTypes: \" + " + m + ".ALL.keySet());\n"
                + "    }\n\n"
                + "    private static void list() {\n"
                + "        " + m + ".ALL.forEach((type, machine) -> {\n"
                + "            System.out.println(type + \"  (initial \" + machine.spec().initialState() + \", terminal \" + machine.spec().terminalStates() + \")\");\n"
                + "            for (StateMachineSpec.Edge e : machine.spec().edges()) {\n"
                + "                System.out.printf(\"  %-14s %s -> %s  payload %s  locks %s%n\", e.eventType(), e.from(), e.to(),\n"
                + "                        e.payloadType() == null ? \"-\" : e.payloadType().getSimpleName(), " + m + ".LOCKS.get(type).get(e.eventType()));\n"
                + "            }\n"
                + "        });\n"
                + "    }\n\n"
                + "    private static String readPayload(String arg) throws IOException {\n"
                + "        if (arg.equals(\"-\")) {\n"
                + "            return new String(System.in.readAllBytes(), StandardCharsets.UTF_8);\n"
                + "        }\n"
                + "        String t = arg.strip();\n"
                + "        return t.startsWith(\"{\") || t.equals(\"null\") ? t : Files.readString(Path.of(arg), StandardCharsets.UTF_8);\n"
                + "    }\n\n"
                + "    /**\n"
                + "     * The event, validated: the smType and event type exist, the payload binds to the event's payload class and\n"
                + "     * satisfies its multiplicities, and every lock key renders.\n"
                + "     */\n"
                + "    public static EventEnvelope envelope(String smType, String eventType, String instanceKey, String payload) {\n"
                + "        MachineCatalog.Machine machine = " + m + ".get(smType);\n"
                + "        StateMachineSpec.Edge edge = machine.spec().edges().stream().filter(x -> x.eventType().equals(eventType)).findFirst()\n"
                + "                .orElseThrow(() -> new IllegalArgumentException(smType + \" has no event \" + eventType + \"; events: \"\n"
                + "                        + machine.spec().edges().stream().map(StateMachineSpec.Edge::eventType).distinct().toList()));\n"
                + "        String json = payload == null || payload.isBlank() || payload.strip().equals(\"null\") ? null : payload.strip();\n"
                + "        if (edge.payloadType() != null && json != null) {\n"
                + "            Object bound = ModelJson.read(json, edge.payloadType());\n"
                + "            if (bound instanceof ModelObject mo && !mo.validationErrors().isEmpty()) {\n"
                + "                throw new IllegalArgumentException(\"invalid \" + edge.payloadType().getSimpleName() + \" payload: \"\n"
                + "                        + String.join(\"; \", mo.validationErrors()));\n"
                + "            }\n"
                + "            json = ModelJson.write(bound);\n"
                + "        }\n"
                + "        JsonNode tree;\n"
                + "        try {\n"
                + "            tree = json == null ? null : Json.MAPPER.readTree(json);\n"
                + "        } catch (com.fasterxml.jackson.core.JsonProcessingException x) {\n"
                + "            throw new IllegalArgumentException(\"payload is not JSON: \" + x.getOriginalMessage(), x);\n"
                + "        }\n"
                + "        List<String> locks = LockTemplates.render(" + m + ".LOCKS.get(smType).get(eventType), instanceKey, tree);\n"
                + "        return new EventEnvelope(smType + \"-\" + eventType + \"-\" + UUID.randomUUID(), smType, instanceKey, eventType, locks, json,\n"
                + "                System.currentTimeMillis(), 0);\n"
                + "    }\n\n"
                + "    private static void publish(KinesisClient kinesis, EventEnvelope e) {\n"
                + "        String stream = Env.get(\"INGEST_STREAM\", \"concert-events\");\n"
                + "        String partitionKey = e.effectiveLockKeys().getFirst();\n"
                + "        kinesis.putRecord(b -> b.streamName(stream).partitionKey(partitionKey).data(SdkBytes.fromUtf8String(Json.write(e))));\n"
                + "        System.out.printf(\"sent %s %s:%s %s  locks %s  (partition key %s)%n\", e.eventId(), e.smType(), e.instanceKey(), e.eventType(),\n"
                + "                e.effectiveLockKeys(), partitionKey);\n"
                + "    }\n\n"
                + "    private static void flow(Path file, long delayMs) throws IOException, InterruptedException {\n"
                + "        JsonNode flow = Json.MAPPER.readTree(Files.readString(file, StandardCharsets.UTF_8));\n"
                + "        List<EventEnvelope> events = new ArrayList<>();\n"
                + "        for (JsonNode e : flow.path(\"events\")) {\n"
                + "            JsonNode p = e.get(\"payload\");\n"
                + "            events.add(envelope(e.path(\"smType\").asText(), e.path(\"eventType\").asText(), e.path(\"instanceKey\").asText(),\n"
                + "                    p == null || p.isNull() ? null : Json.write(p)));\n"
                + "        }\n"
                + "        System.out.printf(\"flow %s: %d events%n\", flow.path(\"name\").asText(file.getFileName().toString()), events.size());\n"
                + "        try (KinesisClient kinesis = KinesisClients.fromEnv()) {\n"
                + "            for (int i = 0; i < events.size(); i++) {\n"
                + "                if (i > 0 && delayMs > 0) {\n"
                + "                    Thread.sleep(delayMs); // events of one entity in order, even across shards\n"
                + "                }\n"
                + "                publish(kinesis, events.get(i));\n"
                + "            }\n"
                + "        }\n"
                + "    }\n\n"
                + "    /** smType to machine, for tests and tools. */\n"
                + "    public static Map<String, MachineCatalog.Machine> machines() {\n"
                + "        return " + m + ".ALL;\n"
                + "    }\n"
                + "}\n";
    }

    // ---- generated test ----

    String test() {
        String cls = testClass();
        String m = machinesClass();
        return GENERATED_HEADER + "package " + pkg() + ";\n\n"
                + """
                import static org.junit.jupiter.api.Assertions.assertEquals;
                import static org.junit.jupiter.api.Assertions.assertTrue;

                import com.fasterxml.jackson.databind.JsonNode;
                import io.concert.common.EventEnvelope;
                import io.concert.common.Json;
                import io.concert.common.TaskQueues;
                import io.concert.common.WorkflowIds;
                import io.concert.common.api.EntityInit;
                import io.concert.common.api.EntityWorkflow;
                import io.concert.common.api.TransitionResult;
                import io.concert.model.runtime.ModelJson;
                import io.concert.model.runtime.ModelObject;
                import io.concert.sdk.EntityPersistenceActivitiesImpl;
                import io.concert.sdk.EntitySnapshotPublisher;
                import io.concert.sdk.StateMachineSpec;
                import io.concert.sink.EntitySnapshot;
                import io.concert.store.InMemoryStateStore;
                import io.temporal.api.enums.v1.WorkflowIdConflictPolicy;
                import io.temporal.client.UpdateOptions;
                import io.temporal.client.WithStartWorkflowOperation;
                import io.temporal.client.WorkflowClient;
                import io.temporal.client.WorkflowOptions;
                import io.temporal.client.WorkflowUpdateStage;
                import io.temporal.testing.TestEnvironmentOptions;
                import io.temporal.testing.TestWorkflowEnvironment;
                import io.temporal.worker.Worker;
                import java.io.IOException;
                import java.nio.file.Files;
                import java.nio.file.Path;
                import java.util.List;
                import java.util.concurrent.CopyOnWriteArrayList;
                import java.util.stream.Stream;
                import org.junit.jupiter.api.Test;

                """
                + "/** Checks the generated samples and runs every happy-path flow through the real machines (your stubs). */\n"
                + "class " + cls + " {\n\n"
                + "    private static final Path SAMPLES = Path.of(System.getProperty(\"ecosystem.samples\", \"samples\"));\n\n"
                + """
                    @Test
                    void samplesBindToTheirPayloadClassesAndValidate() throws IOException {
                        int checked = 0;
                """
                + "        for (var machine : " + m + ".ALL.values()) {\n"
                + """
                            for (StateMachineSpec.Edge e : machine.spec().edges()) {
                                Path sample = SAMPLES.resolve(machine.smType()).resolve(e.eventType() + ".json");
                                if (e.payloadType() == null || !Files.exists(sample)) {
                                    continue;
                                }
                                Object bound = ModelJson.read(Files.readString(sample), e.payloadType());
                                if (bound instanceof ModelObject mo) {
                                    assertEquals(List.of(), mo.validationErrors(), sample.toString());
                                }
                                checked++;
                            }
                        }
                        assertTrue(checked > 0, "no samples under " + SAMPLES.toAbsolutePath());
                    }

                    @Test
                    void happyPathFlowsReachTerminalStates() throws IOException {
                        System.setProperty("TEMPORAL_SEARCH_ATTRIBUTES", "false");
                        InMemoryStateStore store = new InMemoryStateStore();
                        List<EntitySnapshot> snapshots = new CopyOnWriteArrayList<>();
                        try (TestWorkflowEnvironment env = TestWorkflowEnvironment.newInstance(
                                TestEnvironmentOptions.newBuilder().setUseTimeskipping(false).build())) {
                """
                + "            " + m + ".ALL.forEach((type, machine) -> {\n"
                + """
                                Worker w = env.newWorker(TaskQueues.stateMachine(type));
                                w.registerWorkflowImplementationTypes(machine.impl());
                                w.registerActivitiesImplementations(new EntityPersistenceActivitiesImpl(store), (EntitySnapshotPublisher) snapshots::add);
                            });
                            env.start();
                            WorkflowClient client = env.getWorkflowClient();
                            List<Path> flows;
                            try (Stream<Path> s = Files.list(SAMPLES.resolve("flows"))) {
                                flows = s.filter(p -> p.toString().endsWith(".json")).sorted().toList();
                            }
                            assertTrue(!flows.isEmpty(), "no flows");
                            int n = 0;
                            for (Path flow : flows) {
                                String last = null;
                                String smType = null;
                                for (JsonNode e : Json.MAPPER.readTree(Files.readString(flow)).path("events")) {
                                    JsonNode p = e.get("payload");
                """
                + "                    EventEnvelope event = " + eventsClass() + ".envelope(e.path(\"smType\").asText(), e.path(\"eventType\").asText(),\n"
                + """
                                            e.path("instanceKey").asText(), p == null || p.isNull() ? null : Json.write(p));
                                    TransitionResult r = send(client, event, flow.getFileName() + "-" + n++);
                                    assertTrue(r.accepted(), flow.getFileName() + " " + event.eventType() + " rejected: " + r);
                                    last = r.toState();
                                    smType = event.smType();
                                }
                """
                + "                assertTrue(last != null && " + m + ".get(smType).spec().isTerminal(last),\n"
                + """
                                        flow.getFileName() + " ends in non-terminal state " + last);
                            }
                        }
                    }

                    private static TransitionResult send(WorkflowClient client, EventEnvelope e, String eventId) {
                        EventEnvelope event = new EventEnvelope(eventId, e.smType(), e.instanceKey(), e.eventType(), e.lockKeys(), e.payload(), 0, 0);
                        EntityWorkflow wf = client.newWorkflowStub(EntityWorkflow.class, WorkflowOptions.newBuilder()
                                .setWorkflowId(WorkflowIds.entity(event.smType(), event.instanceKey()))
                                .setTaskQueue(TaskQueues.stateMachine(event.smType()))
                                .setWorkflowIdConflictPolicy(WorkflowIdConflictPolicy.WORKFLOW_ID_CONFLICT_POLICY_USE_EXISTING)
                                .build());
                        return WorkflowClient.executeUpdateWithStart(wf::handle, event,
                                UpdateOptions.<TransitionResult>newBuilder().setUpdateId(eventId).setWaitForStage(WorkflowUpdateStage.COMPLETED).build(),
                                new WithStartWorkflowOperation<>(wf::run, EntityInit.fresh(event.smType(), event.instanceKey())));
                    }
                }
                """;
    }
}
