package io.concert.ecosystem;

import io.concert.model.codegen.JavaNames;
import io.concert.model.pure.ClassDef;
import io.concert.model.pure.PropertyDef;
import io.concert.model.pure.ResolvedModel;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.TreeSet;

/** The Java sources of a generated ecosystem module. */
final class JavaSources {

    static final String GENERATED_HEADER = "// GENERATED by ./generate-concert-ecosystem from the Pure models -- do not edit: regenerated on every run.\n";

    private final Ecosystem eco;
    private final ResolvedModel model;

    JavaSources(Ecosystem eco) {
        this.eco = eco;
        this.model = eco.model();
    }

    String pkg() {
        return eco.javaPackage();
    }

    static String specClass(MachineDecl m) {
        return Ecosystem.pascal(m.smType()) + "Spec";
    }

    static String machineClass(MachineDecl m) {
        return Ecosystem.pascal(m.smType()) + "Machine";
    }

    String machinesClass() {
        return eco.pascalName() + "Machines";
    }

    String modelsClass() {
        return eco.pascalName() + "Models";
    }

    String workerMainClass() {
        return eco.pascalName() + "WorkerMain";
    }

    String eventsClass() {
        return eco.pascalName() + "Events";
    }

    String testClass() {
        return eco.pascalName() + "GeneratedTest";
    }

    static String q(String s) {
        StringBuilder sb = new StringBuilder("\"");
        for (char c : s.toCharArray()) {
            switch (c) {
                case '"' -> sb.append("\\\"");
                case '\\' -> sb.append("\\\\");
                case '\n' -> sb.append("\\n");
                default -> sb.append(c);
            }
        }
        return sb.append('"').toString();
    }

    static String html(String s) {
        return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("*/", "*&#47;").replace("@", "&#64;");
    }

    /** Transition table as Javadoc {@code <pre>} lines. */
    private static String table(MachineDecl m) {
        StringBuilder sb = new StringBuilder();
        for (MachineDecl.Transition t : m.transitions()) {
            sb.append(" *   ").append(html(t.from() + " -" + t.eventType() + "-> " + t.to()));
            if (t.payloadClass() != null) {
                sb.append(" : ").append(html(t.payloadClass()));
            }
            sb.append('\n');
        }
        return sb.toString();
    }

    // ---- <Name>Models ----

    String models() {
        StringBuilder files = new StringBuilder();
        List<String> lf = eco.legendFiles();
        for (int i = 0; i < lf.size(); i++) {
            files.append(i == 0 ? "" : ", ").append(q(lf.get(i)));
        }
        return GENERATED_HEADER + "package " + pkg() + ";\n\n"
                + "import io.concert.model.runtime.LegendModel;\n\n"
                + "/**\n"
                + " * Generates the Java classes of the ecosystem's Pure models ({@code src/main/pure}) at compile time:\n"
                + " * {@code a::b::X} becomes {@code " + eco.modelPackage() + ".a.b.X}.\n"
                + " */\n"
                + "@LegendModel(files = {" + files + "}, root = " + q(eco.legendRoot())
                + ", javaPackage = " + q(eco.modelPackage()) + ")\n"
                + "public final class " + modelsClass() + " {\n"
                + "    private " + modelsClass() + "() {}\n\n"
                + "    /** The {@code files} of the annotation. */\n"
                + "    public static final String[] FILES = {" + files + "};\n"
                + "}\n";
    }

    // ---- <Root>Spec ----

    String spec(MachineDecl m) {
        StringBuilder sb = new StringBuilder(GENERATED_HEADER);
        sb.append("package ").append(pkg()).append(";\n\n");
        sb.append("import com.fasterxml.jackson.databind.JsonNode;\n");
        sb.append("import io.concert.sdk.LockTemplates;\n");
        sb.append("import io.concert.sdk.StateMachineSpec;\n");
        sb.append("import java.util.List;\nimport java.util.Map;\n\n");
        sb.append("/**\n * State machine {@code ").append(m.smType()).append("} declared on {@code ").append(html(m.root().qualifiedName()))
                .append("} (").append(html(m.root().location().toString())).append(").\n *\n * <pre>\n");
        sb.append(" *   initial ").append(m.initial()).append("; terminal ").append(html(String.join(", ", m.terminal()))).append('\n');
        sb.append(table(m));
        sb.append(" * </pre>\n */\n");
        String cls = specClass(m);
        sb.append("public final class ").append(cls).append(" {\n    private ").append(cls).append("() {}\n\n");
        sb.append("    /** smType: task queue {@code sm-").append(m.smType()).append("}, workflow ids {@code ").append(m.smType())
                .append(":<key>}. */\n");
        sb.append("    public static final String TYPE = ").append(q(m.smType())).append(";\n\n");
        sb.append("    /** Qualified Pure name of the root (data) class. */\n");
        sb.append("    public static final String ROOT_CLASS = ").append(q(m.root().qualifiedName())).append(";\n\n");
        sb.append("    /** Property set to the instance key, or {@code null}. */\n");
        sb.append("    public static final String ID_PROPERTY = ").append(m.idProperty() == null ? "null" : q(m.idProperty())).append(";\n\n");
        sb.append("    /** Enum property kept equal to the state, or {@code null}. */\n");
        sb.append("    public static final String STATUS_PROPERTY = ").append(m.statusProperty() == null ? "null" : q(m.statusProperty()))
                .append(";\n\n");
        sb.append("    public static final StateMachineSpec SPEC = StateMachineSpec.startingAt(").append(q(m.initial())).append(")\n");
        for (MachineDecl.Transition t : m.transitions()) {
            sb.append("            .on(").append(q(t.from())).append(", ").append(q(t.eventType())).append(", ").append(q(t.to()));
            if (t.payloadClass() != null) {
                sb.append(", ").append(eco.javaType(t.payloadClass())).append(".class");
            }
            sb.append(")\n");
        }
        if (m.terminalDeclared()) {
            sb.append("            .terminal(");
            sb.append(String.join(", ", m.terminal().stream().map(JavaSources::q).toList()));
            sb.append(")\n");
        }
        sb.append("            .build();\n\n");
        sb.append("    /**\n     * Lock key templates per event type, beyond the target entity key (always implied): {@code {id}} is\n"
                + "     * the instance key, {@code {field}} a payload field.\n     */\n");
        sb.append("    public static final Map<String, List<String>> LOCKS = Map.ofEntries(\n");
        List<Map.Entry<String, List<String>>> entries = new ArrayList<>(m.locks().entrySet());
        for (int i = 0; i < entries.size(); i++) {
            Map.Entry<String, List<String>> e = entries.get(i);
            sb.append("            Map.entry(").append(q(e.getKey())).append(", List.of(")
                    .append(String.join(", ", e.getValue().stream().map(JavaSources::q).toList())).append("))")
                    .append(i == entries.size() - 1 ? ");\n\n" : ",\n");
        }
        sb.append("    /** The lock keys of an event, rendered from its payload. */\n");
        sb.append("    public static List<String> lockKeys(String eventType, String instanceKey, JsonNode payload) {\n");
        sb.append("        List<String> templates = LOCKS.get(eventType);\n");
        sb.append("        if (templates == null) {\n");
        sb.append("            throw new IllegalArgumentException(TYPE + \" has no event \" + eventType + \", expected one of \" + LOCKS.keySet());\n");
        sb.append("        }\n");
        sb.append("        return LockTemplates.render(templates, instanceKey, payload);\n    }\n");
        sb.append("}\n");
        return sb.toString();
    }

    // ---- <Root>Machine (user-owned stub) ----

    String stub(MachineDecl m) {
        String root = eco.javaType(m.root().qualifiedName());
        String rootSimple = Ecosystem.simpleName(root);
        String var = Character.toLowerCase(rootSimple.charAt(0)) + rootSimple.substring(1);
        if (var.equals("event") || var.equals("payload") || var.equals("from") || var.equals("to")) {
            var = var + "Data";
        }
        TreeSet<String> imports = new TreeSet<>(List.of("io.concert.common.EventEnvelope", "io.concert.sdk.ModelStateMachine",
                "io.concert.sdk.StateMachineSpec", root));
        Map<String, String> names = new LinkedHashMap<>(); // qualified Java -> name used in code
        names.put(root, rootSimple);
        java.util.function.Function<String, String> use = qualified -> names.computeIfAbsent(qualified, k -> {
            String simple = Ecosystem.simpleName(k);
            if (names.containsValue(simple)) {
                return k;
            }
            imports.add(k);
            return simple;
        });
        String statusEnum = m.statusEnum() == null ? null : use.apply(eco.javaType(m.statusEnum()));
        StringBuilder body = new StringBuilder();
        body.append("    @Override\n    protected StateMachineSpec spec() {\n        return ").append(specClass(m)).append(".SPEC;\n    }\n\n");
        body.append("    @Override\n    protected Class<").append(rootSimple).append("> dataType() {\n        return ").append(rootSimple)
                .append(".class;\n    }\n\n");
        body.append("    @Override\n    protected ").append(rootSimple).append(" initialData(String instanceKey) {\n        return new ")
                .append(rootSimple).append("()");
        if (m.idProperty() != null) {
            body.append('.').append(JavaNames.setter(m.idProperty())).append("(instanceKey)");
        }
        if (statusEnum != null) {
            body.append('.').append(JavaNames.setter(m.statusProperty())).append('(').append(statusEnum).append('.')
                    .append(JavaNames.identifier(m.initial())).append(')');
        }
        body.append(";\n    }\n\n");
        body.append("    @Override\n    protected void onTransition(String from, String to, ").append(rootSimple).append(' ').append(var)
                .append(", Object payload, EventEnvelope event) {\n");
        if (statusEnum != null) {
            body.append("        ").append(var).append('.').append(JavaNames.setter(m.statusProperty())).append('(').append(statusEnum)
                    .append(".valueOf(to));\n");
        }
        body.append("        switch (payload) {\n");
        for (String payload : m.payloadClasses()) {
            String name = use.apply(eco.javaType(payload));
            body.append("            case ").append(name).append(" cmd -> {\n");
            for (MachineDecl.Transition t : m.transitions()) {
                if (payload.equals(t.payloadClass())) {
                    body.append("                // TODO ").append(t.from()).append(" -").append(t.eventType()).append("-> ").append(t.to())
                            .append(": apply the command to the ").append(var).append(", call activities, or reject(\"...\")\n");
                }
            }
            for (String copy : copies(m, payload, var)) {
                body.append("                ").append(copy).append('\n');
            }
            body.append("            }\n");
        }
        List<MachineDecl.Transition> untyped = m.transitions().stream().filter(t -> t.payloadClass() == null).toList();
        if (!untyped.isEmpty()) {
            body.append("            case null -> {\n");
            for (MachineDecl.Transition t : untyped) {
                body.append("                // TODO ").append(t.from()).append(" -").append(t.eventType()).append("-> ").append(t.to())
                        .append(" (untyped event; see event.eventType())\n");
            }
            body.append("            }\n");
            body.append("            default -> reject(\"unexpected payload for \" + event.eventType() + \": \" + payload.getClass().getSimpleName());\n");
        } else {
            body.append("            case null, default -> reject(\"unexpected payload for \" + event.eventType() + \": \" + payload);\n");
        }
        body.append("        }\n    }\n}\n");

        StringBuilder sb = new StringBuilder();
        sb.append("// Yours to edit: generated once by ./generate-concert-ecosystem and never overwritten (--force\n"
                + "// regenerates it after backing it up as ").append(machineClass(m)).append(".java.bak-<timestamp>).\n");
        sb.append("package ").append(pkg()).append(";\n\n");
        imports.forEach(i -> sb.append("import ").append(i).append(";\n"));
        sb.append("\n/**\n * The {@code ").append(m.smType()).append("} state machine: entity data {@code ").append(html(m.root().qualifiedName()))
                .append("}, transitions\n * from {@link ").append(specClass(m)).append("} (regenerated from the Pure annotations):\n *\n * <pre>\n")
                .append(table(m)).append(" * </pre>\n *\n")
                .append(" * <p>{@code onTransition} mutates the data in place; reject an event with {@code reject(\"reason\")}. Take time\n"
                        + " * from {@code Workflow.currentTimeMillis()} (workflow code must be deterministic).\n */\n");
        sb.append("public class ").append(machineClass(m)).append(" extends ModelStateMachine<").append(rootSimple).append("> {\n\n");
        sb.append(body);
        return sb.toString();
    }

    /**
     * Starting-point code copying payload fields that have the same name, type and to-one multiplicity on
     * the root (except the id and status properties).
     */
    private List<String> copies(MachineDecl m, String payloadClass, String var) {
        ClassDef payload = model.findClass(payloadClass).orElseThrow();
        List<String> out = new ArrayList<>();
        for (PropertyDef p : model.allProperties(payload)) {
            if (!p.multiplicity().isToOne() || p.name().equals(m.idProperty()) || p.name().equals(m.statusProperty())) {
                continue;
            }
            Optional<PropertyDef> r = model.allProperties(m.root()).stream().filter(x -> x.name().equals(p.name())).findFirst();
            if (r.isPresent() && r.get().type().equals(p.type()) && r.get().multiplicity().isToOne()) {
                String get = "cmd." + JavaNames.getter(p.name()) + "()";
                out.add("if (" + get + " != null) {\n                    " + var + "." + JavaNames.setter(p.name()) + "(" + get
                        + ");\n                }");
            }
        }
        if (!out.isEmpty()) {
            out.addFirst("// generated starting point: copy the fields the command shares with the " + var);
        }
        return out;
    }

    // ---- <Name>Machines ----

    String machines() {
        StringBuilder sb = new StringBuilder(GENERATED_HEADER);
        sb.append("package ").append(pkg()).append(";\n\n");
        sb.append("import io.concert.sdk.MachineCatalog;\nimport io.concert.sdk.StateMachineRegistry;\nimport java.util.LinkedHashMap;\n"
                + "import java.util.List;\nimport java.util.Map;\n\n");
        sb.append("/**\n * The machines of ecosystem {@code ").append(eco.name()).append("} by smType: their specs and the model's class diagram\n"
                + " * (for the worker, the event sender and, through the {@link MachineCatalog} SPI, the trace UI).\n */\n");
        String cls = machinesClass();
        sb.append("public final class ").append(cls).append(" implements MachineCatalog {\n\n");
        sb.append("    /** Mermaid class diagram of the ecosystem's model (all model files). */\n");
        sb.append("    public static final String MODEL_MERMAID = mermaid(");
        List<String> registries = eco.modelRegistryClasses();
        sb.append(String.join(", ", registries.stream().map(r -> r + ".MERMAID").toList())).append(");\n\n");
        sb.append("    /** In declaration order. */\n");
        sb.append("    public static final Map<String, Machine> ALL = index(\n");
        for (int i = 0; i < eco.machines().size(); i++) {
            MachineDecl m = eco.machines().get(i);
            sb.append("            new Machine(").append(specClass(m)).append(".TYPE, ").append(machineClass(m)).append(".class, ")
                    .append(specClass(m)).append(".SPEC, MODEL_MERMAID)").append(i == eco.machines().size() - 1 ? ");\n\n" : ",\n");
        }
        sb.append("    /** Lock key templates per smType and event type. */\n");
        sb.append("    public static final Map<String, Map<String, List<String>>> LOCKS = Map.ofEntries(\n");
        for (int i = 0; i < eco.machines().size(); i++) {
            MachineDecl m = eco.machines().get(i);
            sb.append("            Map.entry(").append(specClass(m)).append(".TYPE, ").append(specClass(m)).append(".LOCKS)")
                    .append(i == eco.machines().size() - 1 ? ");\n\n" : ",\n");
        }
        sb.append("""
                    private static Map<String, Machine> index(Machine... machines) {
                        Map<String, Machine> m = new LinkedHashMap<>();
                        for (Machine x : machines) {
                            m.put(x.smType(), x);
                        }
                        return java.util.Collections.unmodifiableMap(m);
                    }

                    /** Merges generated {@code classDiagram}s (one per model file) into one diagram. */
                    static String mermaid(String... diagrams) {
                        StringBuilder sb = new StringBuilder("classDiagram\\n");
                        for (String d : diagrams) {
                            sb.append(d.substring(d.indexOf('\\n') + 1));
                        }
                        return sb.toString();
                    }

                    /** Registers the specs in {@link StateMachineRegistry}. */
                    public static void registerSpecs() {
                        ALL.forEach((type, m) -> StateMachineRegistry.register(type, m.spec()));
                    }

                    public static Machine get(String smType) {
                        Machine m = ALL.get(smType);
                        if (m == null) {
                            throw new IllegalArgumentException("unknown smType " + smType + ", expected one of " + ALL.keySet());
                        }
                        return m;
                    }

                    @Override
                    public String name() {
                        return NAME;
                    }

                    @Override
                    public List<Machine> machines() {
                        return List.copyOf(ALL.values());
                    }

                """);
        sb.append("    /** The ecosystem (module) name. */\n    public static final String NAME = ").append(q(eco.name())).append(";\n}\n");
        return sb.toString();
    }

    // ---- <Name>WorkerMain ----

    String workerMain() {
        String cls = workerMainClass();
        String m = machinesClass();
        String env = eco.name().toUpperCase(java.util.Locale.ROOT).replace('-', '_') + "_SM_TYPES";
        return GENERATED_HEADER + "package " + pkg() + ";\n\n"
                + """
                import io.concert.common.Env;
                import io.concert.common.TemporalClients;
                import io.concert.sdk.EntitySnapshotPublisher;
                import io.concert.sdk.MachineCatalog;
                import io.concert.sdk.WorkerBootstrap;
                import io.concert.sink.SnapshotCodec;
                import io.concert.store.StateStore;
                import io.concert.store.Stores;
                import io.temporal.worker.WorkerFactory;
                import java.util.ArrayList;
                import java.util.List;
                import org.slf4j.Logger;
                import org.slf4j.LoggerFactory;

                """
                + "/**\n * Runs the workers of every machine of ecosystem {@code " + eco.name() + "} in one process (task queues\n"
                + " * {@code sm-<smType>}). Environment as for every worker ({@code TEMPORAL_*}, {@code STORE_KIND},\n"
                + " * {@code KAFKA_BOOTSTRAP}, ...); {@code " + env + "} (comma separated) optionally restricts the types.\n */\n"
                + "public final class " + cls + " {\n"
                + "    private static final Logger log = LoggerFactory.getLogger(" + cls + ".class);\n\n"
                + "    private " + cls + "() {}\n\n"
                + "    public static void main(String[] args) throws InterruptedException {\n"
                + "        StateStore store = Stores.fromEnv();\n"
                + "        var client = TemporalClients.fromEnv();\n"
                + "        " + m + ".registerSpecs();\n"
                + "        // One Kafka producer for all types (no-op when KAFKA_BOOTSTRAP is empty); the schemaHash header is\n"
                + "        // the hash of the ecosystem's model diagram.\n"
                + "        String schemaHash = SnapshotCodec.schemaHash(" + m + ".MODEL_MERMAID);\n"
                + "        EntitySnapshotPublisher snapshots = EntitySnapshotPublisher.fromEnv(\n"
                + "                type -> " + m + ".ALL.containsKey(type) ? schemaHash : null);\n"
                + "        String types = Env.get(\"" + env + "\", String.join(\",\", " + m + ".ALL.keySet()));\n"
                + "        List<WorkerFactory> factories = new ArrayList<>();\n"
                + "        for (String type : types.split(\",\")) {\n"
                + "            MachineCatalog.Machine machine = " + m + ".get(type.trim());\n"
                + "            factories.add(WorkerBootstrap.start(client, store, machine.smType(), machine.impl(), snapshots));\n"
                + "            log.info(\"worker up for sm-{}\", machine.smType());\n"
                + "        }\n"
                + "        Runtime.getRuntime().addShutdownHook(new Thread(() -> {\n"
                + "            factories.forEach(WorkerFactory::shutdown);\n"
                + "            store.close();\n"
                + "        }));\n"
                + "        Thread.currentThread().join();\n"
                + "    }\n"
                + "}\n";
    }

    // ---- <Name>Events ----

    /** The Kinesis sender: entity-style events of the machines and / or event-style events of the event types. */
    String events() {
        String cls = eventsClass();
        String m = machinesClass();
        String t = eco.pascalName() + "EventTypes";
        boolean sm = eco.hasMachines();
        boolean ev = eco.hasEvents();
        TreeSet<String> imports = new TreeSet<>(List.of("com.fasterxml.jackson.databind.JsonNode", "io.concert.common.Env",
                "io.concert.common.EventEnvelope", "io.concert.common.Json", "io.concert.model.runtime.ModelJson",
                "io.concert.model.runtime.ModelObject", "io.concert.orchestration.KinesisClients", "io.concert.sdk.LockTemplates",
                "java.io.IOException", "java.nio.charset.StandardCharsets", "java.nio.file.Files", "java.nio.file.Path",
                "java.util.ArrayList", "java.util.List", "java.util.UUID", "software.amazon.awssdk.core.SdkBytes",
                "software.amazon.awssdk.services.kinesis.KinesisClient"));
        if (sm) {
            imports.addAll(List.of("io.concert.sdk.MachineCatalog", "io.concert.sdk.StateMachineSpec", "java.util.Map"));
        }
        if (ev) {
            imports.addAll(List.of("io.concert.sdk.events.EventCatalog", "java.time.Duration", "java.time.Instant",
                    "java.time.OffsetDateTime", "java.time.format.DateTimeParseException"));
        }
        StringBuilder sb = new StringBuilder(GENERATED_HEADER);
        sb.append("package ").append(pkg()).append(";\n\n");
        imports.forEach(i -> sb.append("import ").append(i).append(";\n"));
        sb.append("\n/**\n * Sends events of ecosystem {@code ").append(eco.name()).append("} to Kinesis ({@code INGEST_STREAM}, default\n"
                + " * {@code concert-events}; {@code KINESIS_ENDPOINT}, e.g. {@code http://localhost:4566}), addressed and locked as\n"
                + " * the Pure annotations declare: lock keys are rendered from the payload, the partition key is the first sorted\n"
                + " * lock key. Payloads are checked against their model class before sending.\n *\n * <pre>\n");
        if (sm) {
            sb.append(" * send &lt;smType&gt; &lt;eventType&gt; &lt;instanceKey&gt; [payload.json | - | '{...json...}']        entity style\n");
        }
        if (ev) {
            sb.append(" * send &lt;EventType&gt; [payload.json | - | '{...json...}'] [--at ISO|+30s|+5m|+2h] [--id ID]   event style\n"
                    + " *      (no payload: $ECOSYSTEM_SAMPLES/events/&lt;EventType&gt;.json)\n");
        }
        sb.append(" * flow &lt;flow.json&gt; [--delay-ms 500]     {\"events\": [...]}: ");
        if (sm) {
            sb.append("{smType, instanceKey, eventType, payload}");
        }
        if (sm && ev) {
            sb.append(" or ");
        }
        if (ev) {
            sb.append("{style: event, eventType, payload, at?, id?}");
        }
        sb.append("\n * list\n * </pre>\n */\n");
        sb.append("public final class ").append(cls).append(" {\n    private ").append(cls).append("() {}\n\n");
        sb.append("""
                    public static void main(String[] args) throws Exception {
                        try {
                            run(args);
                        } catch (IllegalArgumentException | java.io.UncheckedIOException e) {
                            System.err.println("error: " + e.getMessage());
                            System.exit(1);
                        }
                    }

                    private static void run(String[] args) throws Exception {
                        if (args.length == 0) {
                            usage();
                            System.exit(2);
                        }
                        switch (args[0]) {
                            case "list" -> list();
                            case "send" -> {
                """);
        if (ev) {
            sb.append("                if (args.length >= 2 && ").append(t).append(".isEventType(args[1])) {\n");
            sb.append("                    sendEvent(args);\n                    return;\n                }\n");
        }
        if (sm) {
            sb.append("""
                                    if (args.length < 4) {
                                        usage();
                                        System.exit(2);
                                    }
                                    String payload = args.length > 4 ? readPayload(args[4]) : null;
                                    EventEnvelope e = envelope(args[1], args[2], args[3], payload);
                                    try (KinesisClient kinesis = KinesisClients.fromEnv()) {
                                        publish(kinesis, e);
                                    }
                    """);
        } else {
            sb.append("                usage();\n                System.exit(2);\n");
        }
        sb.append("""
                            }
                            case "flow" -> {
                                if (args.length < 2) {
                                    usage();
                                    System.exit(2);
                                }
                                long delay = args.length > 3 && args[2].equals("--delay-ms") ? Long.parseLong(args[3]) : 500;
                                flow(Path.of(args[1]), delay);
                            }
                            default -> {
                                usage();
                                System.exit(2);
                            }
                        }
                    }

                    private static void usage() {
                        System.err.println("usage: "
                """);
        if (sm) {
            sb.append("                + \"send <smType> <eventType> <instanceKey> [payload.json | - | '{json}']\\n       \"\n");
        }
        if (ev) {
            sb.append("                + \"send <EventType> [payload.json | - | '{json}'] [--at ISO|+30s|+5m|+2h] [--id ID]\\n       \"\n");
        }
        sb.append("                + \"flow <flow.json> [--delay-ms N]\\n       list\"");
        if (sm) {
            sb.append("\n                + \"\\nsmTypes: \" + ").append(m).append(".ALL.keySet()");
        }
        if (ev) {
            sb.append("\n                + \"\\nevent types: \" + ").append(t).append(".typeNames()");
        }
        sb.append(");\n    }\n\n");

        sb.append("    private static void list() {\n");
        if (sm) {
            sb.append("        ").append(m).append(".ALL.forEach((type, machine) -> {\n")
                    .append("            System.out.println(type + \"  (initial \" + machine.spec().initialState() + \", terminal \" + machine.spec().terminalStates() + \")\");\n")
                    .append("            for (StateMachineSpec.Edge e : machine.spec().edges()) {\n")
                    .append("                System.out.printf(\"  %-14s %s -> %s  payload %s  locks %s%n\", e.eventType(), e.from(), e.to(),\n")
                    .append("                        e.payloadType() == null ? \"-\" : e.payloadType().getSimpleName(), ").append(m)
                    .append(".LOCKS.get(type).get(e.eventType()));\n")
                    .append("            }\n        });\n");
        }
        if (ev) {
            sb.append("        for (String domain : ").append(t).append(".DOMAINS) {\n")
                    .append("            System.out.println(\"event domain \" + domain + \"  (task queue ev-\" + domain + \")\");\n")
                    .append("            for (EventCatalog.EventType e : ").append(t).append(".types()) {\n")
                    .append("                if (e.domain().equals(domain)) {\n")
                    .append("                    System.out.printf(\"  %-24s locks %s  onError %s  attempts %d  emits %s%n\", e.name(),\n")
                    .append("                            e.lockTemplates().isEmpty() ? \"[\" + domain + \":{id}]\" : e.lockTemplates(), e.onError(), e.maxAttempts(), ")
                    .append(t).append(".emits(e.name()));\n")
                    .append("                }\n            }\n        }\n");
        }
        sb.append("    }\n\n");
        sb.append("""
                    private static String readPayload(String arg) throws IOException {
                        if (arg.equals("-")) {
                            return new String(System.in.readAllBytes(), StandardCharsets.UTF_8);
                        }
                        String t = arg.strip();
                        return t.startsWith("{") || t.equals("null") ? t : Files.readString(Path.of(arg), StandardCharsets.UTF_8);
                    }

                    /** The payload bound to its model class and validated (multiplicities), then serialized back. */
                    private static String checked(String payload, Class<?> type) {
                        String json = payload == null || payload.isBlank() || payload.strip().equals("null") ? null : payload.strip();
                        if (type != null && json != null) {
                            Object bound = ModelJson.read(json, type);
                            if (bound instanceof ModelObject mo && !mo.validationErrors().isEmpty()) {
                                throw new IllegalArgumentException("invalid " + type.getSimpleName() + " payload: "
                                        + String.join("; ", mo.validationErrors()));
                            }
                            json = ModelJson.write(bound);
                        }
                        return json;
                    }

                    private static JsonNode tree(String json) {
                        try {
                            return json == null ? null : Json.MAPPER.readTree(json);
                        } catch (com.fasterxml.jackson.core.JsonProcessingException x) {
                            throw new IllegalArgumentException("payload is not JSON: " + x.getOriginalMessage(), x);
                        }
                    }

                """);
        if (sm) {
            sb.append("    /**\n"
                    + "     * An entity-style event, validated: the smType and event type exist, the payload binds to the event's payload class\n"
                    + "     * and satisfies its multiplicities, and every lock key renders.\n"
                    + "     */\n"
                    + "    public static EventEnvelope envelope(String smType, String eventType, String instanceKey, String payload) {\n"
                    + "        MachineCatalog.Machine machine = " + m + ".get(smType);\n"
                    + "        StateMachineSpec.Edge edge = machine.spec().edges().stream().filter(x -> x.eventType().equals(eventType)).findFirst()\n"
                    + "                .orElseThrow(() -> new IllegalArgumentException(smType + \" has no event \" + eventType + \"; events: \"\n"
                    + "                        + machine.spec().edges().stream().map(StateMachineSpec.Edge::eventType).distinct().toList()));\n"
                    + "        String json = checked(payload, edge.payloadType());\n"
                    + "        List<String> locks = LockTemplates.render(" + m + ".LOCKS.get(smType).get(eventType), instanceKey, tree(json));\n"
                    + "        return new EventEnvelope(smType + \"-\" + eventType + \"-\" + UUID.randomUUID(), smType, instanceKey, eventType, locks, json,\n"
                    + "                System.currentTimeMillis(), 0);\n"
                    + "    }\n\n");
        }
        if (ev) {
            sb.append("""
                        private static void sendEvent(String[] args) throws IOException {
                            String type = args[1];
                            String payload = null;
                            long at = 0;
                            String id = null;
                            for (int i = 2; i < args.length; i++) {
                                switch (args[i]) {
                                    case "--at" -> at = parseAt(value(args, ++i, "--at"));
                                    case "--id" -> id = value(args, ++i, "--id");
                                    default -> payload = readPayload(args[i]);
                                }
                            }
                            if (payload == null) {
                                payload = samplePayload(type);
                            }
                            EventEnvelope e = eventEnvelope(type, payload, at, id);
                            try (KinesisClient kinesis = KinesisClients.fromEnv()) {
                                publish(kinesis, e);
                            }
                        }

                        private static String value(String[] args, int i, String option) {
                            if (i >= args.length) {
                                throw new IllegalArgumentException(option + " needs a value");
                            }
                            return args[i];
                        }

                        /** {@code $ECOSYSTEM_SAMPLES/events/<type>.json} (set by the send script), else {@code null}. */
                        private static String samplePayload(String type) throws IOException {
                            String dir = Env.get("ECOSYSTEM_SAMPLES", "");
                            Path p = dir.isBlank() ? null : Path.of(dir, "events", type + ".json");
                            return p != null && Files.isRegularFile(p) ? Files.readString(p, StandardCharsets.UTF_8) : null;
                        }

                        /** {@code +30s}, {@code +5m}, {@code +2h}, {@code +1d} from now, or an ISO-8601 instant / offset date-time. */
                        public static long parseAt(String at) {
                            String s = at.strip();
                            if (s.startsWith("+") && s.length() > 2) {
                                long n = Long.parseLong(s.substring(1, s.length() - 1));
                                Duration d = switch (s.charAt(s.length() - 1)) {
                                    case 's' -> Duration.ofSeconds(n);
                                    case 'm' -> Duration.ofMinutes(n);
                                    case 'h' -> Duration.ofHours(n);
                                    case 'd' -> Duration.ofDays(n);
                                    default -> throw new IllegalArgumentException("bad --at " + at + ": use +30s, +5m, +2h, +1d or an ISO instant");
                                };
                                return System.currentTimeMillis() + d.toMillis();
                            }
                            try {
                                return Instant.parse(s).toEpochMilli();
                            } catch (DateTimeParseException notInstant) {
                                try {
                                    return OffsetDateTime.parse(s).toInstant().toEpochMilli();
                                } catch (DateTimeParseException e) {
                                    throw new IllegalArgumentException("bad --at " + at + ": use +30s, +5m, +2h, +1d or an ISO instant", e);
                                }
                            }
                        }

                        /**
                         * An event-style event, validated: the type exists, the payload binds to its class and satisfies its
                         * multiplicities, and every lock key renders from it.
                         *
                         * @param atMillis apply no earlier than this (SCHEDULED until then); 0 = now
                         * @param eventId {@code null}: {@code <EventType>-<random>}
                         */
                        public static EventEnvelope eventEnvelope(String eventType, String payload, long atMillis, String eventId) {
                    """);
            sb.append("            EventCatalog.EventType type = ").append(t).append(".type(eventType);\n");
            sb.append("""
                            String json = checked(payload, type.payloadType());
                            String id = eventId != null ? eventId : eventType + "-" + UUID.randomUUID().toString().replace("-", "").substring(0, 12);
                            List<String> locks = type.lockTemplates().isEmpty() ? List.of() : LockTemplates.render(type.lockTemplates(), id, tree(json));
                            EventEnvelope e = EventEnvelope.event(id, type.domain(), type.name(), locks, json, System.currentTimeMillis());
                            return atMillis > 0 ? e.withScheduledAt(atMillis) : e;
                        }

                    """);
        }
        sb.append("""
                    private static void publish(KinesisClient kinesis, EventEnvelope e) {
                        String stream = Env.get("INGEST_STREAM", "concert-events");
                        String partitionKey = e.effectiveLockKeys().getFirst();
                        kinesis.putRecord(b -> b.streamName(stream).partitionKey(partitionKey).data(SdkBytes.fromUtf8String(Json.write(e))));
                        if (e.isEventStyle()) {
                            System.out.printf("sent %s event %s (domain %s)  locks %s  (partition key %s)%s%n", e.eventId(), e.eventType(), e.domain(),
                                    e.effectiveLockKeys(), partitionKey, e.scheduledAtMillis() > 0 ? "  scheduled at "
                                            + java.time.Instant.ofEpochMilli(e.scheduledAtMillis()) : "");
                        } else {
                            System.out.printf("sent %s %s:%s %s  locks %s  (partition key %s)%n", e.eventId(), e.smType(), e.instanceKey(),
                                    e.eventType(), e.effectiveLockKeys(), partitionKey);
                        }
                    }

                    private static void flow(Path file, long delayMs) throws IOException, InterruptedException {
                        JsonNode flow = Json.MAPPER.readTree(Files.readString(file, StandardCharsets.UTF_8));
                        List<EventEnvelope> events = new ArrayList<>();
                        for (JsonNode e : flow.path("events")) {
                            JsonNode p = e.get("payload");
                            String payload = p == null || p.isNull() ? null : Json.write(p);
                """);
        if (ev) {
            sb.append("""
                                if (e.path("style").asText("").equals("event")) {
                                    long at = e.hasNonNull("at") ? parseAt(e.get("at").asText()) : 0;
                                    events.add(eventEnvelope(e.path("eventType").asText(), payload, at,
                                            e.hasNonNull("id") ? e.get("id").asText() : null));
                                    continue;
                                }
                    """);
        }
        if (sm) {
            sb.append("            events.add(envelope(e.path(\"smType\").asText(), e.path(\"eventType\").asText(), e.path(\"instanceKey\").asText(), payload));\n");
        } else {
            sb.append("            throw new IllegalArgumentException(file + \": flow event without \\\"style\\\": \\\"event\\\": \" + e);\n");
        }
        sb.append("""
                        }
                        System.out.printf("flow %s: %d events%n", flow.path("name").asText(file.getFileName().toString()), events.size());
                        try (KinesisClient kinesis = KinesisClients.fromEnv()) {
                            for (int i = 0; i < events.size(); i++) {
                                if (i > 0 && delayMs > 0) {
                                    Thread.sleep(delayMs); // events of one entity in order, even across shards
                                }
                                publish(kinesis, events.get(i));
                            }
                        }
                    }
                """);
        if (sm) {
            sb.append("\n    /** smType to machine, for tests and tools. */\n"
                    + "    public static Map<String, MachineCatalog.Machine> machines() {\n"
                    + "        return " + m + ".ALL;\n    }\n");
        }
        sb.append("}\n");
        return sb.toString();
    }

    // ---- generated test ----

    String test() {
        String cls = testClass();
        String m = machinesClass();
        return GENERATED_HEADER + "package " + pkg() + ";\n\n"
                + """
                import static org.junit.jupiter.api.Assertions.assertEquals;
                import static org.junit.jupiter.api.Assertions.assertTrue;

                import com.fasterxml.jackson.databind.JsonNode;
                import io.concert.common.EventEnvelope;
                import io.concert.common.Json;
                import io.concert.common.TaskQueues;
                import io.concert.common.WorkflowIds;
                import io.concert.common.api.EntityInit;
                import io.concert.common.api.EntityWorkflow;
                import io.concert.common.api.TransitionResult;
                import io.concert.model.runtime.ModelJson;
                import io.concert.model.runtime.ModelObject;
                import io.concert.sdk.EntityPersistenceActivitiesImpl;
                import io.concert.sdk.EntitySnapshotPublisher;
                import io.concert.sdk.StateMachineSpec;
                import io.concert.sink.EntitySnapshot;
                import io.concert.store.InMemoryStateStore;
                import io.temporal.api.enums.v1.WorkflowIdConflictPolicy;
                import io.temporal.client.UpdateOptions;
                import io.temporal.client.WithStartWorkflowOperation;
                import io.temporal.client.WorkflowClient;
                import io.temporal.client.WorkflowOptions;
                import io.temporal.client.WorkflowUpdateStage;
                import io.temporal.testing.TestEnvironmentOptions;
                import io.temporal.testing.TestWorkflowEnvironment;
                import io.temporal.worker.Worker;
                import java.io.IOException;
                import java.nio.file.Files;
                import java.nio.file.Path;
                import java.util.List;
                import java.util.concurrent.CopyOnWriteArrayList;
                import java.util.stream.Stream;
                import org.junit.jupiter.api.Test;

                """
                + "/** Checks the generated samples and runs every happy-path flow through the real machines (your stubs). */\n"
                + "class " + cls + " {\n\n"
                + "    private static final Path SAMPLES = Path.of(System.getProperty(\"ecosystem.samples\", \"samples\"));\n\n"
                + """
                    @Test
                    void samplesBindToTheirPayloadClassesAndValidate() throws IOException {
                        int checked = 0;
                """
                + "        for (var machine : " + m + ".ALL.values()) {\n"
                + """
                            for (StateMachineSpec.Edge e : machine.spec().edges()) {
                                Path sample = SAMPLES.resolve(machine.smType()).resolve(e.eventType() + ".json");
                                if (e.payloadType() == null || !Files.exists(sample)) {
                                    continue;
                                }
                                Object bound = ModelJson.read(Files.readString(sample), e.payloadType());
                                if (bound instanceof ModelObject mo) {
                                    assertEquals(List.of(), mo.validationErrors(), sample.toString());
                                }
                                checked++;
                            }
                        }
                        assertTrue(checked > 0, "no samples under " + SAMPLES.toAbsolutePath());
                    }

                    @Test
                    void happyPathFlowsReachTerminalStates() throws IOException {
                        System.setProperty("TEMPORAL_SEARCH_ATTRIBUTES", "false");
                        InMemoryStateStore store = new InMemoryStateStore();
                        List<EntitySnapshot> snapshots = new CopyOnWriteArrayList<>();
                        try (TestWorkflowEnvironment env = TestWorkflowEnvironment.newInstance(
                                TestEnvironmentOptions.newBuilder().setUseTimeskipping(false).build())) {
                """
                + "            " + m + ".ALL.forEach((type, machine) -> {\n"
                + """
                                Worker w = env.newWorker(TaskQueues.stateMachine(type));
                                w.registerWorkflowImplementationTypes(machine.impl());
                                w.registerActivitiesImplementations(new EntityPersistenceActivitiesImpl(store), (EntitySnapshotPublisher) snapshots::add);
                            });
                            env.start();
                            WorkflowClient client = env.getWorkflowClient();
                            List<Path> flows;
                            try (Stream<Path> s = Files.list(SAMPLES.resolve("flows"))) {
                                flows = s.filter(p -> p.toString().endsWith(".json")).sorted().toList();
                            }
                            assertTrue(!flows.isEmpty(), "no flows");
                            int n = 0;
                            for (Path flow : flows) {
                                String last = null;
                                String smType = null;
                                for (JsonNode e : Json.MAPPER.readTree(Files.readString(flow)).path("events")) {
                                    JsonNode p = e.get("payload");
                """
                + "                    EventEnvelope event = " + eventsClass() + ".envelope(e.path(\"smType\").asText(), e.path(\"eventType\").asText(),\n"
                + """
                                            e.path("instanceKey").asText(), p == null || p.isNull() ? null : Json.write(p));
                                    TransitionResult r = send(client, event, flow.getFileName() + "-" + n++);
                                    assertTrue(r.accepted(), flow.getFileName() + " " + event.eventType() + " rejected: " + r);
                                    last = r.toState();
                                    smType = event.smType();
                                }
                """
                + "                assertTrue(last != null && " + m + ".get(smType).spec().isTerminal(last),\n"
                + """
                                        flow.getFileName() + " ends in non-terminal state " + last);
                            }
                        }
                    }

                    private static TransitionResult send(WorkflowClient client, EventEnvelope e, String eventId) {
                        EventEnvelope event = new EventEnvelope(eventId, e.smType(), e.instanceKey(), e.eventType(), e.lockKeys(), e.payload(), 0, 0);
                        EntityWorkflow wf = client.newWorkflowStub(EntityWorkflow.class, WorkflowOptions.newBuilder()
                                .setWorkflowId(WorkflowIds.entity(event.smType(), event.instanceKey()))
                                .setTaskQueue(TaskQueues.stateMachine(event.smType()))
                                .setWorkflowIdConflictPolicy(WorkflowIdConflictPolicy.WORKFLOW_ID_CONFLICT_POLICY_USE_EXISTING)
                                .build());
                        return WorkflowClient.executeUpdateWithStart(wf::handle, event,
                                UpdateOptions.<TransitionResult>newBuilder().setUpdateId(eventId).setWaitForStage(WorkflowUpdateStage.COMPLETED).build(),
                                new WithStartWorkflowOperation<>(wf::run, EntityInit.fresh(event.smType(), event.instanceKey())));
                    }
                }
                """;
    }
}
