package io.concert.ecosystem;

import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.JsonNodeFactory;
import com.fasterxml.jackson.databind.node.ObjectNode;
import io.concert.model.pure.ClassDef;
import io.concert.model.pure.PrimitiveType;
import io.concert.model.pure.PropertyDef;
import io.concert.model.pure.ResolvedModel;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Set;

/** The non-Java files of a generated module: build, compose, Deephaven snippet, README, manifest, scripts. */
final class ProjectFiles {

    private static final Set<String> DH_SYSTEM = Set.of("EntityId", "SmType", "State", "Version", "CreatedAt", "CompletedAt",
            "LatencyMs", "CreatedAtText", "CompletedAtText");

    private final Ecosystem eco;
    private final JavaSources java;
    private final ResolvedModel model;

    ProjectFiles(Ecosystem eco, JavaSources java) {
        this.eco = eco;
        this.java = java;
        this.model = eco.model();
    }

    String moduleDir() {
        return "showcases/" + eco.name();
    }

    String envSuffix() {
        return eco.name().toUpperCase(Locale.ROOT).replace('-', '_');
    }

    /**
     * {@code SINK_ROOTS} entries: each machine's root, each event type's lifecycle rows ({@code evt_<type>}: the sinks
     * add the lifecycle columns and flatten the payload class) and each keyed-state type ({@code st_<type>}).
     */
    String sinkRoots() {
        List<String> roots = new ArrayList<>();
        eco.machines().forEach(m -> roots.add(m.smType() + ":" + m.root().qualifiedName()));
        eco.events().forEach(e -> roots.add(e.smType() + ":" + e.cls().qualifiedName()));
        eco.states().forEach(st -> roots.add(st.smType() + ":" + st.cls().qualifiedName()));
        return String.join(",", roots);
    }

    // ---- build.gradle.kts ----

    String build() {
        EventSources ev = new EventSources(eco);
        String main = java.pkg() + "." + (eco.hasMachines() ? java.workerMainClass() : ev.workerMainClass());
        String events = java.pkg() + "." + java.eventsClass();
        StringBuilder scripts = new StringBuilder();
        StringBuilder contents = new StringBuilder();
        if (eco.hasMachines()) {
            scripts.append("""
                    // bin/ecosystem-worker: the state machine worker under a fixed name (the generic showcase-worker Docker target)
                    val workerScripts = tasks.register<CreateStartScripts>("workerStartScripts") {
                        mainClass.set("%s")
                        applicationName = "ecosystem-worker"
                        defaultJvmOpts = jvmArgs
                        classpath = tasks.startScripts.get().classpath
                        outputDir = layout.buildDirectory.dir("worker-scripts").get().asFile
                    }

                    """.formatted(java.pkg() + "." + java.workerMainClass()));
            contents.append("        from(workerScripts) { into(\"bin\") }\n");
        }
        if (eco.hasEvents()) {
            scripts.append("""
                    // bin/ecosystem-event-worker: the event-style worker (one worker per domain, your handlers)
                    val eventWorkerScripts = tasks.register<CreateStartScripts>("eventWorkerStartScripts") {
                        mainClass.set("%s")
                        applicationName = "ecosystem-event-worker"
                        defaultJvmOpts = jvmArgs
                        classpath = tasks.startScripts.get().classpath
                        outputDir = layout.buildDirectory.dir("event-worker-scripts").get().asFile
                    }

                    """.formatted(java.pkg() + "." + ev.workerMainClass()));
            contents.append("        from(eventWorkerScripts) { into(\"bin\") }\n");
        }
        contents.append("        from(eventScripts) { into(\"bin\") }\n");
        String what = eco.hasMachines() && eco.hasEvents() ? "the state machines (concert::sm) and event types (concert::event)"
                : eco.hasMachines() ? "the state machines declared in src/main/pure (concert::sm profile)"
                : "the event types declared in src/main/pure (concert::event profile)";
        String bins = (eco.hasMachines() ? "bin/ecosystem-worker runs the state machine workers, " : "")
                + (eco.hasEvents() ? "bin/ecosystem-event-worker the event handlers, " : "");
        return """
                // GENERATED by ./generate-concert-ecosystem -- do not edit: regenerated on every run. Put extra build
                // logic in extra.gradle.kts next to this file (applied below when present; use string configuration
                // names there, e.g. dependencies { "testImplementation"(project(":x")) }).
                //
                // Ecosystem "%1$s": %5$s.
                // %6$sbin/events sends events (./showcases/%1$s/send).
                plugins { application }

                dependencies {
                    implementation(project(":worker-sdk"))
                    // POJOs generated from src/main/pure (the root build passes the directory to the processor)
                    implementation(project(":model-runtime"))
                    annotationProcessor(project(":model-codegen"))
                    // %2$s: KinesisClients; the generated tests run the real lock chain
                    implementation(project(":orchestration"))
                    implementation(platform(libs.aws.bom))
                    implementation(libs.aws.kinesis)
                    // STORE_KIND=dynamo|spanner backends, discovered via ServiceLoader
                    runtimeOnly(project(":store-dynamo"))
                    runtimeOnly(project(":store-spanner"))
                    runtimeOnly(libs.slf4j.simple)

                    testImplementation(libs.temporal.testing)
                    testImplementation(platform(libs.junit.bom))
                    testImplementation(libs.junit.jupiter)
                    testRuntimeOnly(libs.junit.launcher)
                }

                val jvmArgs = listOf("-XX:+UseZGC", "-XX:+UseCompactObjectHeaders")

                application {
                    mainClass.set("%3$s")
                    applicationDefaultJvmArgs = jvmArgs
                }

                %7$s// bin/events: the event sender
                val eventScripts = tasks.register<CreateStartScripts>("eventStartScripts") {
                    mainClass.set("%4$s")
                    applicationName = "events"
                    defaultJvmOpts = listOf("-XX:+UseSerialGC", "-XX:TieredStopAtLevel=1")
                    classpath = tasks.startScripts.get().classpath
                    outputDir = layout.buildDirectory.dir("event-scripts").get().asFile
                }

                distributions.main {
                    contents {
                %8$s    }
                }

                tasks.test {
                    systemProperty("ecosystem.samples", layout.projectDirectory.dir("samples").asFile.absolutePath)
                    // the in-memory Temporal server cancels still-running workflows on close: keep its warnings out of the build
                    systemProperty("org.slf4j.simpleLogger.log.io.temporal.internal", "error")
                    inputs.dir(layout.projectDirectory.dir("samples")).withPathSensitivity(PathSensitivity.RELATIVE)
                }

                if (file("extra.gradle.kts").isFile) {
                    apply(from = "extra.gradle.kts")
                }
                """.formatted(eco.name(), java.eventsClass(), main, events, what, bins, scripts, contents);
    }

    // ---- compose.yml ----

    String compose() {
        String n = eco.name();
        String env = """
                    depends_on:
                      temporal-init: { condition: service_completed_successfully }
                      localstack: { condition: service_healthy }
                      coordinator: { condition: service_started }
                    environment:
                      STORE_KIND: ${STORE_KIND:-postgres}
                      TEMPORAL_ADDRESS: temporal:7233
                      KINESIS_ENDPOINT: http://localstack:4566
                      STORE_JDBC_URL: jdbc:postgresql://dsql:5432/concert
                      DYNAMO_ENDPOINT: http://localstack:4566
                      SPANNER_EMULATOR_HOST: spanner:9010
                      TRACE_SAMPLE: ${TRACE_SAMPLE:-1.0}
                      AWS_REGION: us-east-1
                      KAFKA_BOOTSTRAP: ${KAFKA_BOOTSTRAP-kafka:9092}
                      SINK_DUCKDB_URL: http://sink-duckdb:8090
                      STORE_INIT_SCHEMA: "false"
                      JAVA_OPTS: -XX:+UseZGC -XX:+UseCompactObjectHeaders -XX:MaxRAMPercentage=50
                %s    deploy: { resources: { limits: { memory: 1g } } }
                    restart: unless-stopped
                """;
        String build = """
                    build:
                      context: .
                      target: showcase-worker
                      args: { MODULE: %1$s, MODULE_DIR: %2$s }
                    image: concert-temporal/%1$s-worker
                """.formatted(n, moduleDir());
        StringBuilder services = new StringBuilder();
        if (eco.hasMachines()) {
            services.append("  # state machine workers (task queues sm-<smType>)\n  ").append(n).append("-worker:\n    profiles: [")
                    .append(n).append("]\n").append(build).append(env.formatted(""));
        }
        if (eco.hasEvents()) {
            String domains = "      " + envSuffix() + "_EVENT_DOMAINS: ${" + envSuffix() + "_EVENT_DOMAINS:-" + String.join(",", eco.domains())
                    + "}\n";
            services.append(eco.hasMachines() ? "\n" : "").append("  # event-style handlers (task queues ")
                    .append(String.join(", ", eco.domains().stream().map(d -> "ev-" + d).toList())).append("), same image\n  ")
                    .append(n).append("-event-worker:\n    profiles: [").append(n).append("]\n").append(build)
                    .append("    entrypoint: [\"/app/bin/ecosystem-event-worker\"]\n").append(env.formatted(domains));
        }
        return """
                # GENERATED by ./generate-concert-ecosystem -- do not edit: regenerated on every run.
                # Ecosystem "%1$s" as a compose override: its worker(s) (profile %1$s) and its roots in the analytics sinks.
                #   ./deploy-concert-ecosystem %1$s [--store postgres|dynamo|spanner] [--no-analytics]
                # or by hand:
                #   docker compose -f docker-compose.yml -f %2$s/compose.yml --profile %1$s up -d --build
                # The sinks add MODELS_DIR_%3$s / SINK_ROOTS_%3$s to their MODELS_DIR / SINK_ROOTS, so several ecosystem
                # overrides can be combined (-f ... -f ...).
                services:
                %5$s
                  sink-duckdb:
                    environment:
                      MODELS_DIR_%3$s: /models-eco/%1$s
                      SINK_ROOTS_%3$s: %4$s
                    volumes:
                      - ./%2$s/src/main/pure:/models-eco/%1$s:ro

                  sink-clickhouse:
                    environment:
                      MODELS_DIR_%3$s: /models-eco/%1$s
                      SINK_ROOTS_%3$s: %4$s
                    volumes:
                      - ./%2$s/src/main/pure:/models-eco/%1$s:ro

                  # concert.py loads app.d/ecosystems/%1$s.py only when this is set
                  deephaven:
                    environment:
                      CONCERT_ECOSYSTEM_%3$s: "on"
                """.formatted(n, moduleDir(), envSuffix(), sinkRoots(), services.toString().stripTrailing() + "\n");
    }

    // ---- Deephaven ----

    /** Deephaven columns of a root: to-one primitives and enums, and those of to-one value classes one level down. */
    List<String[]> deephavenColumns(MachineDecl m) {
        return deephavenColumns(m.root());
    }

    /** Deephaven columns of a class (a machine's root or a keyed-state class). */
    List<String[]> deephavenColumns(ClassDef root) {
        List<String[]> out = new ArrayList<>();
        for (PropertyDef p : model.allProperties(root)) {
            if (!p.multiplicity().isToOne()) {
                continue;
            }
            if (model.isClass(p.type())) {
                ClassDef value = model.findClass(p.type().name()).orElseThrow();
                for (PropertyDef q : model.allProperties(value)) {
                    String kind = kind(q);
                    if (q.multiplicity().isToOne() && kind != null) {
                        out.add(new String[] {column(Ecosystem.pascal(p.name()) + Ecosystem.pascal(q.name())),
                                "/model/" + p.name() + "/" + q.name(), kind});
                    }
                }
                continue;
            }
            String kind = kind(p);
            if (kind != null) {
                out.add(new String[] {column(Ecosystem.pascal(p.name())), "/model/" + p.name(), kind});
            }
        }
        return out;
    }

    private static String column(String name) {
        return DH_SYSTEM.contains(name) ? "Model" + name : name;
    }

    private String kind(PropertyDef p) {
        if (model.isEnum(p.type())) {
            return "string";
        }
        if (!p.type().primitive()) {
            return null;
        }
        PrimitiveType t = p.type().primitiveType();
        return switch (t) {
            case STRING, STRICT_DATE, DATE -> "string";
            case INTEGER -> "long";
            case FLOAT, DECIMAL, NUMBER -> "double";
            case BOOLEAN -> "bool";
            case DATE_TIME -> "instant";
        };
    }

    String deephavenTable(MachineDecl m) {
        return py(eco.name()) + "_" + Ecosystem.rootTable(m.smType()) + "_latest";
    }

    private static String py(String s) {
        return s.replace('-', '_');
    }

    String deephaven() {
        String p = py(eco.name());
        StringBuilder sb = new StringBuilder();
        sb.append("# GENERATED by ./generate-concert-ecosystem -- do not edit: regenerated on every run.\n");
        sb.append("# Ecosystem \"").append(eco.name()).append("\" (from entity-snapshots):");
        if (eco.hasMachines()) {
            sb.append(" latest completed entity per root, completions per minute and state\n# distribution.");
        }
        if (eco.hasEvents()) {
            sb.append(" Event style: latest lifecycle row per event (by status, error queue, scheduled,\n"
                    + "# causation depth) and the latest document per keyed state.");
        }
        sb.append("\n# Loaded by concert.py, which exec()s every file in app.d/ecosystems with its\n");
        sb.append("# globals (consume, parse_instants, TYPES, agg, kc, dht) and exports the tables named in ECOSYSTEM_FIELDS.\n");
        sb.append("from deephaven import merge\n\n\n");
        sb.append("def _").append(p).append("_root(sm_type, columns):\n");
        sb.append("""
                    cols = {"EntityId": dht.string, "SmType": dht.string, "State": dht.string, "Version": dht.int64,
                            "CreatedAtText": dht.string, "CompletedAtText": dht.string}
                    mapping = {"entityId": "EntityId", "smType": "SmType", "state": "State", "version": "Version",
                               "createdAt": "CreatedAtText", "completedAt": "CompletedAtText"}
                    instants = ["CreatedAt", "CompletedAt"]
                    for column, pointer, kind in columns:
                        if kind == "instant":
                            instants.append(column)
                            column, kind = column + "Text", "string"
                        cols[column] = TYPES[kind]
                        mapping[pointer] = column
                    raw = consume("entity-snapshots", cols, mapping, kc.TableType.append()).where(f"SmType == `{sm_type}`")
                    latest = raw.agg_by(agg.sorted_last("Version", [c for c in raw.column_names if c != "EntityId"]), by=["EntityId"])
                    return parse_instants(latest, instants).update(
                        "LatencyMs = (isNull(CreatedAt) || isNull(CompletedAt)) ? NULL_LONG : diffMillis(CreatedAt, CompletedAt)")


                """);
        List<String> tables = new ArrayList<>();
        for (MachineDecl m : eco.machines()) {
            String t = deephavenTable(m);
            tables.add(t);
            sb.append(t).append(" = _").append(p).append("_root(\"").append(m.smType()).append("\", [\n");
            for (String[] c : deephavenColumns(m)) {
                sb.append("    (\"").append(c[0]).append("\", \"").append(c[1]).append("\", \"").append(c[2]).append("\"),\n");
            }
            sb.append("])\n");
        }
        List<String> fields = new ArrayList<>(tables);
        if (eco.hasMachines()) {
            String common = "[\"EntityId\", \"SmType\", \"State\", \"Version\", \"CreatedAt\", \"CompletedAt\", \"LatencyMs\"]";
            sb.append("\n").append(p).append("_latest = merge([").append(String.join(", ", tables.stream().map(t -> t + ".view(" + common + ")").toList()))
                    .append("])\n");
            sb.append(p).append("_state_distribution = ").append(p).append("_latest.count_by(\"Entities\", by=[\"SmType\", \"State\"]).sort([\"SmType\", \"State\"])\n");
            sb.append(p).append("_completions_per_minute = ").append(p).append("_latest.where(\"!isNull(CompletedAt)\") \\\n")
                    .append("    .update(\"Minute = lowerBin(CompletedAt, MINUTE)\") \\\n")
                    .append("    .count_by(\"Completions\", by=[\"Minute\", \"SmType\"]).sort_descending([\"Minute\"])\n");
            fields.addAll(List.of(p + "_latest", p + "_state_distribution", p + "_completions_per_minute"));
        }
        if (eco.hasEvents()) {
            sb.append("""

                    # ---- event style: lifecycle rows (evt_*, one per event, latest status) and keyed-state documents (st_*)
                    def _%1$s_events(sm_types):
                        cols = {"EntityId": dht.string, "SmType": dht.string, "Status": dht.string, "Version": dht.int64,
                                "CreatedAtText": dht.string, "UpdatedAtText": dht.string, "EventId": dht.string,
                                "EventType": dht.string, "Domain": dht.string, "Outcome": dht.string, "Error": dht.string,
                                "Attempts": dht.int64, "Retries": dht.int64, "ParentEventId": dht.string, "CausationRoot": dht.string,
                                "Depth": dht.int64, "ProcessorKey": dht.string, "ScheduledAtMs": dht.int64}
                        mapping = {"entityId": "EntityId", "smType": "SmType", "state": "Status", "version": "Version",
                                   "createdAt": "CreatedAtText", "completedAt": "UpdatedAtText", "/model/eventId": "EventId",
                                   "/model/eventType": "EventType", "/model/domain": "Domain", "/model/outcome": "Outcome",
                                   "/model/error": "Error", "/model/attempts": "Attempts", "/model/retries": "Retries",
                                   "/model/parentEventId": "ParentEventId", "/model/causationRoot": "CausationRoot",
                                   "/model/depth": "Depth", "/model/processorKey": "ProcessorKey", "/model/scheduledAt": "ScheduledAtMs"}
                        raw = consume("entity-snapshots", cols, mapping, kc.TableType.append()) \\
                            .where("SmType in " + ", ".join(f"`{t}`" for t in sm_types))
                        latest = raw.agg_by(agg.sorted_last("Version", [c for c in raw.column_names if c != "EntityId"]), by=["EntityId"])
                        return parse_instants(latest, ["CreatedAt", "UpdatedAt"]).update([
                            "ScheduledAt = isNull(ScheduledAtMs) ? null : epochMillisToInstant(ScheduledAtMs)",
                            "AgeMs = isNull(CreatedAt) || isNull(UpdatedAt) ? NULL_LONG : diffMillis(CreatedAt, UpdatedAt)"])


                    """.formatted(p));
            sb.append(p).append("_events_latest = _").append(p).append("_events([")
                    .append(String.join(", ", eco.events().stream().map(e -> "\"" + e.smType() + "\"").toList())).append("])\n");
            sb.append(p).append("_events_by_status = ").append(p).append("_events_latest.count_by(\"Events\", by=[\"Domain\", \"EventType\", \"Status\"])")
                    .append(".sort([\"Domain\", \"EventType\", \"Status\"])\n");
            sb.append(p).append("_event_errors = ").append(p).append("_events_latest.where(\"Status in `ERROR_BLOCKING`, `ERROR_NON_BLOCKING`\")")
                    .append(".sort_descending([\"UpdatedAt\"])\n");
            sb.append(p).append("_events_scheduled = ").append(p).append("_events_latest.where(\"Status == `SCHEDULED`\").sort([\"ScheduledAt\"])\n");
            sb.append(p).append("_causation_depth = ").append(p).append("_events_latest.agg_by([agg.count_(\"Events\"), agg.max_(\"MaxDepth = Depth\"),\n")
                    .append("    agg.min_(\"Started = CreatedAt\"), agg.max_(\"LastUpdate = UpdatedAt\")], by=[\"CausationRoot\"]).sort_descending([\"LastUpdate\"])\n");
            fields.addAll(List.of(p + "_events_latest", p + "_events_by_status", p + "_event_errors", p + "_events_scheduled",
                    p + "_causation_depth"));
            for (EventDecl.StateDecl st : eco.states()) {
                String t = stateTable(st);
                fields.add(t);
                sb.append(t).append(" = _").append(p).append("_root(\"").append(st.smType()).append("\", [\n");
                for (String[] c : deephavenColumns(st.cls())) {
                    sb.append("    (\"").append(c[0]).append("\", \"").append(c[1]).append("\", \"").append(c[2]).append("\"),\n");
                }
                sb.append("])\n");
            }
        }
        sb.append("\nECOSYSTEM_FIELDS = {\n");
        for (String t : fields) {
            sb.append("    \"").append(t).append("\": ").append(t).append(",\n");
        }
        sb.append("}\n");
        return sb.toString();
    }

    /** Deephaven table of a keyed-state type: latest document per key. */
    String stateTable(EventDecl.StateDecl st) {
        return py(eco.name()) + "_" + st.table() + "_latest";
    }

    List<String> deephavenFields() {
        String p = py(eco.name());
        List<String> out = new ArrayList<>(eco.machines().stream().map(this::deephavenTable).toList());
        if (eco.hasMachines()) {
            out.addAll(List.of(p + "_latest", p + "_state_distribution", p + "_completions_per_minute"));
        }
        if (eco.hasEvents()) {
            out.addAll(List.of(p + "_events_latest", p + "_events_by_status", p + "_event_errors", p + "_events_scheduled",
                    p + "_causation_depth"));
            eco.states().forEach(st -> out.add(stateTable(st)));
        }
        return out;
    }

    // ---- scripts ----

    String sendScript() {
        StringBuilder usage = new StringBuilder();
        if (eco.hasMachines()) {
            usage.append("#   ./showcases/%1$s/send <smType> <eventType> <instanceKey> [payload.json | - | '{json}']\n"
                    + "#     (no payload: samples/<smType>/<eventType>.json)\n");
        }
        if (eco.hasEvents()) {
            usage.append("#   ./showcases/%1$s/send <EventType> [payload.json | - | '{json}'] [--at +5m | 2026-01-15T10:00:00Z] [--id ID]\n"
                    + "#     (no payload: samples/events/<EventType>.json; --at: SCHEDULED until then)\n");
        }
        return ("""
                #!/usr/bin/env bash
                # GENERATED by ./generate-concert-ecosystem -- regenerated on every run.
                # Send one %1$s event to Kinesis (concert-events), lock keys rendered from the payload:
                """ + usage + """
                # ./showcases/%1$s/send list shows the event types.
                set -euo pipefail
                here=$(cd "$(dirname "$0")" && pwd)
                if [ "${1:-}" = "list" ]; then
                  exec "$here/../../scripts/ecosystem-events.sh" %1$s list
                fi
                exec "$here/../../scripts/ecosystem-events.sh" %1$s send "$@"
                """).formatted(eco.name());
    }

    String sendFlowScript() {
        String dirs = (eco.hasMachines() ? "\"$here\"/samples/flows/*.json " : "") + (eco.hasEvents() ? "\"$here\"/samples/event-flows/*.json" : "");
        return """
                #!/usr/bin/env bash
                # GENERATED by ./generate-concert-ecosystem -- regenerated on every run.
                # Send the events of a flow file in order (default 500 ms apart):
                #   ./showcases/%1$s/send-flow <flow.json> [--delay-ms N]
                #   ./showcases/%1$s/send-flow all        (every flow under samples/)
                set -euo pipefail
                here=$(cd "$(dirname "$0")" && pwd)
                if [ "${1:-}" = "all" ]; then
                  shift
                  for f in %2$s; do
                    [ -f "$f" ] || continue
                    "$here/../../scripts/ecosystem-events.sh" %1$s flow "$f" "$@"
                  done
                  exit 0
                fi
                exec "$here/../../scripts/ecosystem-events.sh" %1$s flow "$@"
                """.formatted(eco.name(), dirs.strip());
    }

    // ---- manifest ----

    ObjectNode manifest(String modelsDir) {
        JsonNodeFactory f = JsonNodeFactory.instance;
        ObjectNode o = f.objectNode();
        o.put("name", eco.name());
        o.put("package", eco.javaPackage());
        o.put("modelsDir", modelsDir);
        o.put("module", moduleDir());
        if (eco.hasMachines()) {
            o.put("service", eco.name() + "-worker");
        }
        if (eco.hasEvents()) {
            o.put("eventService", eco.name() + "-event-worker");
        }
        o.put("profile", eco.name());
        ArrayNode files = o.putArray("files");
        eco.files().forEach(files::add);
        ArrayNode roots = o.putArray("roots");
        for (MachineDecl m : eco.machines()) {
            ObjectNode r = roots.addObject();
            r.put("smType", m.smType());
            r.put("rootClass", m.root().qualifiedName());
            r.put("table", Ecosystem.rootTable(m.smType()));
            r.put("deephavenTable", deephavenTable(m));
            r.put("initial", m.initial());
            ArrayNode terminal = r.putArray("terminal");
            m.terminal().forEach(terminal::add);
            ArrayNode events = r.putArray("events");
            m.eventTypes().forEach(events::add);
            r.put("sampleKey", Ecosystem.sampleKey(m));
            r.put("happyPath", "samples/flows/" + m.smType() + "-happy-path.json");
        }
        if (eco.hasEvents()) {
            ArrayNode domains = o.putArray("domains");
            eco.domains().forEach(domains::add);
            ArrayNode events = o.putArray("events");
            for (EventDecl e : eco.events()) {
                ObjectNode r = events.addObject();
                r.put("eventType", e.name());
                r.put("domain", e.domain());
                r.put("payloadClass", e.cls().qualifiedName());
                r.put("smType", e.smType());
                r.put("table", e.table());
                ArrayNode locks = r.putArray("locks");
                e.locks().forEach(locks::add);
                r.put("onError", e.onError());
                r.put("maxAttempts", e.maxAttempts());
                ArrayNode emits = r.putArray("emits");
                e.emits().forEach(emits::add);
                r.put("handler", e.handlerClass());
                r.put("sample", "samples/events/" + e.name() + ".json");
            }
            ArrayNode states = o.putArray("states");
            for (EventDecl.StateDecl st : eco.states()) {
                ObjectNode r = states.addObject();
                r.put("name", st.name());
                r.put("stateClass", st.cls().qualifiedName());
                r.put("smType", st.smType());
                r.put("table", st.table());
                if (st.keyTemplate() != null) {
                    r.put("key", st.keyTemplate());
                }
                r.put("deephavenTable", stateTable(st));
            }
            ArrayNode flows = o.putArray("eventFlows");
            new SampleGenerator(eco).rootEvents().forEach(e -> flows.add("samples/event-flows/" + e.name() + "-flow.json"));
        }
        ArrayNode dh = o.putArray("deephavenTables");
        deephavenFields().forEach(dh::add);
        return o;
    }

    // ---- README ----

    String readme(SampleGenerator samples) {
        String n = eco.name();
        String mod = "showcases/" + n;
        StringBuilder sb = new StringBuilder();
        sb.append("<!-- GENERATED by ./generate-concert-ecosystem -- do not edit: regenerated on every run. -->\n");
        sb.append("# ").append(n).append(" ecosystem\n\n");
        String declared = eco.hasMachines() && eco.hasEvents()
                ? "whose state machines are declared with the `concert::sm` profile and event types with `concert::event`"
                : eco.hasMachines() ? "whose state machines are declared with the `concert::sm` profile"
                : "whose event types and keyed states are declared with the `concert::event` profile";
        sb.append("Generated from the Pure models in `").append(eco.files().size()).append("` file(s) (")
                .append(String.join(", ", eco.files().stream().map(x -> "`" + x + "`").toList()))
                .append("), ").append(declared).append(". Java package `").append(eco.javaPackage()).append("`.\n\n");
        if (eco.hasMachines()) {
            machinesReadme(sb, samples);
        }
        if (eco.hasEvents()) {
            eventsReadme(sb, samples);
        }
        String pascal = eco.pascalName();
        sb.append("\n## Files\n\n| file | owner |\n|---|---|\n");
        sb.append("| `src/main/pure/*.pure` | copies of the models dir (regenerated); `src/main/pure/concert/concert.pure` is the built-in profile |\n");
        if (eco.hasMachines()) {
            sb.append("| `src/main/java/.../<Root>Spec.java` | regenerated: states, transitions, payload types, terminal states, lock templates |\n");
            sb.append("| `src/main/java/.../<Root>Machine.java` | **yours**: generated once, never overwritten (`--force` backs it up first) |\n");
            sb.append("| `src/main/java/.../").append(pascal).append("Machines.java`, `").append(pascal).append("WorkerMain.java` | regenerated |\n");
            sb.append("| `src/test/java/.../").append(pascal).append("GeneratedTest.java` | regenerated: samples bind to their classes; happy paths reach terminal states through your machines |\n");
        }
        if (eco.hasEvents()) {
            sb.append("| `src/main/java/.../<Domain>EventCatalog.java` | regenerated: event types (domain, lock templates, onError, attempts, emits) and keyed states, `EventCatalog` SPI |\n");
            sb.append("| `src/main/java/.../<Event>Handler.java` | **yours**: generated once, never overwritten (`--force` backs it up first) |\n");
            sb.append("| `src/main/java/.../").append(pascal).append("EventTypes.java`, `").append(pascal).append("EventWorkerMain.java` | regenerated: catalogs, handlers per domain, diagrams; the event worker |\n");
            sb.append("| `src/test/java/.../").append(pascal).append("EventFlowsTest.java` | regenerated: event samples bind; every event flow settles through your handlers on the real lock chain |\n");
            sb.append("| `samples/events/<EventType>.json`, `samples/event-flows/*.json` | regenerated unless you edited them; add your own flows (optional `\"expect\"`) |\n");
        }
        sb.append("| `src/main/java/.../").append(pascal).append("Models.java`, `").append(pascal).append("Events.java` | regenerated: POJOs; the Kinesis sender |\n");
        if (eco.hasMachines()) {
            sb.append("| `samples/<smType>/<event>.json`, `samples/flows/*.json` | regenerated unless you edited them (hashes in `ecosystem.json`) |\n");
        }
        sb.append("| `compose.yml`, `send`, `send-flow`, `build.gradle.kts`, `README.md`, `ecosystem.json` | regenerated (`extra.gradle.kts` is yours) |\n");
        sb.append("| `infra/deephaven/app.d/ecosystems/").append(n).append(".py` | regenerated: Deephaven tables of this ecosystem |\n");
        List<String> svc = new ArrayList<>();
        if (eco.hasMachines()) {
            svc.add("`" + n + "-worker`");
        }
        if (eco.hasEvents()) {
            svc.add("`" + n + "-event-worker`");
        }
        String services = "service" + (svc.size() > 1 ? "s " : " ") + String.join(" and ", svc);
        sb.append("""

                ## Deploy

                ```bash
                ./generate-concert-ecosystem <models-dir> --name %1$s      # after editing the models
                ./deploy-concert-ecosystem %1$s --store spanner             # or postgres | dynamo; --no-analytics
                ```

                `deploy` builds, starts the stack with this module's `compose.yml` override (%2$s, profile
                `%1$s`), re-provisions ClickHouse, restarts the DuckDB sink and Deephaven so the new roots appear, and prints
                the links. The trace UI finds the machines and event catalogs through their SPIs (no edits needed).

                ## Send events

                ```bash
                ./%3$s/send list
                """.formatted(n, services, mod));
        if (eco.hasMachines()) {
            sb.append("./").append(mod).append("/send <smType> <event> <instanceKey> [payload.json]   # default payload: samples/<smType>/<event>.json\n");
            sb.append("./").append(mod).append("/send-flow ").append(mod).append("/samples/flows/<smType>-happy-path.json\n");
        }
        if (eco.hasEvents()) {
            sb.append("./").append(mod).append("/send <EventType> [payload.json] [--at +5m|ISO]     # default payload: samples/events/<EventType>.json\n");
            sb.append("./").append(mod).append("/send-flow ").append(mod).append("/samples/event-flows/<EventType>-flow.json\n");
            sb.append("scripts/events.sh list errors        # ERROR_BLOCKING / ERROR_NON_BLOCKING; retry | skip <eventId>\n");
        }
        sb.append("./").append(mod).append("/send-flow all\n```\n");
        sb.append("\nExample queries (DuckDB: trace UI → Analytics → DuckDB; ClickHouse: add `FINAL`):\n\n```sql\n");
        for (MachineDecl m : eco.machines()) {
            sb.append("SELECT sm_state, count(*) FROM ").append(Ecosystem.rootTable(m.smType())).append(" GROUP BY sm_state;\n");
        }
        for (EventDecl e : eco.events()) {
            sb.append("SELECT status, count(*), avg(attempts) FROM ").append(e.table()).append(" GROUP BY status;\n");
        }
        if (eco.hasEvents()) {
            EventDecl e = eco.events().getFirst();
            sb.append("SELECT event_id, status, error, attempts, parent_event_id FROM ").append(e.table())
                    .append(" WHERE status LIKE 'ERROR_%';\n");
        }
        for (EventDecl.StateDecl st : eco.states()) {
            sb.append("SELECT * FROM ").append(st.table()).append(" ORDER BY completed_at DESC LIMIT 10;\n");
        }
        sb.append("```\n");
        return sb.toString();
    }

    private void machinesReadme(StringBuilder sb, SampleGenerator samples) {
        sb.append("| smType | root class | states | terminal | events | analytics table |\n|---|---|---|---|---|---|\n");
        for (MachineDecl m : eco.machines()) {
            sb.append("| `").append(m.smType()).append("` | `").append(m.root().qualifiedName()).append("` | ").append(m.states().size())
                    .append(" | ").append(String.join(", ", m.terminal())).append(" | ").append(String.join(", ", m.eventTypes()))
                    .append(" | `").append(Ecosystem.rootTable(m.smType())).append("` |\n");
        }
        sb.append("\n## State machines\n");
        for (MachineDecl m : eco.machines()) {
            sb.append("\n### ").append(m.smType()).append(" (`").append(m.root().qualifiedName()).append("`)\n\n");
            sb.append("```mermaid\nstateDiagram-v2\n    [*] --> ").append(m.initial()).append('\n');
            for (MachineDecl.Transition t : m.transitions()) {
                sb.append("    ").append(t.from()).append(" --> ").append(t.to()).append(" : ").append(t.eventType()).append('\n');
            }
            for (String s : m.terminal()) {
                sb.append("    ").append(s).append(" --> [*]\n");
            }
            sb.append("```\n\n| event | from → to | payload | lock keys (besides `").append(m.smType()).append(":<key>`) |\n|---|---|---|---|\n");
            for (MachineDecl.Transition t : m.transitions()) {
                sb.append("| `").append(t.eventType()).append("` | ").append(t.from()).append(" → ").append(t.to()).append(" | ")
                        .append(t.payloadClass() == null ? "–" : "`" + t.payloadClass() + "`").append(" | ")
                        .append(String.join(", ", m.locks().get(t.eventType()).stream().map(x -> "`" + x + "`").toList())).append(" |\n");
            }
            sb.append("\nData: `").append(m.root().qualifiedName()).append("`");
            if (m.idProperty() != null) {
                sb.append(", `").append(m.idProperty()).append("` = instance key");
            }
            if (m.statusProperty() != null) {
                sb.append(", `").append(m.statusProperty()).append("` = state");
            }
            sb.append(". Happy path (`samples/flows/").append(m.smType()).append("-happy-path.json`, key `").append(Ecosystem.sampleKey(m))
                    .append("`): ").append(samples.happyPath(m).path("description").asText()).append(".\n");
        }
    }

    private void eventsReadme(StringBuilder sb, SampleGenerator samples) {
        EventSources ev = new EventSources(eco);
        sb.append("\n## Event types\n\n");
        sb.append("Every event goes `NEW → DONE` (or `SCHEDULED` first when sent with `--at`, `ERROR_BLOCKING` / `ERROR_NON_BLOCKING`\n"
                + "on failure); its handler (`<Event>Handler`, yours) runs with all of the event's lock keys held and may save keyed\n"
                + "state and emit follow-up events. Lifecycle rows go to the `evt_*` tables, state documents to `st_*`.\n\n");
        sb.append("```mermaid\n").append(ev.flowMermaid()).append("```\n\n");
        sb.append("| event type | domain | lock keys | on error | attempts | emits | handler | analytics table |\n|---|---|---|---|---|---|---|---|\n");
        for (EventDecl e : eco.events()) {
            sb.append("| `").append(e.name()).append("` | `").append(e.domain()).append("` | ")
                    .append(e.locks().isEmpty() ? "`" + e.domain() + ":<eventId>`" : String.join(", ", e.locks().stream().map(x -> "`" + x + "`").toList()))
                    .append(" | ").append(e.onError()).append(" | ").append(e.maxAttempts()).append(" | ")
                    .append(e.emits().isEmpty() ? "–" : String.join(", ", e.emits())).append(" | `").append(e.handlerClass()).append("` | `")
                    .append(e.table()).append("` |\n");
        }
        if (!eco.states().isEmpty()) {
            sb.append("\n| keyed state | class | key | analytics table |\n|---|---|---|---|\n");
            for (EventDecl.StateDecl st : eco.states()) {
                sb.append("| `").append(st.name()).append("` | `").append(st.cls().qualifiedName()).append("` | ")
                        .append(st.keyTemplate() == null ? "(given to `ctx.save`)" : "`" + st.keyTemplate() + "`").append(" | `")
                        .append(st.table()).append("` |\n");
            }
        }
        sb.append("\nFlows (`samples/event-flows/`, from `concert::event.emits`):\n\n");
        for (EventDecl root : samples.rootEvents()) {
            sb.append("- `").append(root.name()).append("-flow.json`: ").append(samples.chain(root.name(), new HashSet<>())).append("\n");
        }
    }
}
