package io.concert.ecosystem;

import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.JsonNodeFactory;
import com.fasterxml.jackson.databind.node.ObjectNode;
import io.concert.model.pure.ClassDef;
import io.concert.model.pure.PrimitiveType;
import io.concert.model.pure.PropertyDef;
import io.concert.model.pure.ResolvedModel;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Set;

/** The non-Java files of a generated module: build, compose, Deephaven snippet, README, manifest, scripts. */
final class ProjectFiles {

    private static final Set<String> DH_SYSTEM = Set.of("EntityId", "SmType", "State", "Version", "CreatedAt", "CompletedAt",
            "LatencyMs", "CreatedAtText", "CompletedAtText");

    private final Ecosystem eco;
    private final JavaSources java;
    private final ResolvedModel model;

    ProjectFiles(Ecosystem eco, JavaSources java) {
        this.eco = eco;
        this.java = java;
        this.model = eco.model();
    }

    String moduleDir() {
        return "showcases/" + eco.name();
    }

    String envSuffix() {
        return eco.name().toUpperCase(Locale.ROOT).replace('-', '_');
    }

    String sinkRoots() {
        return String.join(",", eco.machines().stream().map(m -> m.smType() + ":" + m.root().qualifiedName()).toList());
    }

    // ---- build.gradle.kts ----

    String build() {
        String main = java.pkg() + "." + java.workerMainClass();
        String events = java.pkg() + "." + java.eventsClass();
        return """
                // GENERATED by ./generate-concert-ecosystem -- do not edit: regenerated on every run. Put extra build
                // logic in extra.gradle.kts next to this file (applied below when present; use string configuration
                // names there, e.g. dependencies { "testImplementation"(project(":x")) }).
                //
                // Ecosystem "%1$s": the state machines declared in src/main/pure (concert::sm profile). bin/%1$s and
                // bin/ecosystem-worker run the workers, bin/events sends events (./showcases/%1$s/send).
                plugins { application }

                dependencies {
                    implementation(project(":worker-sdk"))
                    // POJOs generated from src/main/pure (the root build passes the directory to the processor)
                    implementation(project(":model-runtime"))
                    annotationProcessor(project(":model-codegen"))
                    // %2$s: KinesisClients
                    implementation(project(":orchestration"))
                    implementation(platform(libs.aws.bom))
                    implementation(libs.aws.kinesis)
                    // STORE_KIND=dynamo|spanner backends, discovered via ServiceLoader
                    runtimeOnly(project(":store-dynamo"))
                    runtimeOnly(project(":store-spanner"))
                    runtimeOnly(libs.slf4j.simple)

                    testImplementation(libs.temporal.testing)
                    testImplementation(platform(libs.junit.bom))
                    testImplementation(libs.junit.jupiter)
                    testRuntimeOnly(libs.junit.launcher)
                }

                val jvmArgs = listOf("-XX:+UseZGC", "-XX:+UseCompactObjectHeaders")

                application {
                    mainClass.set("%3$s")
                    applicationDefaultJvmArgs = jvmArgs
                }

                // bin/ecosystem-worker: the same worker under a fixed name (the generic showcase-worker Docker target)
                val workerScripts = tasks.register<CreateStartScripts>("workerStartScripts") {
                    mainClass.set("%3$s")
                    applicationName = "ecosystem-worker"
                    defaultJvmOpts = jvmArgs
                    classpath = tasks.startScripts.get().classpath
                    outputDir = layout.buildDirectory.dir("worker-scripts").get().asFile
                }

                // bin/events: the event sender
                val eventScripts = tasks.register<CreateStartScripts>("eventStartScripts") {
                    mainClass.set("%4$s")
                    applicationName = "events"
                    defaultJvmOpts = listOf("-XX:+UseSerialGC", "-XX:TieredStopAtLevel=1")
                    classpath = tasks.startScripts.get().classpath
                    outputDir = layout.buildDirectory.dir("event-scripts").get().asFile
                }

                distributions.main {
                    contents {
                        from(workerScripts) { into("bin") }
                        from(eventScripts) { into("bin") }
                    }
                }

                tasks.test {
                    systemProperty("ecosystem.samples", layout.projectDirectory.dir("samples").asFile.absolutePath)
                    inputs.dir(layout.projectDirectory.dir("samples")).withPathSensitivity(PathSensitivity.RELATIVE)
                }

                if (file("extra.gradle.kts").isFile) {
                    apply(from = "extra.gradle.kts")
                }
                """.formatted(eco.name(), java.eventsClass(), main, events);
    }

    // ---- compose.yml ----

    String compose() {
        String n = eco.name();
        return """
                # GENERATED by ./generate-concert-ecosystem -- do not edit: regenerated on every run.
                # Ecosystem "%1$s" as a compose override: its worker (profile %1$s) and its roots in the analytics sinks.
                #   ./deploy-concert-ecosystem %1$s [--store postgres|dynamo|spanner] [--no-analytics]
                # or by hand:
                #   docker compose -f docker-compose.yml -f %2$s/compose.yml --profile %1$s up -d --build
                # The sinks add MODELS_DIR_%3$s / SINK_ROOTS_%3$s to their MODELS_DIR / SINK_ROOTS, so several ecosystem
                # overrides can be combined (-f ... -f ...).
                services:
                  %1$s-worker:
                    profiles: [%1$s]
                    build:
                      context: .
                      target: showcase-worker
                      args: { MODULE: %1$s, MODULE_DIR: %2$s }
                    image: concert-temporal/%1$s-worker
                    depends_on:
                      temporal-init: { condition: service_completed_successfully }
                      localstack: { condition: service_healthy }
                      coordinator: { condition: service_started }
                    environment:
                      STORE_KIND: ${STORE_KIND:-postgres}
                      TEMPORAL_ADDRESS: temporal:7233
                      KINESIS_ENDPOINT: http://localstack:4566
                      STORE_JDBC_URL: jdbc:postgresql://dsql:5432/concert
                      DYNAMO_ENDPOINT: http://localstack:4566
                      SPANNER_EMULATOR_HOST: spanner:9010
                      TRACE_SAMPLE: ${TRACE_SAMPLE:-1.0}
                      AWS_REGION: us-east-1
                      KAFKA_BOOTSTRAP: ${KAFKA_BOOTSTRAP-kafka:9092}
                      SINK_DUCKDB_URL: http://sink-duckdb:8090
                      STORE_INIT_SCHEMA: "false"
                      JAVA_OPTS: -XX:+UseZGC -XX:+UseCompactObjectHeaders -XX:MaxRAMPercentage=50
                    deploy: { resources: { limits: { memory: 1g } } }
                    restart: unless-stopped

                  sink-duckdb:
                    environment:
                      MODELS_DIR_%3$s: /models-eco/%1$s
                      SINK_ROOTS_%3$s: %4$s
                    volumes:
                      - ./%2$s/src/main/pure:/models-eco/%1$s:ro

                  sink-clickhouse:
                    environment:
                      MODELS_DIR_%3$s: /models-eco/%1$s
                      SINK_ROOTS_%3$s: %4$s
                    volumes:
                      - ./%2$s/src/main/pure:/models-eco/%1$s:ro

                  # concert.py loads app.d/ecosystems/%1$s.py only when this is set
                  deephaven:
                    environment:
                      CONCERT_ECOSYSTEM_%3$s: "on"
                """.formatted(n, moduleDir(), envSuffix(), sinkRoots());
    }

    // ---- Deephaven ----

    /** Deephaven columns of a root: to-one primitives and enums, and those of to-one value classes one level down. */
    List<String[]> deephavenColumns(MachineDecl m) {
        List<String[]> out = new ArrayList<>();
        for (PropertyDef p : model.allProperties(m.root())) {
            if (!p.multiplicity().isToOne()) {
                continue;
            }
            if (model.isClass(p.type())) {
                ClassDef value = model.findClass(p.type().name()).orElseThrow();
                for (PropertyDef q : model.allProperties(value)) {
                    String kind = kind(q);
                    if (q.multiplicity().isToOne() && kind != null) {
                        out.add(new String[] {column(Ecosystem.pascal(p.name()) + Ecosystem.pascal(q.name())),
                                "/model/" + p.name() + "/" + q.name(), kind});
                    }
                }
                continue;
            }
            String kind = kind(p);
            if (kind != null) {
                out.add(new String[] {column(Ecosystem.pascal(p.name())), "/model/" + p.name(), kind});
            }
        }
        return out;
    }

    private static String column(String name) {
        return DH_SYSTEM.contains(name) ? "Model" + name : name;
    }

    private String kind(PropertyDef p) {
        if (model.isEnum(p.type())) {
            return "string";
        }
        if (!p.type().primitive()) {
            return null;
        }
        PrimitiveType t = p.type().primitiveType();
        return switch (t) {
            case STRING, STRICT_DATE, DATE -> "string";
            case INTEGER -> "long";
            case FLOAT, DECIMAL, NUMBER -> "double";
            case BOOLEAN -> "bool";
            case DATE_TIME -> "instant";
        };
    }

    String deephavenTable(MachineDecl m) {
        return py(eco.name()) + "_" + Ecosystem.rootTable(m.smType()) + "_latest";
    }

    private static String py(String s) {
        return s.replace('-', '_');
    }

    String deephaven() {
        String p = py(eco.name());
        StringBuilder sb = new StringBuilder();
        sb.append("# GENERATED by ./generate-concert-ecosystem -- do not edit: regenerated on every run.\n");
        sb.append("# Ecosystem \"").append(eco.name()).append("\": latest completed entity per root (from entity-snapshots), completions\n");
        sb.append("# per minute and state distribution. Loaded by concert.py, which exec()s every file in app.d/ecosystems with its\n");
        sb.append("# globals (consume, parse_instants, TYPES, agg, kc, dht) and exports the tables named in ECOSYSTEM_FIELDS.\n");
        sb.append("from deephaven import merge\n\n\n");
        sb.append("def _").append(p).append("_root(sm_type, columns):\n");
        sb.append("""
                    cols = {"EntityId": dht.string, "SmType": dht.string, "State": dht.string, "Version": dht.int64,
                            "CreatedAtText": dht.string, "CompletedAtText": dht.string}
                    mapping = {"entityId": "EntityId", "smType": "SmType", "state": "State", "version": "Version",
                               "createdAt": "CreatedAtText", "completedAt": "CompletedAtText"}
                    instants = ["CreatedAt", "CompletedAt"]
                    for column, pointer, kind in columns:
                        if kind == "instant":
                            instants.append(column)
                            column, kind = column + "Text", "string"
                        cols[column] = TYPES[kind]
                        mapping[pointer] = column
                    raw = consume("entity-snapshots", cols, mapping, kc.TableType.append()).where(f"SmType == `{sm_type}`")
                    latest = raw.agg_by(agg.sorted_last("Version", [c for c in raw.column_names if c != "EntityId"]), by=["EntityId"])
                    return parse_instants(latest, instants).update(
                        "LatencyMs = (isNull(CreatedAt) || isNull(CompletedAt)) ? NULL_LONG : diffMillis(CreatedAt, CompletedAt)")


                """);
        List<String> tables = new ArrayList<>();
        for (MachineDecl m : eco.machines()) {
            String t = deephavenTable(m);
            tables.add(t);
            sb.append(t).append(" = _").append(p).append("_root(\"").append(m.smType()).append("\", [\n");
            for (String[] c : deephavenColumns(m)) {
                sb.append("    (\"").append(c[0]).append("\", \"").append(c[1]).append("\", \"").append(c[2]).append("\"),\n");
            }
            sb.append("])\n");
        }
        String common = "[\"EntityId\", \"SmType\", \"State\", \"Version\", \"CreatedAt\", \"CompletedAt\", \"LatencyMs\"]";
        sb.append("\n").append(p).append("_latest = merge([").append(String.join(", ", tables.stream().map(t -> t + ".view(" + common + ")").toList()))
                .append("])\n");
        sb.append(p).append("_state_distribution = ").append(p).append("_latest.count_by(\"Entities\", by=[\"SmType\", \"State\"]).sort([\"SmType\", \"State\"])\n");
        sb.append(p).append("_completions_per_minute = ").append(p).append("_latest.where(\"!isNull(CompletedAt)\") \\\n")
                .append("    .update(\"Minute = lowerBin(CompletedAt, MINUTE)\") \\\n")
                .append("    .count_by(\"Completions\", by=[\"Minute\", \"SmType\"]).sort_descending([\"Minute\"])\n\n");
        sb.append("ECOSYSTEM_FIELDS = {\n");
        for (String t : tables) {
            sb.append("    \"").append(t).append("\": ").append(t).append(",\n");
        }
        for (String t : List.of(p + "_latest", p + "_state_distribution", p + "_completions_per_minute")) {
            sb.append("    \"").append(t).append("\": ").append(t).append(",\n");
        }
        sb.append("}\n");
        return sb.toString();
    }

    List<String> deephavenFields() {
        String p = py(eco.name());
        List<String> out = new ArrayList<>(eco.machines().stream().map(this::deephavenTable).toList());
        out.addAll(List.of(p + "_latest", p + "_state_distribution", p + "_completions_per_minute"));
        return out;
    }

    // ---- scripts ----

    String sendScript() {
        return """
                #!/usr/bin/env bash
                # GENERATED by ./generate-concert-ecosystem -- regenerated on every run.
                # Send one %1$s event to Kinesis (concert-events), lock keys rendered from the payload:
                #   ./showcases/%1$s/send <smType> <eventType> <instanceKey> [payload.json | - | '{json}']
                # Without a payload, samples/<smType>/<eventType>.json is sent. ./showcases/%1$s/send list shows the events.
                set -euo pipefail
                here=$(cd "$(dirname "$0")" && pwd)
                if [ "${1:-}" = "list" ]; then
                  exec "$here/../../scripts/ecosystem-events.sh" %1$s list
                fi
                exec "$here/../../scripts/ecosystem-events.sh" %1$s send "$@"
                """.formatted(eco.name());
    }

    String sendFlowScript() {
        return """
                #!/usr/bin/env bash
                # GENERATED by ./generate-concert-ecosystem -- regenerated on every run.
                # Send the events of a flow file in order (default 500 ms apart):
                #   ./showcases/%1$s/send-flow <flow.json> [--delay-ms N]
                #   ./showcases/%1$s/send-flow all        (every samples/flows/*.json)
                set -euo pipefail
                here=$(cd "$(dirname "$0")" && pwd)
                if [ "${1:-}" = "all" ]; then
                  shift
                  for f in "$here"/samples/flows/*.json; do
                    "$here/../../scripts/ecosystem-events.sh" %1$s flow "$f" "$@"
                  done
                  exit 0
                fi
                exec "$here/../../scripts/ecosystem-events.sh" %1$s flow "$@"
                """.formatted(eco.name());
    }

    // ---- manifest ----

    ObjectNode manifest(String modelsDir) {
        JsonNodeFactory f = JsonNodeFactory.instance;
        ObjectNode o = f.objectNode();
        o.put("name", eco.name());
        o.put("package", eco.javaPackage());
        o.put("modelsDir", modelsDir);
        o.put("module", moduleDir());
        o.put("service", eco.name() + "-worker");
        o.put("profile", eco.name());
        ArrayNode files = o.putArray("files");
        eco.files().forEach(files::add);
        ArrayNode roots = o.putArray("roots");
        for (MachineDecl m : eco.machines()) {
            ObjectNode r = roots.addObject();
            r.put("smType", m.smType());
            r.put("rootClass", m.root().qualifiedName());
            r.put("table", Ecosystem.rootTable(m.smType()));
            r.put("deephavenTable", deephavenTable(m));
            r.put("initial", m.initial());
            ArrayNode terminal = r.putArray("terminal");
            m.terminal().forEach(terminal::add);
            ArrayNode events = r.putArray("events");
            m.eventTypes().forEach(events::add);
            r.put("sampleKey", Ecosystem.sampleKey(m));
            r.put("happyPath", "samples/flows/" + m.smType() + "-happy-path.json");
        }
        ArrayNode dh = o.putArray("deephavenTables");
        deephavenFields().forEach(dh::add);
        return o;
    }

    // ---- README ----

    String readme(SampleGenerator samples) {
        String n = eco.name();
        StringBuilder sb = new StringBuilder();
        sb.append("<!-- GENERATED by ./generate-concert-ecosystem -- do not edit: regenerated on every run. -->\n");
        sb.append("# ").append(n).append(" ecosystem\n\n");
        sb.append("Generated from the Pure models in `").append(eco.files().size()).append("` file(s) (")
                .append(String.join(", ", eco.files().stream().map(x -> "`" + x + "`").toList()))
                .append("), whose state machines are declared with the `concert::sm` profile. Java package `")
                .append(eco.javaPackage()).append("`.\n\n");
        sb.append("| smType | root class | states | terminal | events | analytics table |\n|---|---|---|---|---|---|\n");
        for (MachineDecl m : eco.machines()) {
            sb.append("| `").append(m.smType()).append("` | `").append(m.root().qualifiedName()).append("` | ").append(m.states().size())
                    .append(" | ").append(String.join(", ", m.terminal())).append(" | ").append(String.join(", ", m.eventTypes()))
                    .append(" | `").append(Ecosystem.rootTable(m.smType())).append("` |\n");
        }
        sb.append("\n## State machines\n");
        for (MachineDecl m : eco.machines()) {
            sb.append("\n### ").append(m.smType()).append(" (`").append(m.root().qualifiedName()).append("`)\n\n");
            sb.append("```mermaid\nstateDiagram-v2\n    [*] --> ").append(m.initial()).append('\n');
            for (MachineDecl.Transition t : m.transitions()) {
                sb.append("    ").append(t.from()).append(" --> ").append(t.to()).append(" : ").append(t.eventType()).append('\n');
            }
            for (String s : m.terminal()) {
                sb.append("    ").append(s).append(" --> [*]\n");
            }
            sb.append("```\n\n| event | from → to | payload | lock keys (besides `").append(m.smType()).append(":<key>`) |\n|---|---|---|---|\n");
            for (MachineDecl.Transition t : m.transitions()) {
                sb.append("| `").append(t.eventType()).append("` | ").append(t.from()).append(" → ").append(t.to()).append(" | ")
                        .append(t.payloadClass() == null ? "–" : "`" + t.payloadClass() + "`").append(" | ")
                        .append(String.join(", ", m.locks().get(t.eventType()).stream().map(x -> "`" + x + "`").toList())).append(" |\n");
            }
            sb.append("\nData: `").append(m.root().qualifiedName()).append("`");
            if (m.idProperty() != null) {
                sb.append(", `").append(m.idProperty()).append("` = instance key");
            }
            if (m.statusProperty() != null) {
                sb.append(", `").append(m.statusProperty()).append("` = state");
            }
            sb.append(". Happy path (`samples/flows/").append(m.smType()).append("-happy-path.json`, key `").append(Ecosystem.sampleKey(m))
                    .append("`): ").append(samples.happyPath(m).path("description").asText()).append(".\n");
        }
        sb.append("""

                ## Files

                | file | owner |
                |---|---|
                | `src/main/pure/*.pure` | copies of the models dir (regenerated); `src/main/pure/concert/concert.pure` is the built-in profile |
                | `src/main/java/.../<Root>Spec.java` | regenerated: states, transitions, payload types, terminal states, lock templates |
                | `src/main/java/.../<Root>Machine.java` | **yours**: generated once, never overwritten (`--force` backs it up first) |
                | `src/main/java/.../%1$sMachines.java`, `%1$sModels.java`, `%1$sWorkerMain.java`, `%1$sEvents.java` | regenerated |
                | `src/test/java/.../%1$sGeneratedTest.java` | regenerated: samples bind to their classes; happy paths reach terminal states through your machines |
                | `samples/<smType>/<event>.json`, `samples/flows/*.json` | regenerated unless you edited them (hashes in `ecosystem.json`) |
                | `compose.yml`, `send`, `send-flow`, `build.gradle.kts`, `README.md`, `ecosystem.json` | regenerated (`extra.gradle.kts` is yours) |
                | `infra/deephaven/app.d/ecosystems/%2$s.py` | regenerated: Deephaven tables of this ecosystem |

                ## Deploy

                ```bash
                ./generate-concert-ecosystem <models-dir> --name %2$s      # after editing the models
                ./deploy-concert-ecosystem %2$s --store spanner             # or postgres | dynamo; --no-analytics
                ```

                `deploy` builds, starts the stack with this module's `compose.yml` override (service `%2$s-worker`, profile
                `%2$s`), re-provisions ClickHouse, restarts the DuckDB sink and Deephaven so the new roots appear, and prints
                the links. The trace UI finds the machines through the `MachineCatalog` SPI (no edits needed).

                ## Send events

                ```bash
                ./showcases/%2$s/send list
                ./showcases/%2$s/send <smType> <event> <instanceKey> [payload.json]   # default payload: samples/<smType>/<event>.json
                ./showcases/%2$s/send-flow showcases/%2$s/samples/flows/<smType>-happy-path.json
                ./showcases/%2$s/send-flow all
                ```
                """.formatted(java.pkg().isEmpty() ? "" : eco.pascalName(), n));
        sb.append("\nExample queries (DuckDB: trace UI → Analytics → DuckDB; ClickHouse: add `FINAL`):\n\n```sql\n");
        for (MachineDecl m : eco.machines()) {
            sb.append("SELECT sm_state, count(*) FROM ").append(Ecosystem.rootTable(m.smType())).append(" GROUP BY sm_state;\n");
        }
        sb.append("```\n");
        return sb.toString();
    }
}
