// GENERATED by ./generate-concert-ecosystem -- do not edit: regenerated on every run. Put extra build
// logic in extra.gradle.kts next to this file (applied below when present; use string configuration
// names there, e.g. dependencies { "testImplementation"(project(":x")) }).
//
// Ecosystem "insurance": the state machines declared in src/main/pure (concert::sm profile).
// bin/ecosystem-worker runs the state machine workers, bin/events sends events (./showcases/insurance/send).
plugins { application }

dependencies {
    implementation(project(":worker-sdk"))
    // POJOs generated from src/main/pure (the root build passes the directory to the processor)
    implementation(project(":model-runtime"))
    annotationProcessor(project(":model-codegen"))
    // InsuranceEvents: KinesisClients; the generated tests run the real lock chain
    implementation(project(":orchestration"))
    implementation(platform(libs.aws.bom))
    implementation(libs.aws.kinesis)
    // STORE_KIND=dynamo|spanner backends, discovered via ServiceLoader
    runtimeOnly(project(":store-dynamo"))
    runtimeOnly(project(":store-spanner"))
    runtimeOnly(libs.slf4j.simple)

    testImplementation(libs.temporal.testing)
    testImplementation(platform(libs.junit.bom))
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly(libs.junit.launcher)
}

val jvmArgs = listOf("-XX:+UseZGC", "-XX:+UseCompactObjectHeaders")

application {
    mainClass.set("io.concert.eco.insurance.InsuranceWorkerMain")
    applicationDefaultJvmArgs = jvmArgs
}

// bin/ecosystem-worker: the state machine worker under a fixed name (the generic showcase-worker Docker target)
val workerScripts = tasks.register<CreateStartScripts>("workerStartScripts") {
    mainClass.set("io.concert.eco.insurance.InsuranceWorkerMain")
    applicationName = "ecosystem-worker"
    defaultJvmOpts = jvmArgs
    classpath = tasks.startScripts.get().classpath
    outputDir = layout.buildDirectory.dir("worker-scripts").get().asFile
}

// bin/events: the event sender
val eventScripts = tasks.register<CreateStartScripts>("eventStartScripts") {
    mainClass.set("io.concert.eco.insurance.InsuranceEvents")
    applicationName = "events"
    defaultJvmOpts = listOf("-XX:+UseSerialGC", "-XX:TieredStopAtLevel=1")
    classpath = tasks.startScripts.get().classpath
    outputDir = layout.buildDirectory.dir("event-scripts").get().asFile
}

distributions.main {
    contents {
        from(workerScripts) { into("bin") }
        from(eventScripts) { into("bin") }
    }
}

tasks.test {
    systemProperty("ecosystem.samples", layout.projectDirectory.dir("samples").asFile.absolutePath)
    // the in-memory Temporal server cancels still-running workflows on close: keep its warnings out of the build
    systemProperty("org.slf4j.simpleLogger.log.io.temporal.internal", "error")
    inputs.dir(layout.projectDirectory.dir("samples")).withPathSensitivity(PathSensitivity.RELATIVE)
}

if (file("extra.gradle.kts").isFile) {
    apply(from = "extra.gradle.kts")
}
