# GENERATED by ./generate-concert-ecosystem -- do not edit: regenerated on every run.
# Ecosystem "insurance": latest completed entity per root (from entity-snapshots), completions
# per minute and state distribution. Loaded by concert.py, which exec()s every file in app.d/ecosystems with its
# globals (consume, parse_instants, TYPES, agg, kc, dht) and exports the tables named in ECOSYSTEM_FIELDS.
from deephaven import merge


def _insurance_root(sm_type, columns):
    cols = {"EntityId": dht.string, "SmType": dht.string, "State": dht.string, "Version": dht.int64,
            "CreatedAtText": dht.string, "CompletedAtText": dht.string}
    mapping = {"entityId": "EntityId", "smType": "SmType", "state": "State", "version": "Version",
               "createdAt": "CreatedAtText", "completedAt": "CompletedAtText"}
    instants = ["CreatedAt", "CompletedAt"]
    for column, pointer, kind in columns:
        if kind == "instant":
            instants.append(column)
            column, kind = column + "Text", "string"
        cols[column] = TYPES[kind]
        mapping[pointer] = column
    raw = consume("entity-snapshots", cols, mapping, kc.TableType.append()).where(f"SmType == `{sm_type}`")
    latest = raw.agg_by(agg.sorted_last("Version", [c for c in raw.column_names if c != "EntityId"]), by=["EntityId"])
    return parse_instants(latest, instants).update(
        "LatencyMs = (isNull(CreatedAt) || isNull(CompletedAt)) ? NULL_LONG : diffMillis(CreatedAt, CompletedAt)")


insurance_claims_latest = _insurance_root("claim", [
    ("ClaimId", "/model/claimId", "string"),
    ("Status", "/model/status", "string"),
    ("PolicyId", "/model/policyId", "string"),
    ("Claimant", "/model/claimant", "string"),
    ("LossType", "/model/lossType", "string"),
    ("LossDate", "/model/lossDate", "string"),
    ("Description", "/model/description", "string"),
    ("ClaimedAmount", "/model/claimed/amount", "double"),
    ("ClaimedCurrency", "/model/claimed/currency", "string"),
    ("AssessedAmount", "/model/assessedAmount", "double"),
    ("Assessor", "/model/assessor", "string"),
    ("ApprovedAmount", "/model/approvedAmount", "double"),
    ("RejectReason", "/model/rejectReason", "string"),
    ("PayeeAccount", "/model/payeeAccount", "string"),
    ("PaidAmount", "/model/paidAmount", "double"),
    ("FiledAt", "/model/filedAt", "instant"),
    ("ClosedAt", "/model/closedAt", "instant"),
])
insurance_payouts_latest = _insurance_root("payout", [
    ("PayoutId", "/model/payoutId", "string"),
    ("Status", "/model/status", "string"),
    ("ClaimId", "/model/claimId", "string"),
    ("PayeeAccount", "/model/payeeAccount", "string"),
    ("Method", "/model/method", "string"),
    ("AmountAmount", "/model/amount/amount", "double"),
    ("AmountCurrency", "/model/amount/currency", "string"),
    ("Attempts", "/model/attempts", "long"),
    ("Reference", "/model/reference", "string"),
    ("FailureReason", "/model/failureReason", "string"),
    ("ScheduledAt", "/model/scheduledAt", "instant"),
    ("DisbursedAt", "/model/disbursedAt", "instant"),
])
insurance_policies_latest = _insurance_root("policy", [
    ("PolicyId", "/model/policyId", "string"),
    ("Status", "/model/status", "string"),
    ("HolderName", "/model/holderName", "string"),
    ("Product", "/model/product", "string"),
    ("PremiumAmount", "/model/premium/amount", "double"),
    ("PremiumCurrency", "/model/premium/currency", "string"),
    ("CoverageLimit", "/model/coverageLimit", "double"),
    ("Deductible", "/model/deductible", "double"),
    ("StartDate", "/model/startDate", "string"),
    ("EndDate", "/model/endDate", "string"),
    ("Endorsements", "/model/endorsements", "long"),
    ("BoundAt", "/model/boundAt", "instant"),
    ("ClosedAt", "/model/closedAt", "instant"),
    ("CloseReason", "/model/closeReason", "string"),
])

insurance_latest = merge([insurance_claims_latest.view(["EntityId", "SmType", "State", "Version", "CreatedAt", "CompletedAt", "LatencyMs"]), insurance_payouts_latest.view(["EntityId", "SmType", "State", "Version", "CreatedAt", "CompletedAt", "LatencyMs"]), insurance_policies_latest.view(["EntityId", "SmType", "State", "Version", "CreatedAt", "CompletedAt", "LatencyMs"])])
insurance_state_distribution = insurance_latest.count_by("Entities", by=["SmType", "State"]).sort(["SmType", "State"])
insurance_completions_per_minute = insurance_latest.where("!isNull(CompletedAt)") \
    .update("Minute = lowerBin(CompletedAt, MINUTE)") \
    .count_by("Completions", by=["Minute", "SmType"]).sort_descending(["Minute"])

ECOSYSTEM_FIELDS = {
    "insurance_claims_latest": insurance_claims_latest,
    "insurance_payouts_latest": insurance_payouts_latest,
    "insurance_policies_latest": insurance_policies_latest,
    "insurance_latest": insurance_latest,
    "insurance_state_distribution": insurance_state_distribution,
    "insurance_completions_per_minute": insurance_completions_per_minute,
}
