# GENERATED by ./generate-concert-ecosystem -- do not edit: regenerated on every run.
# Ecosystem "order-events" (from entity-snapshots): Event style: latest lifecycle row per event (by status, error queue, scheduled,
# causation depth) and the latest document per keyed state.
# Loaded by concert.py, which exec()s every file in app.d/ecosystems with its
# globals (consume, parse_instants, TYPES, agg, kc, dht) and exports the tables named in ECOSYSTEM_FIELDS.
from deephaven import merge


def _order_events_root(sm_type, columns):
    cols = {"EntityId": dht.string, "SmType": dht.string, "State": dht.string, "Version": dht.int64,
            "CreatedAtText": dht.string, "CompletedAtText": dht.string}
    mapping = {"entityId": "EntityId", "smType": "SmType", "state": "State", "version": "Version",
               "createdAt": "CreatedAtText", "completedAt": "CompletedAtText"}
    instants = ["CreatedAt", "CompletedAt"]
    for column, pointer, kind in columns:
        if kind == "instant":
            instants.append(column)
            column, kind = column + "Text", "string"
        cols[column] = TYPES[kind]
        mapping[pointer] = column
    raw = consume("entity-snapshots", cols, mapping, kc.TableType.append()).where(f"SmType == `{sm_type}`")
    latest = raw.agg_by(agg.sorted_last("Version", [c for c in raw.column_names if c != "EntityId"]), by=["EntityId"])
    return parse_instants(latest, instants).update(
        "LatencyMs = (isNull(CreatedAt) || isNull(CompletedAt)) ? NULL_LONG : diffMillis(CreatedAt, CompletedAt)")



# ---- event style: lifecycle rows (evt_*, one per event, latest status) and keyed-state documents (st_*)
def _order_events_events(sm_types):
    cols = {"EntityId": dht.string, "SmType": dht.string, "Status": dht.string, "Version": dht.int64,
            "CreatedAtText": dht.string, "UpdatedAtText": dht.string, "EventId": dht.string,
            "EventType": dht.string, "Domain": dht.string, "Outcome": dht.string, "Error": dht.string,
            "Attempts": dht.int64, "Retries": dht.int64, "ParentEventId": dht.string, "CausationRoot": dht.string,
            "Depth": dht.int64, "ProcessorKey": dht.string, "ScheduledAtMs": dht.int64}
    mapping = {"entityId": "EntityId", "smType": "SmType", "state": "Status", "version": "Version",
               "createdAt": "CreatedAtText", "completedAt": "UpdatedAtText", "/model/eventId": "EventId",
               "/model/eventType": "EventType", "/model/domain": "Domain", "/model/outcome": "Outcome",
               "/model/error": "Error", "/model/attempts": "Attempts", "/model/retries": "Retries",
               "/model/parentEventId": "ParentEventId", "/model/causationRoot": "CausationRoot",
               "/model/depth": "Depth", "/model/processorKey": "ProcessorKey", "/model/scheduledAt": "ScheduledAtMs"}
    raw = consume("entity-snapshots", cols, mapping, kc.TableType.append()) \
        .where("SmType in " + ", ".join(f"`{t}`" for t in sm_types))
    latest = raw.agg_by(agg.sorted_last("Version", [c for c in raw.column_names if c != "EntityId"]), by=["EntityId"])
    return parse_instants(latest, ["CreatedAt", "UpdatedAt"]).update([
        "ScheduledAt = isNull(ScheduledAtMs) ? null : epochMillisToInstant(ScheduledAtMs)",
        "AgeMs = isNull(CreatedAt) || isNull(UpdatedAt) ? NULL_LONG : diffMillis(CreatedAt, UpdatedAt)"])


order_events_events_latest = _order_events_events(["evt_reserve_inventory_event", "evt_restock_event", "evt_order_create_event", "evt_order_accepted_event", "evt_order_rejected_event", "evt_order_expiry_check_event", "evt_payment_capture_event"])
order_events_events_by_status = order_events_events_latest.count_by("Events", by=["Domain", "EventType", "Status"]).sort(["Domain", "EventType", "Status"])
order_events_event_errors = order_events_events_latest.where("Status in `ERROR_BLOCKING`, `ERROR_NON_BLOCKING`").sort_descending(["UpdatedAt"])
order_events_events_scheduled = order_events_events_latest.where("Status == `SCHEDULED`").sort(["ScheduledAt"])
order_events_causation_depth = order_events_events_latest.agg_by([agg.count_("Events"), agg.max_("MaxDepth = Depth"),
    agg.min_("Started = CreatedAt"), agg.max_("LastUpdate = UpdatedAt")], by=["CausationRoot"]).sort_descending(["LastUpdate"])
order_events_st_stocks_latest = _order_events_root("st_stock", [
    ("Sku", "/model/sku", "string"),
    ("Available", "/model/available", "long"),
    ("Reserved", "/model/reserved", "long"),
    ("Restocked", "/model/restocked", "long"),
    ("UpdatedAt", "/model/updatedAt", "instant"),
])
order_events_st_orders_latest = _order_events_root("st_order", [
    ("OrderId", "/model/orderId", "string"),
    ("CustomerId", "/model/customerId", "string"),
    ("Status", "/model/status", "string"),
    ("Currency", "/model/currency", "string"),
    ("Total", "/model/total", "double"),
    ("PaidAmount", "/model/paidAmount", "double"),
    ("RejectReason", "/model/rejectReason", "string"),
    ("ReservedLines", "/model/reservedLines", "long"),
    ("ModelCreatedAt", "/model/createdAt", "instant"),
    ("UpdatedAt", "/model/updatedAt", "instant"),
    ("ExpiresAt", "/model/expiresAt", "instant"),
])

ECOSYSTEM_FIELDS = {
    "order_events_events_latest": order_events_events_latest,
    "order_events_events_by_status": order_events_events_by_status,
    "order_events_event_errors": order_events_event_errors,
    "order_events_events_scheduled": order_events_events_scheduled,
    "order_events_causation_depth": order_events_causation_depth,
    "order_events_st_stocks_latest": order_events_st_stocks_latest,
    "order_events_st_orders_latest": order_events_st_orders_latest,
}
