# GENERATED by ./generate-concert-ecosystem -- do not edit: regenerated on every run.
# Ecosystem "trading-gen" (from entity-snapshots): latest completed entity per root, completions per minute and state
# distribution.
# Loaded by concert.py, which exec()s every file in app.d/ecosystems with its
# globals (consume, parse_instants, TYPES, agg, kc, dht) and exports the tables named in ECOSYSTEM_FIELDS.
from deephaven import merge


def _trading_gen_root(sm_type, columns):
    cols = {"EntityId": dht.string, "SmType": dht.string, "State": dht.string, "Version": dht.int64,
            "CreatedAtText": dht.string, "CompletedAtText": dht.string}
    mapping = {"entityId": "EntityId", "smType": "SmType", "state": "State", "version": "Version",
               "createdAt": "CreatedAtText", "completedAt": "CompletedAtText"}
    instants = ["CreatedAt", "CompletedAt"]
    for column, pointer, kind in columns:
        if kind == "instant":
            instants.append(column)
            column, kind = column + "Text", "string"
        cols[column] = TYPES[kind]
        mapping[pointer] = column
    raw = consume("entity-snapshots", cols, mapping, kc.TableType.append()).where(f"SmType == `{sm_type}`")
    latest = raw.agg_by(agg.sorted_last("Version", [c for c in raw.column_names if c != "EntityId"]), by=["EntityId"])
    return parse_instants(latest, instants).update(
        "LatencyMs = (isNull(CreatedAt) || isNull(CompletedAt)) ? NULL_LONG : diffMillis(CreatedAt, CompletedAt)")


trading_gen_gen_trading_orders_latest = _trading_gen_root("gen_trading_order", [
    ("OrderId", "/model/orderId", "string"),
    ("ClientId", "/model/clientId", "string"),
    ("AccountId", "/model/accountId", "string"),
    ("Symbol", "/model/symbol", "string"),
    ("Side", "/model/side", "string"),
    ("OrderType", "/model/orderType", "string"),
    ("LimitPrice", "/model/limitPrice", "double"),
    ("TimeInForce", "/model/timeInForce", "string"),
    ("Currency", "/model/currency", "string"),
    ("Quantity", "/model/quantity", "long"),
    ("FilledQty", "/model/filledQty", "long"),
    ("LeavesQty", "/model/leavesQty", "long"),
    ("RoutedQty", "/model/routedQty", "long"),
    ("AllocatedQty", "/model/allocatedQty", "long"),
    ("AvgPx", "/model/avgPx", "double"),
    ("ArrivalPx", "/model/arrivalPx", "double"),
    ("Notional", "/model/notional", "double"),
    ("TotalFees", "/model/totalFees", "double"),
    ("Status", "/model/status", "string"),
    ("RejectReason", "/model/rejectReason", "string"),
    ("CancelReason", "/model/cancelReason", "string"),
    ("ModelCreatedAt", "/model/createdAt", "instant"),
    ("AckedAt", "/model/ackedAt", "instant"),
    ("FirstFillAt", "/model/firstFillAt", "instant"),
    ("LastFillAt", "/model/lastFillAt", "instant"),
    ("ModelCompletedAt", "/model/completedAt", "instant"),
])
trading_gen_gen_trading_executions_latest = _trading_gen_root("gen_trading_execution", [
    ("ExecId", "/model/execId", "string"),
    ("OrderId", "/model/orderId", "string"),
    ("Symbol", "/model/symbol", "string"),
    ("Side", "/model/side", "string"),
    ("Venue", "/model/venue", "string"),
    ("Quantity", "/model/quantity", "long"),
    ("FilledQty", "/model/filledQty", "long"),
    ("LimitPrice", "/model/limitPrice", "double"),
    ("AvgPx", "/model/avgPx", "double"),
    ("TotalFees", "/model/totalFees", "double"),
    ("Status", "/model/status", "string"),
    ("RoutedAt", "/model/routedAt", "instant"),
    ("ModelCompletedAt", "/model/completedAt", "instant"),
])
trading_gen_gen_trading_fills_latest = _trading_gen_root("gen_trading_fill", [
    ("FillId", "/model/fillId", "string"),
    ("ExecId", "/model/execId", "string"),
    ("OrderId", "/model/orderId", "string"),
    ("AccountId", "/model/accountId", "string"),
    ("Symbol", "/model/symbol", "string"),
    ("Side", "/model/side", "string"),
    ("Quantity", "/model/quantity", "long"),
    ("Price", "/model/price", "double"),
    ("Venue", "/model/venue", "string"),
    ("Liquidity", "/model/liquidity", "string"),
    ("Fee", "/model/fee", "double"),
    ("Status", "/model/status", "string"),
    ("Ts", "/model/ts", "instant"),
])
trading_gen_gen_trading_allocations_latest = _trading_gen_root("gen_trading_allocation", [
    ("AllocId", "/model/allocId", "string"),
    ("OrderId", "/model/orderId", "string"),
    ("AccountId", "/model/accountId", "string"),
    ("Symbol", "/model/symbol", "string"),
    ("Side", "/model/side", "string"),
    ("Quantity", "/model/quantity", "long"),
    ("AvgPx", "/model/avgPx", "double"),
    ("Status", "/model/status", "string"),
    ("AllocatedAt", "/model/allocatedAt", "instant"),
    ("ConfirmedAt", "/model/confirmedAt", "instant"),
])

trading_gen_latest = merge([trading_gen_gen_trading_orders_latest.view(["EntityId", "SmType", "State", "Version", "CreatedAt", "CompletedAt", "LatencyMs"]), trading_gen_gen_trading_executions_latest.view(["EntityId", "SmType", "State", "Version", "CreatedAt", "CompletedAt", "LatencyMs"]), trading_gen_gen_trading_fills_latest.view(["EntityId", "SmType", "State", "Version", "CreatedAt", "CompletedAt", "LatencyMs"]), trading_gen_gen_trading_allocations_latest.view(["EntityId", "SmType", "State", "Version", "CreatedAt", "CompletedAt", "LatencyMs"])])
trading_gen_state_distribution = trading_gen_latest.count_by("Entities", by=["SmType", "State"]).sort(["SmType", "State"])
trading_gen_completions_per_minute = trading_gen_latest.where("!isNull(CompletedAt)") \
    .update("Minute = lowerBin(CompletedAt, MINUTE)") \
    .count_by("Completions", by=["Minute", "SmType"]).sort_descending(["Minute"])

ECOSYSTEM_FIELDS = {
    "trading_gen_gen_trading_orders_latest": trading_gen_gen_trading_orders_latest,
    "trading_gen_gen_trading_executions_latest": trading_gen_gen_trading_executions_latest,
    "trading_gen_gen_trading_fills_latest": trading_gen_gen_trading_fills_latest,
    "trading_gen_gen_trading_allocations_latest": trading_gen_gen_trading_allocations_latest,
    "trading_gen_latest": trading_gen_latest,
    "trading_gen_state_distribution": trading_gen_state_distribution,
    "trading_gen_completions_per_minute": trading_gen_completions_per_minute,
}
